### ISSUE TITLE
pyenv shell command not available for sudo

### ISSUE THREAD

**Issue by liuyigh** [pyenv/pyenv#1002]
I installed `pyenv` to `/usr/local` and activated it for all users with `/etc/profile.d`. 

I understand it is risky to install `pyenv` for all users. I did this to use one `pyenv` to serve `uWSGI/Web2Py` app under `www-data` and manage the same `pyenv` by an sudo user, since `www-data` is a non-login user.

All is fine until I encountered this error: [dbus error due to pyenv when updating packages](https://bugs.freedesktop.org/show_bug.cgi?id=103099)

As explained by the dbus maintainer, the best solution is to run system level task without custom environment. As a solution, I can switch to system python by `sudo pyenv global system`. To my surprise, my web app is still functional, running on pyenv `minconda`, not affected by this global switch.

However, if I do, `sudo pyenv shell system`, I get this error: `pyenv: no such command 'shell'`

`pyenv shell system` command is fine without `sudo`. But unfortunately it does not change the `sudo` environment.

So the question is, how do I switch the sudo shell pyenv environment without global switch? It seems the global switch solves my problem. But I am curious why the `shell` command does not work for `sudo`.

I tried to add `pyenv shims and bin` path to `secure_path` in `/etc/sudoers`. It doesn't change anything. (Do I need to reboot after changing that?)

Thank you in advance and for providing pyenv~

**Comment by blueyed** [comment]
For me `sudo pyenv shell system` gives `sudo: pyenv: command not found`, which makes sense, since `pyenv` is a function normally.  Your error indicated that you are not using the function, which handles `shell` in a special way.
`sudo pyenv shell system` also does not make sense: it would only be configured for the subshell, which exits immediately.

Since you have a specific use case, why don't you just use the pyenv version you want directly, i.e. the full path?
But this should also work: `sudo $(pyenv shell system; pyenv which python)`..
There are many ways, and `sudo -E` might also help, but it is likely better to configure the user using `sudo` in this case.

btw: `sudo pyenv global system` likely configures it for the root user only (i.e. in `/root`).

**Comment by ssbarnea** [comment]
In fact shell command is missing on MacOS completly. I have pyenv 1.1.4 installed and it does not report `pyenv shell` command as existing.

**Comment by yyuu** [comment]
It's just not available for your shell due to insufficient shell configuration. Don't mix up different things and understand your tooling.

**Comment by yyuu** [comment]
The shell commands are available only if pyenv-init has evaluated in the current shell.
