### ISSUE TITLE
pyenv doctor breaks on OpenSSL 1.1

### ISSUE THREAD

**Issue by PAStheLoD** [pyenv/pyenv#1067]
Hello!

After pyenv update, with pyenv doctor fbe25a90d1102000af484bbcd57af1ab826d37cd I get the following error:

```
Cloning /home/pas/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...

BUILD FAILED (Ubuntu 17.10 using python-build 20150326-1338-g785738d5)

Inspect or clean up the working tree at /tmp/python-build.20180102141520.15344
Results logged to /tmp/python-build.20180102141520.15344.log

Last 10 log lines:
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... yes
checking for readline/readline.h... no
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL is not installed.
Problem(s) detected while checking system.

See https://github.com/yyuu/pyenv/wiki/Common-build-problems for known solutions.
```

I've the OpenSSL dev (and regular) package(s) installed:
```
libssl-dev:amd64                                            1.1.0g-2.1+ubuntu17.04.1+deb.sury.org+1 
libssl1.1:amd64                                             1.1.0g-2.1+ubuntu17.04.1+deb.sury.org+1
libssl1.0.0:amd64                                           1.0.2g-1ubuntu13
```

And of course OpenSSL 1.1 lacks the SSL_library_init function

```
$ readelf -a   /usr/lib/x86_64-linux-gnu/libssl.a | grep -i library
     9: 0000000000000230    97 FUNC    LOCAL  DEFAULT    1 ssl_library_stop
```

So configure fails.

But `pyenv install 3.7.0a3` for example succeeds.

**Comment by yyuu** [comment]
wrong repo to report to https://github.com/pyenv/pyenv-doctor

**Comment by PAStheLoD** [comment]
Issues seems to be disabled on pyenv-doctor repo, hence the report here.

**Comment by pythoninja** [comment]
Kubuntu 18.04 LTS. Same issue here. Issues on pyenv-doctor are disabled.

**Comment by montefra** [comment]
I also this issue on Ubuntu 18.04. Below is the full log.

I have ``libssl-dev`` installed. To make ``pyenv doctor`` happy I have to install ``libssl1.0-dev``, but it annoys a lot of other packages, like a lot of stuff of the nodejs stack.

@yyuu, @joshfriend, anyone else responsible: please reopen the issue until it get fixed or enable issues in ``pyenv-doctor``, so that this problem can be correctly reported.

----

/tmp/python-build.20180823212043.13692 ~/.pyenv/plugins/pyenv-doctor
Cloning into 'python-pyenv-doctor'...
warning: --depth is ignored in local clones; use file:// instead.
/tmp/python-build.20180823212043.13692/python-pyenv-doctor /tmp/python-build.20180823212043.13692 ~/.pyenv/plugins/pyenv-doctor
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... yes
checking for readline/readline.h... no
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL is not installed.

**Comment by cloudbring** [comment]
I have the same issue. It seems pyenv/pyenv-doctor#1 should fix this issue but, doesn't for me and another person in that thread. Either way, it seems to work regardless of what `pyenv doctor` says.

**Comment by Almenon** [comment]
Same issue. @yyuu can you enable issues in pyenv-doctor please?

**Comment by rossmacarthur** [comment]
I have this problem on macOS

Output of `pyenv doctor`

```
Cloning /Users/ross/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.3 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6z/sf_vd_bd08x9cl_4_6g8g5sr0000gn/T/python-build.20190213083157.23123
Results logged to /var/folders/6z/sf_vd_bd08x9cl_4_6g8g5sr0000gn/T/python-build.20190213083157.23123.log

Last 10 log lines:
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... yes
checking for readline/readline.h... no
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL is not installed.
Problem(s) detected while checking system.

See https://github.com/pyenv/pyenv/wiki/Common-build-problems for known solutions.
```

But I can install python fine with `pyenv install 3.7.2`.

Output of `openssl version`

```
LibreSSL 2.6.5
```

**Comment by yssource** [comment]
I have this problem on archlinux.

``` bash
Installing python-pyenv-doctor...

BUILD FAILED (ManjaroLinux 18.0.2 using python-build 1.2.9-4-g6b041822)

Inspect or clean up the working tree at /tmp/python-build.20190215214228.9238
Results logged to /tmp/python-build.20190215214228.9238.log

Last 10 log lines:
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... yes
checking for readline/readline.h... no
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL is not installed.
Problem(s) detected while checking system.

See https://github.com/pyenv/pyenv/wiki/Common-build-problems for known solutions
```

**Comment by kbakk** [comment]
On MacOS Mojave (10.14) I was able to run `pyenv doctor` with these variables exported:

```sh
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include
```

**Comment by guiemi** [comment]
Thank you so much, @kbakk!

**Comment by Prateek13727** [comment]
Thank-you @kbakk. Its the generosity of folks like you that helps all of us to code and build products that change lives.
