### ISSUE TITLE
is pyenv/pyenv-installer deprecated?

### ISSUE THREAD

**Issue by joshsleeper** [pyenv/pyenv#1116]
@yyuu @joshfriend 

Seeing as how instead of enabling issue tracking for [`pyenv/pyenv-update`](https://github.com/pyenv/pyenv-update) you (unsure who, I just know that it changed rather shortly after I responded to my unresolved issue) *chose to disable* issue tracking (thus removing my access to the issue I had filed) for [`pyenv/pyenv-installer`](https://github.com/pyenv/pyenv-installer), that makes me wonder if the intent is to completely stop supporting those projects.

Is this the case?
If not, can you explain why issues have been disabled for `pyenv/pyenv-installer`?

**Comment by joshfriend** [comment]
> chose to disable issue tracking (thus removing my access to the issue I had filed)

To be honest, I think that was a bit ridiculous. Instead of turning off issues completely, it seems better to me to just "unwatch" the repo if you don't plan on actively supporting it. That way other users can still help each other and see if anyone else has a problem or potential way to solve it.

**Comment by joshsleeper** [comment]
Yea, it was a pretty shocking response.
If @yyuu doesn't want to maintain those repos, that's _totally_ ok, but shutting the community out completely seems pretty extreme.

**Comment by yyuu** [comment]
At first clearly the pyenv project is active. (In reality, pyenv-installer isn’t active as pyenv since it’s not on interest on many people as its core project). In reality, it’s not easy to me to allocation some portion of time for this project these days, but I believe we’re still managing changes in timely manner as it should be.

And, sorry all for my ridiculous doing. My excuse for it is that the issue was keep opened _unintentionally_ on the project and I noticed it after your comment. I just closed the issue after realizing and then I lost communication channel about the ongoing thing. That’s it.

IMHO, issues on pyenv projecst are not working well at least. People are reporting something as _issues_ of pyenv, but most of them are some issue of their machine setup, networking issue, etc. Clearly these stuffs are not something intrinsic issue of pyenv implementation. There are too many people reporting and 104 opened issues as of Mar 14 2018. Those issues are nearly neglected since no one is motivated or incentivized to close these issues. With monotonically increasing number of opened issues, it’s too easy to overlook something important. I don’t think GitHue issues are the best place for some kind of knowledge sharing. We have Gitter room and people can use some external site (e.g. StackOverflow, Twitter, etc.) to help each other. What I wanted for is to keep focusing this project on GitHub mainly for development purpose.

BTW, in my understanding, “Not watching” doesn’t work for me since I *was* still willing to receive some pull requests to these projects. (Plus, people tends to unnecessarily mention my name in their issue; it’s another issue) However, I will give up the maintenance of https://github.com/pyenv/pyenv-installer and https://github.com/pyenv/pyenv-update since I’m not keen on these project at all. My will is, I will keep joining to project as a core committer for most of projects, but not on pyenv-update and pyenv-installer.

**Comment by joshfriend** [comment]
I think having [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) (especially in the main `pyenv`) repo would be very helpful. This template could include:

* Link to the common build problems wiki
* Reminder for homebrew users to add the `init` to their shell
* Reminder to search closed issues
* Request for info about os/python version/pyenv version/etc since most people leave that out
* Request for a verbose build output via `PYENV_DEBUG`
* Links to the Gitter.im chatroom
* Links to StackOverflow questions tagged with `pyenv`

> We have Gitter room and people can use some external site (e.g. StackOverflow, Twitter, etc.) to help each other.

Personally, I still prefer github issues to both of those options, but I do think they have value, so they should at least be linked in the README.

> “Not watching” doesn’t work for me since I was still willing to receive some pull requests to these projects. (Plus, people tends to unnecessarily mention my name in their issue

 Thats fair 😆

**Comment by yyuu** [comment]
I've opened #1123 for issue templates. I think this issue doesn't make any sense anymore. Closing.

**Comment by joshsleeper** [comment]
@yyuu 
sorry for the delayed response, and thanks so much for getting back to me!

## title clarification
first off, for clarification, the title was referring to the `pyenv-installer` repo in the `pyenv` org. i have no doubts that `pyenv` itself is alive and well! 👍

## deprecating pyenv-installer and pyenv-update
given that the `pyenv` `README.md` [explicitly calls out using `pyenv-installer`](https://github.com/pyenv/pyenv/blob/master/README.md#the-automatic-installer) i just assumed that that was a stable and convenient way to use/maintain my `pyenv` install.
i would strongly suggest either formally deprecating those repos (declared at the tops of their `README.md`s, ideally), or ensuring that someone else is actually committed to maintaining them.

## issue templates
i totally support the issue templates, they really do help cut down on issue cruft, and give maintainers a great excuse to not waste their time on issues where people can't do their due diligence. good call!

## moving away from github issues
last but certainly not least, moving away from github issues.
so, i know you say they're not working out, but i totally disagree that just because people file issues without 100%, absolute, undeniable proof that it's a `pyenv` bug means that github issues are worthless.

yes, people will always file totally unrelated issues, but they'll ask those same unrelated questions on stackoverflow, twitter, or gitter anyway, and ignoring them in either place is going to have a similar effect: people who are frustrated because they can't use your product (which is great, btw) and have a desire or need to do so.

having the ability to go to a product repo like this and say:

> hey, i really want to use your thing, but this isn't working for me.
> can someone help point me straight?

is extremely valuable, and i really worry that you'd be hurting `pyenv` more than helping it by doing so.

## suggested path forward
1. merge those issue templates and make sure people are using them on all _new_ issues.
    * closing old issues just because they don't follow the brand new templates is a guaranteed way to get a lot of people angry and even less willing to use `pyenv`, so i'd avoid doing that.
2. declare (in their appropriate `README.md` files) that `pyenv-installer` and `pyenv-update` are deprecated until the point at which someone else wants to commit to taking on the work. no shame in saying that you can't or won't keep up with something, and if they're really that useful then people will inevitably come to support them.
3. take a few nights or a weekend or something and just sift through as many existing issues as you can. focus on either helping people get up and running (and improving related docs/code where you can!) or giving suggestions on how to verify whether or not it's actually a `pyenv` issue.
