### ISSUE TITLE
Install python-gdb.py

### ISSUE THREAD

**Issue by altendky** [pyenv/pyenv#1190]
I just had occasion to learn about and use `python-gdb.py` yesterday and it seems like it would be a good idea for pyenv to install it rather than requiring a builder to keep the source tree around.  Unless i'm missing something about the script requiring the whole source tree.  It gets generated directly in the root of the build right next to the binaries.

Hopefully I'll get a chance soon to look at adding this myself but I like to announce first anyways so people can weigh in and tell me preemptively if I'm on the wrong track.

**Comment by ikzelf** [comment]
If this helps to get rid off dbg message like ~/.pyenv/shims/python": not in executable format: File format not recognized it would be very welcome. It's not so easy at all to get the python extensions into dbg at the moment. (for me)

**Comment by altendky** [comment]
@ikzelf, I don't know about that.  For me it turned a (nearly) worthless generic C stack trace on a segfault into something with Python stack frames so I could actually see what method of mine triggered it.  Well, by sourcing the `python-gdb.py` file and then running `py-bt` in gdb rather than just `bt` it did that.

**Comment by krassowski** [comment]
@ikzelf, I bumped into this message too, see my answer at SO: https://stackoverflow.com/a/53007303/6646912

**Comment by altendky** [comment]
@krassowski @ikzelf, perhaps there should be another ticket for that issue?  Unless installing `python-gdb.py` fixes your issue as well?  In my case I was able to run my code just fine (I forget exactly what command) but I didn't have the Python extensions in gdb without manually copying `python-gdb.py` over from the build.

**Comment by chrahunt** [comment]
I did some investigation on this. The most convenient setup seems to be the following:

1. Copy `python-gdb.py` from the root of the build directory into the output directory as `bin/python3.7-gdb.py`. gdb automatically looks for `{object file}-gdb.py` and will run the file assuming it is in a safe path. `{object file}` is determined after all symlinks have been resolved.
2. Add `add-auto-load-safe-path ~/.pyenv` to `.gdbinit`.
3. Configure all tools that create virtual environments to use symlinks instead of copying the Python interpreter into the virtual environment's `bin` directory. This should be automatic when executing something like `python -m venv` but I noticed that e.g. `poetry` creates a copy instead of a symlink (see sdispater/poetry#779).

This satisfies the following use cases:

1. Debugging an existing Python process that was run using a pyenv-managed `python`. Given a Python process with pid 5555, you can start gdb and attach with `gdb -ex 'attach 5555'`. Then since the script matches the expected format it will be automatically loaded.
2. Starting a new Python process under gdb outside of a virtual environment. Executing `gdb $(pyenv which python)` will result in the script being automatically loaded.
3. Starting a new Python process under gdb within a virtual environment. Executing `gdb python` within the virtual environment will result in the script being automatically loaded. Again, this requires that the virtual environment is using symlinks.
4. Starting a Python command-line script under gdb outside of or within a virtual environment. Assuming the module cannot be executed as `python -m <module>` (which is more convenient and can use 1 or 2) we can extract the shebang like e.g. `gdb $(head -1 $(which pytest) | cut -b '3-')` which will result in the script being automatically loaded.
