### ISSUE TITLE
how to install 32bit version of exsisting python 

### ISSUE THREAD

**Issue by elahia** [pyenv/pyenv#1192]
Hello everybody,
I installed python2.7 (64bit) on my ubuntu 16.04 (amd 64bit )which is installed via WSL.
now I need to install 32-bit version of python2.7!
I don't want to install python3, which makes me confused to handle it, 
So how can i use pyenv to fix it?

and the gcc version is: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609 

Cheers,

**Comment by chrahunt** [comment]
If you installed python 2.7 via `apt`, then you can install python 2.7 32-bit by following the instructions in #829, specifically:

```
env CFLAGS="-m32" LDFLAGS="-m32" pyenv install 2.7.15
```

If you installed python 2.7 via pyenv then right now, since pyenv does not support multiple architectures for a single version, you will need to install a different version than the one you have already installed. When you install the different version, use the flags I mentioned above.
