### ISSUE TITLE
Pyenv interrupt command search

### ISSUE THREAD

**Issue by 4hiziri** [pyenv/pyenv#1210]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Linux mint 18.3
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: pyenv 1.2.7-3-g5603eb5
- [ ] Python version: Not related
- [x] C Compiler information (e.g. gcc 7.3): gcc 5.4.0
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

In my environment, iconv command doesn't work because pyenv interrupt command searching.
```sh
$ iconv
pyenv: iconv: command not found

The `iconv' command exists in these Python versions:
  anaconda3-4.3.1
```
Of course, I can fix this by temporary solution, `export PATH="/usr/bin/:$PATH".
But, I think this pyenv behavior is useless and  pyenv should allow shell to search next path.
I want pyenv to print such a message only when any command isn't found.
At least, want not stop searching command.
Python command itself is exception but other commands shouldn't be blocked.
How do you think this idea?

**Comment by jinjiren** [comment]
Just curious about the behavior, so you mean it will block other Python environments that are not managed by pyenv?

**Comment by 4hiziri** [comment]
I didn't mean that you said, iconv which I want to execute is just elf.
But I seem that it is also possible to block other Python environments not in pyenv.

I think it depends on PATH order and a name of command.
If every command which exists in several paths(in my case, that is iconv) is found in $PYENV_ROOT/shims at first, $PYENV_ROOT/shims/command shows message "pyenv: <cmd>: command not found".
Because of this, I can't execute the same name command in other path.

**Comment by botamochi6277** [comment]
Using git and pandoc, I have same problems in macOS.

```bash
MacBook:~ botamochi$ pyenv --version
pyenv 1.2.1

MacBook:~ botamochi$ git 
pyenv: git: command not found

The `git' command exists in these Python versions:
  anaconda3-5.0.1/envs/opensim-rl

MacBook:~ botamochi$ pandoc
pyenv: pandoc: command not found

The `pandoc' command exists in these Python versions:
  anaconda3-5.0.1
```

**Comment by 4hiziri** [comment]
I found other examples, dbus and python3-louis.
Their update `apt update && apt upgrade` failed because of `pyenv: dbus-send: command not found`, `pyenv: python3.5: command not found`.

**Comment by chrahunt** [comment]
Similar to #1204.

**Comment by extsoft** [comment]
**[Black](https://black.readthedocs.io/en/stable/installation_and_usage.html) case**

I have several Black's installations:
1. global by `brew install black`
2. project-specific by `pip install black`

And if I try to run `black` out of projects directories, I see the error:
```bash
~ black
pyenv: black: command not found

The `black' command exists in these Python versions:
  3.6.3/envs/a
  3.6.3/envs/b
  3.6.5/envs/c
  3.7.0/envs/d
  3.7.0/envs/e
  3.7.0/envs/f
  3.7.0/envs/python-in-docker
  3.7.0/envs/g
```

I expect to see `black` running as it a system command. And this is not the same as #1204 that cares about the hierarchy of Python installations. 

This issue is about if a system command has the same name as one of `shims` commands have, then it won't be executed when it's not available in the current Python environment. 

Does it make sense?

**Comment by pscosta5** [comment]
@extsoft Did you ever find a solution to this? I've been struggling with this for a while.

**Comment by extsoft** [comment]
@pscosta5 I've found the following workaround. When the shell (Bash, Zsh, ...) loads  `$(pyenv init -)` line from a profile file (like `.zshrc`, `.bash_profile`, etc.), then `pyenv` updates (rehashes) the `~/.pyenv/shims` directory and adds executable scripts for all executable packages from all Pythons environments. So, I simply remove unneeded scripts from `~/.pyenv/shims`. My `.zshrc` has the following configuration (the order is important):
```shell
# Python
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
## rm bad python files
rm -f ~/.pyenv/shims/{black,blackd,grip}
```

And, while working with Python packages, now I always use `python -m <package name> ...` to run any package. For instance, `python -m black` instead of `black` - so the package is 100% used from the current Python environment.

**Comment by pscosta5** [comment]
@extsoft Thanks a lot for getting back, it's really appreciated.

I get it—you essentially have a blacklist. That's a smart workaround.

**Comment by a-trawka** [comment]
@extsoft Thanks, I've been struggling with the same problem for months. Removing black-related shims helped.
