### ISSUE TITLE
use existing pythons rather than building new ones all the time...

### ISSUE THREAD

**Issue by cjw296** [pyenv/pyenv#1244]
### Description

Unless I'm missing something, I can't see any way to add existing pythons installed by other means to pyenv's list of available pythons.

I want to do this for a couple of reasons:

1. I already have a tonne of pythons installed, no point in rebuilding them, I just want to flip between them in the graceful way that pyenv allows.

2. I don't want, and nor do I think we should be encouraging, people who just want to use a python version to have to learn how to compile it, particularly on platforms like macOS and Windows where that's non-trivial.

In relation to 2, in larger organisations this causes significant problems where people start trying to use pyenv and then ask for development libraries to be installed on production machines.

**Comment by purificant** [comment]
pyenv stores python builds and symlinks to virtual environments in `~/.pyenv/versions`, theoretically, if you were to create a new virtual environment with a python interpreter of your own choosing and then add a symlink and a `pyvenv.cfg` then pyenv might pick it up and allow you to work with it.

However, that being said, pyenv excels at building specific python versions and allowing you to easily mix and match python interpreter builds and virtual environments, if you do not want to build from source perhaps it's not the best tool for your use case.

**Comment by cjw296** [comment]
Yeah, I wonder if there'd be appetite for support for a `pyenv register` command, or some such, to register existing Python installations?

From a sysadmin perspective, I wish there was a global config file we could lay down somewhere in `/etc` that would prevent pyenv from attempting to download and build local python installations. Would be handy for the place where I work!

**Comment by joshfriend** [comment]
I'm confused, if you want to configure pyenv to not do anything, why are you using it?

**Comment by cjw296** [comment]
I was the path hacks that pyenv does, and the ability to switch between the pythons that it knows about.

**Comment by smheidrich** [comment]
+1 on something like ``pyenv register`` for Python versions installed e.g. via the system package manager. This would be useful e.g. for people who only need ``pyenv`` in order to be able to use ``poetry`` as intended (cf. https://github.com/sdispater/poetry/issues/522), and who only want switch between Python 2.x and 3.y (usually, packages for *some* x and *some* y are simultaneously available in operating system repositories).

**Comment by guhur** [comment]
I just had a great experience with this [plugin](https://github.com/doloopwhile/pyenv-register).

I am on a machine without `sudo` access, and I couldn't install the dependencies for `pyenv`. So, I installed `python 3.7.3` using `conda`, and then registered their version with this plugin.

**Comment by native-api** [comment]
If you have an existing Python installation under `<prefix>`, you can symlink `$(pyenv root)/versions/<arbitrary name>` to that prefix. Pyenv would see and handle it like any other version entry.

Of course, this is not an officially supported setup so we cannot guarantee that there won't be issues -- e.g. that foreign installation can be missing something that `pyenv-build` creates, or malfunction when called through such a symlink.

**Comment by cjw296** [comment]
@native-api "here's a hack which we won't support" isn't a great reply to a feature request...

**Comment by native-api** [comment]
It's not a "hack" from Pyenv's POV. I'm pretty sure that this is exactly what the linked plugin does -- so if you want a "supported" way, that's the way to go.

But it can be a hack from the POV of the installation. We cannot vouch for the good behavior of some arbitrary lump of code, now can we?

**Comment by rogerdahl** [comment]
Just to add another use case for the suggested `pyenv register` --  I'm doing some FreeCAD scripts. These scripts must run in a venv that is part of FreeCAD. So the venv is installed along with FreeCAD and just has to be activated. It would be great if pyenv could handle the activation in the same way as those created with pyenv.

**Comment by hierophect** [comment]
I have a use case where I'm forced to use an application-installed version of python (from KiCad). Found this thread - I'm a bit surprised more people haven't requested this? I guess it's a bit of a niche use case but still seems like a reasonable feature.

**Comment by native-api** [comment]
In case https://github.com/pyenv/pyenv/issues/1244#issuecomment-491229852 was unclear,

there's the [`register` 3rd-party plugin](https://github.com/doloopwhile/pyenv-register) for this function.

See this and other 3rd-party plugins at https://github.com/pyenv/pyenv/wiki/Plugins

**Comment by rjlasko** [comment]
I recently found this thread while trying to achieve the same goal as the OP, also noting that `jenv` has this same fundamental capability.  Sadly, the original [pyenv-register](https://github.com/doloopwhile/pyenv-register) repo failed to work for me and is no longer being maintained as it can be seen in the "Public Archive" state.

Fortunately it was forked, and it seems that both have updated the original script to restore the intended functionality. They are:
https://github.com/hell-pl/pyenv-register
https://github.com/garyp/pyenv-register

I have verified that the first fork works, and wanted to post that to this thread so that any other similarly minded individuals have a clear path forward.
