### ISSUE TITLE
Question: What are hash strings in python-build recipes packages URL?

### ISSUE THREAD

**Issue by toniher** [pyenv/pyenv#1250]
I was trying to add new conda recipes to python-build and I noticed the string after the package URL. They do not have the same length as the provided MD5 (here: https://repo.anaconda.com/miniconda/) What are they? 
EDIT: They seem to work with MD5 hashes provided at the miniconda repo despite being shorter...

**Comment by joshfriend** [comment]
The hashes are SHA256. MD5 is now considered "insecure" because of how easy it is to intentionally generate hash collisions. You will see SHA256 (or sometimes even stronger) used by many tools such as NPM/Yarn/Pipenv.

Not all pythons have the SHA256 listed on the downloads page, so we have to compute it manually:

```sh
shasum -a 256 ./path/to/file(s)
```

Whomever reviews PRs for new pythons should be downloading the files themselves and verifying the checksums if they are not available from the authors of the python distribution
