### ISSUE TITLE
pyenv fails with segmentation fault when trying install 2.6.6

### ISSUE THREAD

**Issue by MikHulk** [pyenv/pyenv#1279]
### Description
- [x] Platform information:
   Fedora release 29 (Twenty Nine)
   Linux localhost.localdomain 4.20.4-200.fc29.x86_64 #1 SMP Wed Jan 23 16:11:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- [x] OS architecture: amd64
- [x] pyenv version: pyenv 1.2.9-4-g6b041822
- [x] Python version: 2.7.15
- [x] C Compiler information : gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
- [x] Please attach verbose build log as gist
   - here the pyenv install 2.6.6 output: https://gist.github.com/MikHulk/8229e36a33f9ae958a86ae5d84d08449
   - here the build log: https://gist.github.com/MikHulk/c95f23938fa6439711692b7ebb4e90c1

**Comment by chrahunt** [comment]
Given the GCC version this is probably related to #1298. If that's the case I don't think it would be effective to try and fix this directly. Can you try using an older compiler?

**Comment by MikHulk** [comment]
hi,

thank you for your answer. Sadly, I don't think to have time to try an older compiler. I use pyenv with the GCC version provided by Fedora 29. Could anyone test this instead ? 

I will try to find the time, but I am afraid I cannot do this right now.

Very sorry, about this,

**Comment by chrahunt** [comment]
This fault is very likely with Python 2.6, not pyenv. The options are:

1. Use a newer version of Python
2. Use the default Python 2.6 sources with a more appropriate compiler
3. Patch Python 2.6 or change compiler arguments to work with the compiler you have

1 should be easy with pyenv, please let us know if it is not (in a separate issue).

2 should be straightforward if you have docker. The issue I linked above seems to only impact gcc 8 so you can pull e.g. [gcc:7](https://hub.docker.com/_/gcc/) and run your build using it and see how it goes, or use tag 6 or 5. If you go this route make sure you follow the instructions for the base platform used in the [wiki](https://github.com/pyenv/pyenv/wiki). For example, if the gcc image is based on debian, follow the debian instructions. Instead of using the gcc image you can also use an older fedora image. It looks like they have all the way back to 20 available under `fedora:20`. This advice is all I can give - for more you should post a question on Stack Overflow.

3 will be hard and time-consuming, with very little payoff since the issue has likely been fixed already in the years since Python 2.6.6 was released. You will need to search the Python issue tracker with the command that was being run (`./python -E ./setup.py -q build`) and possibly some keywords/function names from the stack trace that was produced. Or you can re-run `pyenv install` with `-k` and debug the core directly (which should be in `~/.pyenv/sources/2.6.6/Python-2.6.6` unless you have another core pattern set) and reason about what may have caused the segfault. These `gdb` commands can help: `$_siginfo`, `bt`, `info locals`, `x`, `p`. It may also be worth back-porting `python-gdb.py` to work with Python 2.6.6.

**Comment by MikHulk** [comment]
Thank you for this very detailed answer. Usually I use python 3 but we have old applications running on python 2.6 in production. I have no problem with others versions. I keep the solution 2 with docker if I have to come back to the issue I experienced. I get back to you if I have this  occasion.

At now I am on everything else, I would be glade to help with this issue, I just miss the time to do it.

Thx again
