### ISSUE TITLE
PyPy3: pyenv: pip: command not found

### ISSUE THREAD

**Issue by paugier** [pyenv/pyenv#1286]
With pypy3, the command pip is not available 
```
ls /home/me/.pyenv/versions/pypy3.5-7.0.0/bin/
easy_install-3.5*  libpypy3-c.so*  libpypy3-c.so.debug  pip3*  pip3.5*  pypy@  pypy3@  pypy3.5*  pypy3.5.debug  python@  virtualenv-pypy*
```
so we get:
```
pip -h
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  3.7.1
```

I know that one can do `python -m pip -h` or `pip3 -h` but what works we CPython should work with PyPy.

I was wondering why there is no command `pip` with PyPy3. Is it a PyPy issue or should it be solved at the pyenv level ?

**Comment by paugier** [comment]
Note that after `pip3 install --upgrade pip`, the command `pip` becomes available...

**Comment by chrahunt** [comment]
Thanks for raising an issue (and your earlier PR!)

We re-use the PyPy distribution essentially as-is from [squeaky-pl/portable-pypy](https://github.com/squeaky-pl/portable-pypy), you can raise an issue there to see if they will change the packaging. As you stated, the most portable option is `python -m pip`. Another alternative is to always use virtual environments, then the relevant binaries will usually be available.

The `/home/me/.pyenv/shims/pip` shim looks in the `bin` directory of the active Python for an executable of the same name. The reason `pip3 install --upgrade pip` makes pip visible is because that action created `/home/me/.pyenv/versions/pypy3.5-7.0.0/bin/pip`.

**Comment by chrahunt** [comment]
Please let us know if you have any more issues!
