### ISSUE TITLE
[Feature Request] Support resolving python versions to some major or minor version

### ISSUE THREAD

**Issue by lynncyrin** [pyenv/pyenv#1349]
### What

I would like pyenv to support resolving python versions based on the latest major or minor version. In some fashion, I want to be able to say "python 2" or "python 3.4" and have pyenv make a decision about which specific python version (eg. `2.7.10` or `3.4.0`) that should be.

I imagine some "wildcard" or "latest" identifier may possibly be involved for the sake of reducing ambiguity (which I only mention because those are the words I searched while looking for this).

### Why

I, and at least a dozen other people, have used pyenv and came to the conclusion that this is a feature that fits well with pyenv. https://github.com/pyenv/pyenv/issues/602 and https://github.com/pyenv/pyenv/issues/541 provide evidence of that being the case.

### Requested Feedback

It's clear that in the past this feature has been considered, and determined to be not desirable. By creating this issue, I'm requesting that you (the maintainers) re-appraise that decision 🙂 I'll take this issue being closed as "we are explicitly deciding [again] that this feature isn't desired" and l leave the conversation there 👍

**Comment by sztomi** [comment]
I agree - this is a feature we are missing, too. Tox doesn't differentiate between 3.6.4 and 3.6.8 by default (both are "py36") because they are expected to be backwards-compatible.

As it currently stands, I have a hard time updating the python versions to the latest point versions on our CI nodes because many of our projects have .python-versions that pin that version.

@joshfriend I'm curious about the previous reasoning for not adding this feature. If there is openness to the idea after all, I'd be happy to try and contribute a PR (no idea if this is over my head, I don't know the codebase at all).

**Comment by ssbarnea** [comment]
I totally agree with @sztomi that pinning python minor versions is non maintainable. It gets even worse if you are one of those contributing to many python projects. In at least 9/10 cases when someone creates a `.python-versions`they only mean: i want `py27,py36,py37` -- they do not case about which patch release or if they ever care is to have a `>=3.6.1` because they want to avoid a bug with preivous release. So far I never seen a single case where someone wanted 3.6.1 deliberately when 3.6.2 was already available.

Another reason for accepting wildcards or ranges is cross platform availability. Maybe version 3.6.2 does not compile yet on MacOS but compiles on Linux, so bumping it would break other users.

Another issue is lack of scalability. Current design is forcing open-source contributors working on projects that use pyenv to keep an unrealistically big list of python versions installed because various projects update the file with their own speed (which sometimes can be even... not updating them at all).

**Comment by regisz** [comment]
And this would be great, because I have to recreate my all virtualenv (I use pyenv plugin for handle these) if I would like to use a newer patch version.

**Comment by viniciusban** [comment]
Use this plugin: https://github.com/momo-lab/xxenv-latest

**Comment by regisz** [comment]
Not bad, but this plugin did not support minor version handling; so, I can not use the next command for virtualenv creation:
`pyenv virtualenv 3.7 my_new_venv`
Without this I must recreate a virtualenv if I want to use a new Python version (patch too) in it.

**Comment by jack1142** [comment]
It could also be great if pyenv also supported the cases @​ssbarnea mentioned where python projects set version at `>=3.6.1` instead of just `>=3.6` - having a way to install Python 3.6.1 or greater not just "anything greater or equal 3.6" to prevent outdated pyenv from installing version that doesn't fit that requirement.

**Comment by BrandonLWhite** [comment]
For the time being, I've found using `pyenv global 3.6.10 3.8.3` gets the job done with tox envlist=py36,py38

It appears that having multiple global python versions differing only by minor version allows use of the minor version bin shim.  To illustrate:
`pyenv global 3.6.10 3.7.7 3.8.3`
`python3.6 --version`
> Python 3.6.10

`python3.7 --version`
> Python 3.7.7

`python3.8 --version`
> Python 3.8.3

The minor version shims aren't functional for me unless I do the `pyenv global` with the full versions I wish to use for each minor version.  Once my system has been setup that way, tox is happy.

**Comment by b12thompson** [comment]
I agree with @ssbarnea that the latest patch version (2.7.18 as opposed to 2.7.17) should be used and tested.  The only good reason I can think of for wanting to specify differentiating between patch versions would be to test for users who are unwilling or unable to upgrade to the latest patch release.  Maybe there are OS or vendor restrictions--who knows(?), but there is still a use case there that shouldn't go unnoticed.

**Comment by hyperknot** [comment]
Can you support the same logic as the Node / nvm community has embraced for a very long time? In nvm "3.7" means latest from 3.7.x and "3.7.7" means exactly version 3.7.7.

This limitation as of today in pyenv leads to a very a bad security practice, where developer teams and projects are very unlikely to update their Python versions to patch versions, just because probably no one will ever bother updating that file. And it's not their fault, it's clearly impossible to know which OS / package manager system is on which patch version.

**Comment by caniko** [comment]
Any progress?

**Comment by anton-petrov** [comment]
Planned in the near future.

**Comment by joshfriend** [comment]
It is still my opinion that this is not a good idea*. The purpose of pyenv is to be able to install specific versions of python (for example: to match your deployment environment exactly). When you allow "fuzzy" version behavior, your python version becomes dependent on pyenv itself, and also what versions the user has chosen to install, which is not good.

* Someone earlier in the thread mentioned tox not differentiating between patch version, and I think that's maybe the exception here. I can think of only _one time_ where a python patch version (intentionally) introduced breaking behavior (2.7.9? with the ssl stuff) and security patches are important. If someone were to add this feature, I would recommend strongly against adding a plain  `2` or `3` option which would potentially pull in feature changes. 

pyenv is by nature a tool that works best with explicit usage and something like this tends to stray from that a bit

**Comment by BrandonLWhite** [comment]
> It is still my opinion that this is not a good idea*. The purpose of pyenv is to be able to install specific versions of python (for example: to match your deployment environment exactly). When you allow "fuzzy" version behavior, your python version becomes dependent on pyenv itself, and also what versions the user has chosen to install, which is not good.
 

Probably best then to implement it like nvm as pointed out by @hyperknot .  That way both use cases are supported.

**Comment by anton-petrov** [comment]
Perhaps, it would be good to have both functionalityб to be able to run `pyenv install 3.9` or `pyenv install 3.9.2`.

**Comment by altendky** [comment]
From a user perspective, I don't understand what would be bad about being able to explicitly request that pyenv give the 'latest'.  It is nothing more than less work than manually figuring out what the latest version is.  From the developer perspective, of course, it brings a cost that the actual pyenv maintainers must weigh.  But, if it were to exist it seems the interface ought to be explicit and could be so right at the version specification.  `pyenv install 3.9.x` perhaps?  And `pyenv global 3.9.x` from the configuration side?  Fully backwards compatible with no behavior change and also reasonably unlikely to be typoed without intending the resulting functionality.  There would still be the issue of defining allowance for dev/rc/etc or not.  But, that can be ironed out if the maintainer support is achieved.  `:]`

"Duplicate my production environment locally" may have been the inspiration for pyenv.  I think it's overly restrictive to reject other uses.  Anyways, I'll take a wild guess that devs looking to match their exact single Python version of their deployment are usually just using the exact deployment Docker image instead of pyenv anyways.  I use pyenv so I'm not at the mercy of my distribution to have a Python version.  I install random new and old patch releases to help test out odd situations people on IRC ask about.  I try to keep the latest patch releases available and 'default' for when I am testing a library across all supported versions.  Being able to `for V in 3.{6,7,8,9,10}; do pyenv install $V.x; done; pyenv global 3.{9,8,7,6,5,10}.x` (plus PyPy etc) would be a lot nicer than individually querying available versions and grepping for the latest and then typing that in...  five times, etc.

Is it worth the dev time?  Sure, maybe not.  Is it an unreasonable misuse of pyenv that ought to be rejected outright?  It doesn't seem like it.  It also doesn't stop anything from getting at the exact specific version it wants.  The version retrieved for an incompletely specified `python3.8` is going to be dependent on pyenv regardless.  Either you manually installed 3.8.5 or you let pyenv pick the latest.  It's up to pyenv and your use of it regardless of this feature.  If anything, not having addressed https://github.com/pyenv/pyenv/issues/1480 seems way more hazardous to being able to specify an exact version than implementing the feature requested in this ticket would be.

**Comment by boltronics** [comment]
I think closing this was probably a mistake. The above PR only implements this for the `install` command - and also deviates from `nvm` and what was discussed here by mandating `:latest` be appended to the version. I wish we aimed to have some consistency.

It does nothing for `.python-version` unfortunately AFAICT, which I feel is the bigger issue here.

**Comment by native-api** [comment]
@boltronics Those are separate features and warrant a separate discussion for each to flesh out the details.

**Comment by boltronics** [comment]
@native-api I don't see anything about this feature request that is limited to implementing this in one specific place. As such, why would it not be discussed here? Most of the discussion of how it should be implemented applies regardless of where it is implemented, so there is some logic in not separating this out into separate bug reports - especially at this point.

Having said that, the original poster, as well as hyperknot's supplied information, was completely ignored with what has been implemented so far, despite both having many upvotes.

**Comment by native-api** [comment]
Mixing up multiple topics is a single discussion complicates working out any solution a great deal, so if you want a solution, please create separate topics for the separate feature requests that emerged in this duscussion.

The implemented feature does what the OP requested, albeit in a different way. Doing this the way they requested has a roadblock, and I'll tell you it in a separate topic about implementing it specifically that way if one is created.

**Comment by boltronics** [comment]
@native-api No worries. As requested, I have opened a separate issue. Thanks.
