### ISSUE TITLE
Any version of Python fails to build in Arch Linux

### ISSUE THREAD

**Issue by shackra** [pyenv/pyenv#1384]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Arch Linux
- [x] OS architecture (e.g. amd64): 64 bits
- [x] pyenv version: 1.2.13
- [x] Python version: 3.7.4
- [x] C Compiler information (e.g. gcc 7.3):  9.1.0
- [x] Please attach verbose build log as gist https://gist.github.com/shackra/50de40015358ff6757bdd256e0a70dae

In short, this is what happens when the build fails:

```
Downloading Python-3.7.4.tar.xz...
-> https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz
Installing Python-3.7.4...

BUILD FAILED (Arch Linux using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20190824230937.23196
Results logged to /tmp/python-build.20190824230937.23196.log

Last 10 log lines:
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/tmp/python-build.20190824230937.23196/Python-3.7.4/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
  File "/tmp/tmpg1fx0tvj/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/__init__.py", line 19, in <module>
  File "/tmp/tmpg1fx0tvj/pip-19.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/__init__.py", line 8, in <module>
  File "/tmp/tmpg1fx0tvj/pip-19.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/connectionpool.py", line 7, in <module>
  File "/tmp/python-build.20190824230937.23196/Python-3.7.4/Lib/socket.py", line 49, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'
```

**Comment by shackra** [comment]
is there anything else I can provide to help debug this issue?

**Comment by vperilla** [comment]
Seems to be related with pretty-print.c in gcc
building '_socket' extension
gcc -pthread -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wno-cast-function-type -Werror=implicit-function-declaration -I./Include -I. -I/usr/local/include -I/tmp/python-build.20190919064536.11635/Python-3.7.4/Include -I/tmp/python-build.20190919064536.11635/Python-3.7.4 -c /tmp/python-build.20190919064536.11635/Python-3.7.4/Modules/socketmodule.c -o build/temp.linux-x86_64-3.7/tmp/python-build.20190919064536.11635/Python-3.7.4/Modules/socketmodule.o

during GIMPLE pass: wrestrict
En la función ‘sock_bind’:
en pp_format, en pretty-print.c:1393
 2919 | sock_bind(PySocketSockObject *s, PyObject *addro)
      | ^~~~~~~~~
Por favor, envíe un informe completo de errores,
con el código preprocesado si es apropiado.
Véase <https://bugs.archlinux.org/> para instrucciones.
building '_ssl' extension

**Comment by vperilla** [comment]
I created a bug on Archlinux:
https://bugs.archlinux.org/task/63322

**Comment by dvzrv** [comment]
@shackra could you check, whether you have all [makedepends](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python#n16) installed, required for building python3.7?

**Comment by dvzrv** [comment]
@shackra note, that some are not required for building, but only for testing (e.g. gdb, xorg-server-xvfb)

**Comment by dvzrv** [comment]
Also, I've just successfully installed 3.7.4 using pyenv.

**Comment by dvzrv** [comment]
@shackra from the logs you provided:

> Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().

You should also look into the [required dependencies](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python#n15) for building python!

**Comment by vperilla** [comment]
If I run pyenv doctor -c -v
in order to check build dependencies I get following

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking readline/readline.h, usability... no
checking readline/readline.h, presence... no
checking for readline/readline.h,... no
checking readline/rlconf.h usability... yes
checking readline/rlconf.h presence... yes
checking for readline/rlconf.h... yes
**checking for SSL_library_init in -lssl... no
configure: WARNING: OpenSSL <1.1 not installed. Checking v1.1 or beyond...**
checking for OPENSSL_init_ssl in -lssl... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for BZ2_bzCompressInit in -lbz2... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for zlibVersion in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for sqlite3_initialize in -lsqlite3... yes
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
configure: creating ./config.status
config.status: creating Makefile

**Comment by vperilla** [comment]
Same error using flags
LDFLAGS="-L/usr/lib/openssl-1.0" CFLAGS="-I/usr/include/openssl-1.0" pyenv install 3.7.4

**Comment by shackra** [comment]
> @shackra could you check, whether you have all [makedepends](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python#n16) installed, required for building python3.7?

I had tk, sqlite, bluez-libs and llvm already

**Comment by vperilla** [comment]
For reference with last update of gcc
https://www.archlinux.org/packages/core/x86_64/gcc/
Pyenv works again

**Comment by dvzrv** [comment]
@vperilla I doubt this has anything to do with it though. I have successfully built python in many versions with the former version of gcc on several systems.
It would surprise me, if that was of relevance!

Anyhow, glad it seems to work for you again!

**Comment by shackra** [comment]
I was able to install python 3.7.4 without having to do anything else but updating Arch Linux

**Comment by RubioJr9** [comment]
'pyenv install 3.7.7' worked for me on a current Arch system
