### ISSUE TITLE
Executing pypy with pyenv requires `pyenv exec python`

### ISSUE THREAD

**Issue by kylefoley76** [pyenv/pyenv#1431]
In order to get pyenv to execute `pypy` I have to use additional steps than when I want to execute `python 3.7.1`.  I'm not sure if this is a bug or if the developers intended it that way.  In any case, the following terminal commands will demonstrate what I mean:

`Admins-MacBook-Pro-4:~ kylefoley$ pyenv versions
  system
  2.7.14
* 3.5.3 (set by /Users/kylefoley/.python-version)
  3.6.1
  3.7.3
  pypy3.6-7.1.1
Admins-MacBook-Pro-4:~ kylefoley$ python
Python 3.5.3 (default, Oct 16 2019, 03:31:08) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
Admins-MacBook-Pro-4:~ kylefoley$ pyenv local pypy3.6-7.1.1
Admins-MacBook-Pro-4:~ kylefoley$ pyenv versions
  system
  2.7.14
  3.5.3
  3.6.1
  3.7.3
* pypy3.6-7.1.1 (set by /Users/kylefoley/.python-version)
Admins-MacBook-Pro-4:~ kylefoley$ python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin`

As you can see the above is the wrong result.  I should be outputting `pypy` but it's outputting `python 3.7.3`

`Admins-MacBook-Pro-4:~ kylefoley$ pyenv exec python
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:55)
[PyPy 7.1.1-beta0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin`

As you can see I have to use the commands `pyenv exec python` to get what I want.  Is that the way it's supposed to be or am I doing something wrong?

**Comment by wizpig64** [comment]
I suspect you don't have your paths set up right. 

What happens when you execute these lines in a new shell?

```
$ echo $PATH
$ which python
```

If you don't see `pyenv` somewhere in $PATH, you haven't set that up right. If that's the case, read: 

https://github.com/pyenv/pyenv#how-it-works

If it is in there, it might not be in the right order. Or something else, like an IDE, might be injecting more path in front of pyenv's path. Or you could have activated it manually.

`which python` shows you the location of the file your shell will execute, the first folder listed in `$PATH` that has `python` in it. If the output is `/usr/bin/python`, or something similar, it's the version shipped with mac os. If it pyenv set up right, it should output something like `/Users/kylefoley/.pyenv/shims/python`. The shims ask pyenv to resolve and exec the right version.

Since the version you are getting is 3.5.3 with a fresh build date, I'm guessing `which` will resolve to `/Users/kylefoley/.pyenv/versions/3.5.3/bin/python`, which is so specific that it's not actually asking for pyenv to resolve anything. It's just using a version that pyenv installed, and bypassing the shims.
