### ISSUE TITLE
[Feature] Install latest version

### ISSUE THREAD

**Issue by zodman** [pyenv/pyenv#1439]
Hi a great feature will be

`pyenv install 3.6 --latest `

and at the end will install the last version  3.6.8

**Comment by claytron5000** [comment]
I was trying to write a shell script to do this for me, but it turns seems that my version of `grep` doesn't see the line-breaks from `pyenv install -l` as line breaks. Here's where I started:

```
pyenv install -l | grep -e "^3"
```
If I could get this to work, we could sort and pipe the latest back into `pyenv install`. Otherwise, yeah, this would be a handy built-in feature.

**Comment by novacoil** [comment]
#1349 is not specifically about `pyenv install` but both issues seem related to me.

**Comment by viniciusban** [comment]
Use this plugin: https://github.com/momo-lab/xxenv-latest

**Comment by regisz** [comment]
Not bad, but this plugin did not support minor version handling; so, I can not use the next command for virtualenv creation:
`pyenv virtualenv 3.7 my_new_venv`
Without this I must recreate a virtualenv if I want to use a new Python version (patch too) in it.

**Comment by romaingz** [comment]
@joshfriend why has this issue been closed?

Is it consider out of scope for pyenv, or is pyenv encouraging the use of the xxenv plugin?
