### ISSUE TITLE
Docs: how to test added python versions

### ISSUE THREAD

**Issue by clbarnes** [pyenv/pyenv#1445]
A common and indeed neverending dev task is to add new versions of python. The best way to test these is unclear, especially when they're added in an automated way or in bulk. e.g. #1361 has been sitting stale for some time.

What is the best way to test one, or more, added python versions, without interference with an existing pyenv installation (presumably most pyenv devs will also be pyenv users). Presumably people have been testing python versions since pyenv was created - how do you do it, and can that information be added to the README for new devs to use?

**Comment by clbarnes** [comment]
@yyuu any thoughts on this? Would be really beneficial to get PR #1361 merged and lower the barrier to entry for all contributors.

**Comment by native-api** [comment]
The way to test a Python installation is to install it and run `python -m test`.

The question is, which installations to test, and in what environments?

Plus, a test failure may be due to some kind of unfixed bug or incompatibility (especially for prebuilt versions that were built for another environment), through no fault of Pyenv.

So, I suggest to (which is how current scripts are written):

* write installation scripts with a specific range of supported environments in mind and manually test in those as per above
* base them on existing scripts since those gradually accumulate proven best practices as problems are discovered and fixed
* if it's a prebuilt binary, insert a guard like `require_distro()` to warn users if they install it in an environment that it wasn't designed for

**Comment by native-api** [comment]
Could you perhaps make a PR that would add this information to the README (a subsection in https://github.com/pyenv/pyenv/blob/master/plugins/python-build/README.md and a pointer to that README from the Developement section in the main README, I suppose)?

This is probably what you expected to see when you were looking for documentation.
