### ISSUE TITLE
pyenv don't switch between python versions on macos

### ISSUE THREAD

**Issue by gsscoder** [pyenv/pyenv#1446]
I was enable to find an issue on that, but if already exists plese let me know.

- [ ] Platform: macOS Catalina 10.15
- [ ] pyenv version: 1.2.14 (from `brew`)
- [ ] Python version: 2.7.16 (pre-installed in system)
- [ ] C Compiler information: clang-1100.0.33.8
- [ ] Python 3.8.0 build/install with Pyenv and debug switched on: https://gist.github.com/gsscoder/dcb61529b94c6f6b9e552dda22e1d9e1

I've also created a `.zshrc` file like stated in pyenv documentation (since I run zsh on iTerm). Restarted the shell and tried also `pyenv rehash`.

But also if 3.8.0 is set instead of system, `python -V` still shows system version.

**Comment by asmaier** [comment]
I have the same problem on macOS 10.14.6 (system: Python 2.7.10) with pyenv 1.2.13 and Python 3.7.4 (installed via homebrew).

**Comment by gsscoder** [comment]
Thanks for suggestion... Anyway I've already tried it first times and didn't worked.

I've put this first in `.bash_profile `than `.zshenv`, but pyenv was still unable to switch between python versions.

I think that maybe something about shell configuration (in my case `zsh`), but for now I can't figure out what it is.

**Comment by gsscoder** [comment]
Already tried! Didn't solve...

**Comment by cseder** [comment]
> Already tried! Didn't solve...

First of all, why do you even have a .bash_profile on Catalina? Have you installed Bash via brew or something after installing, or have you upgraded to Catalina from Mojave or earlier?
Catalina doesn't ship with Bash, it uses Zsh as the default shell. If you have this left over from an upgrade, copy the things you need into ~/.zprofile and delete the bash scripts unless you're actually using Bash.

Also, you should not update your PATH in .zshrc, this file is read by all processes that uses Zsh, both login shells and interactive shells. Basically every new tab you open in your terminal will execute .zshrc so it should be kept as clean as possible, used only for setting up shell and session specific stuff, not user-wide or system-wide variables. 
Aliases is fine to have in .zshrc, not exports.

Use .zprofile for setting up your PATH and other exports that is supposed to last for a user session, e.g until you log out or shut down your Mac. It is used by the login shell, but not interactive shells and other processes.

Depending on what you have installed and how it is installed you might have stuff in your shell initialization files that alters the PATH and inserts directories in front of the path, like the shims for rbenv and pyenv does. It's important to know what goes where and when.
The order in which Zsh reads your shell files on login and when firing up a Terminal is:

1. ~/.zshenv
2. ~/.zprofile
3. ~/.zshrc
4. ~/.zlogin

Not all these are required, but if they exist this is the order in which they're executed.
Also, **Apple are forcing the standard directories to be injected first in your path if you have ~/.zshenv existing by silently calling /usr/libexec/path_helper** which puts you back to square one so to speak if you're trying to manage what goes where in your PATH.

I solve this in the following way on macOS, because it has this method of action:
* Don't use ~/.zshenv (delete it)
* Don't use ~/.zlogin (delete it)
* DO USE ~/.zprofile for setting things like PATH and other exports
* DO USE ~/.zshrc for setting Zsh specific options and aliases
 
This way you only need to concern yourself with TWO files. One for setting Zsh specific stuff and one for everything else.

If you do it like this, you can put the following into your .zshrc, to force the order YOU want the entries to have:

```
# Clears every item in your path
unset path
# List all path entries you want before the "standard" PATH
PATH="\
$HOME/.cargo/bin:\
$HOME/lib/sbcl/bin:\
/usr/local/opt/openssl/bin:\
/usr/local/opt/curl/bin:\
/usr/local/opt/texinfo/bin:\
/usr/local/opt/sqlite/bin"

# Add the default directories AFTER the above (+=)
PATH+=":/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:\
/Library/Apple/bin:/usr/libexec"

# Now run the stuff that modifies the first entries in path 
eval "$(pyenv init -)"

# Clean up possible duplicates in your path (ex. if iTerm is launching shells as login shells)
# Make PATH Entries Great Again: (Unique)
typeset -aU path
# Finally, export the whole enchilada
export PATH
# Also make sure macOS gets the man pages right:
export MANPATH=$(manpath)

```
If you do it this way, you're always in control of your PATH.

Good Luck!

**Comment by gsscoder** [comment]
First of all, let me thank you for all this detailed informations and for you time!

Yes, you're right my Catalina was upgraded from Mojave where I've installed `iTerm`/`zsh`.
System Python is **2.7.15** and I've installed **3.7.5** using brew.

As soon as possible, I'll try again with your precious suggestions and post here.

Have a nice day.

**Comment by kkawabat** [comment]
I think the main headache for me was that the [installation note](https://github.com/pyenv/pyenv#basic-github-checkout) specifically notes for step 2 and step 3 that :

> Zsh note: Modify your ~/.zshenv file instead of ~/.bash_profile.

It  should be updated to:

> Zsh note: Modify your ~/.zprofile file instead of ~/.bash_profile.

**Comment by gsscoder** [comment]
I was perfectly able to setup `pyenv` on a **Debian 10** machine that uses `bash`.

I'm not a shell expert, but I think that problems I got in **macOS** are due to `zsh`. At the moment, with all wonderful help I got here, I'm still unable to have it running on my mac.

**Comment by cseder** [comment]
> I was perfectly able to setup `pyenv` on a **Debian 10** machine that uses `bash`.
> 
> I'm not a shell expert, but I think that problems I got in **macOS** are due to `zsh`. At the moment, with all wonderful help I got here, I'm still unable to have it running on my mac.

If you post / send me (PM me or whatever) the output from:

`ls -A ~ | egrep '^\.'`

**Comment by gsscoder** [comment]
@cseder, thank you for helping me so much! I really appreciate it :)

There's no problem to post here... It follows what you ask.

`$HOME` hidden files:
```
.CFUserTextEncoding
.DS_Store
.Trash
.Xauthority
.android
.atom
.bash_history
.bash_history.bak
.bash_profile.bak
.bash_profile.bak.1
.bash_sessions
.bundle
.cabal
.cache
.cargo
.config
.csi_history
.cups
.dialyzer_plt
.dlv
.dnx
.dotnet
.dropbox
.elm
.emacs
.emacs.d
.emacs~
.erlang_history
.gem
.ghc
.gitconfig
.histfile
.idris
.kindle
.lein
.lesshst
.lfetool
.local
.m2
.mono
.myprofile
.node_repl_history
.npm
.nuget
.nvm
.oh-my-zsh
.omnisharp
.oracle_jre_usage
.profile.bak
.pyenv
.pylint.d
.python_history
.rnd
.rustup
.sbcl_history
.sbclrc
.scala_history
.slime
.slime-history.eld
.ssh
.subversion
.swt
.templateengine
.v8flags.3.28.71.19.giacomo.json
.vim
.viminfo
.vimrc
.virtualenvs
.vscode
.wget-hsts
.zcompdump
.zprofile
.zprofile.bak
.zsh_history
.zshenv-pyenv
.zshrc
.zshrc-e
.zshrc.bak
.zshrc.bak.2
.zshrc.pre-oh-my-zsh
.zshrc~
```

**.zprofile**:
```
# erlang
export ERLHOME="/usr/local/Cellar/erlang/17.5"
export ERLINCL="$ERLHOME/lib/erlang/usr/include"

# lfe
alias lfe='$HOME/opt/lfe/bin/lfe'

# rebar3 alpha
alias rebar3='$HOME/opt/rebar3/rebar3'

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# custom binaries
export PATH="/opt/bin:$PATH"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# pyenv
#eval "$(pyenv init -)"

# more customizations
source $HOME/.myprofile
```

**.myprofile**:
```
# colorize ls out
alias ls='ls -G'
# common ls aliases
alias ll='ls -lha'
alias la='ls -A'
alias l='ls -CF'

# custom aliases
alias gohack='cd $HOME/OneDrive/Hacking'
alias goproj='cd $HOME/OneDrive/Projects'

# grep options
export GREP_OPTIONS="--color=always"
export GREP_COLOR="1;35;40"

# editor
export VISUAL=nvim
autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# history search
bindkey -v
bindkey '^R' history-incremental-search-backward

# line movement
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
```

**.zshrc**:
```
# virtualenv
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/pyenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh

# pyenv
eval "$(pyenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

If you need something more, please ask me.
Have a nice day.

**Comment by cseder** [comment]
Ok, first of all, you should clean up the stuff that's not needed, because this listing triggers my OCD big-time.

**These files are not used in Catalina** and are leftovers from Bash:

```shell
.bash_history
.bash_history.bak
.bash_profile.bak
.bash_profile.bak.1
.bash_sessions
.histfile
```

Just get them out of the way, delete them, archive them or something.
Also, stick with **TWO FILES for your shell configuration**: .zprofile and .zshrc.

Are you using 'Oh My ZSH'? Or are the files just leftovers?
If you ARE using OMZ, make sure that the edits I propose gets added after all the OMZ s*it.
If you're not using it, delete the following:

```shell
.oh-my-zsh
.zshrc.pre-oh-my-zsh
```

Example Zsh startup files for your configuration, assuming you're using Homebrew (brew.sh)
Move stuff to .zprofile + .zshrc & get rid of .myprofile

**Example .zshrc file:**

```shell
# .zshrc
export TERM="xterm-256color"
export LANG="en_US.UTF-8"
export CLICOLOR=1
export VISUAL=nvim
export ERLHOME="/usr/local/Cellar/erlang/17.5"
export ERLINCL="$ERLHOME/lib/erlang/usr/include"
export CARGO_HOME="$HOME/.cargo"
export GREP_OPTIONS="--color=always"
export GREP_COLOR="1;35;40"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=500
SAVEHIST=500

# Common aliases
alias ls='ls -G'
alias ll='ls -lha'
alias la='ls -A'
alias l='ls -CF'

# Custom aliases
alias gohack='cd $HOME/OneDrive/Hacking'
alias goproj='cd $HOME/OneDrive/Projects'
alias rebar3='$HOME/opt/rebar3/rebar3'

# Misc Configuration
autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# History search options
bindkey -v
bindkey '^R' history-incremental-search-backward

# Line movement
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
```

**Example .zprofile file:**
 Set up $PATH, start by emptying it, then build from there:

```shell
# .zprofile
unset path
PATH="\
$HOME/.cargo/bin:\
/opt/bin:\
/usr/local/bin:\
/usr/local/sbin:\
/usr/bin:\
/bin:\
/usr/sbin:\
/sbin:\
/Library/Apple/usr/bin:\
/Library/Apple/bin:\
/usr/libexec"

# These will all alter your PATH, so place them in correct order:
# Set up NVM (No need for the Bash completion part)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# virtualenv
export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/pyenvs"
export VIRTUALENVWRAPPER_PYTHON="/usr/local/bin/python3"
source /usr/local/bin/virtualenvwrapper.sh

# pyenv (this should be added last to get first in PATH)
eval "$(pyenv init -)"

# Make $PATH Entries Great Again (Unique, just in case) & export:
typeset -aU path
export PATH

# Export MANPATH
export MANPATH=`/usr/bin/manpath`
```

**BACKUP YOUR CURRENT FILES BEFORE CHANGING THEM!**
I can't guarantee that you'll have success with this, but this is the way I've managed the dreaded PATH related issues for many years.

**Good luck!**

**Comment by gsscoder** [comment]
@cseder , I'm very grateful of your help!
I executed your instructios and I'm sure a got a better shell configuration...

Unfortunately `pyenv` still doesn't work:
```
$ pyenv versions
  system
* 3.8.0 (set by /Users/giacomo/.python-version)
$ python -V
Python 2.7.16
```
I tried `pyenv global 3.8.0` and `pyenv local 3.8.0` various times but nothing happens.

Is there a way to put pyenv in *DEBUG MODE*? I way to make it more verbose and spot the issue?

Again, thank for your time.

**Comment by cseder** [comment]
If you want to make sure you have the pyenv version executed first, add the pyenv shims dir as the first line in the list of paths in the .zprofile file:

```shell
PATH="\
$HOME/.pyenv/bin:\
$HOME/.cargo/bin:\
...

```

And make sure you do a
`zsh -l`
or 
`exec "$SHELL"`

After changing the shell files or log out and back in...

**Comment by gsscoder** [comment]
@cseder, thanks for suggestions! I'll try everything and post here.

In both case I'll close the issue since more than possible was done from a distance.

Have a nice day.

**Comment by kwcooper** [comment]
Same issue for me... Damn bash licensing issues forcing the MacOS move towards zsh... 

Anyway, I think adding the pyenv script to the .zprofile as per @cseder 's comments did the trick for me. Though I can't rule out pyenv rehash fixed it after the terminal restart to source the updated profile. 

In any case, thanks for the suggestions all.

**Comment by cseder** [comment]
@kwcooper 
I've used Zsh for a couple of years before the transition, so I might have been a bit better prepared at least ;)

> Though I can't rule out pyenv rehash fixed it after the terminal restart to source the updated profile.

The rehash in pyenv just refreshes the bin-stubs in your shims directory for the installed versions of Python and it's run automatically when you install / reinstall a Python version.
It has nothing to do with sourcing the shell startup files. 

Having `eval "$(pyenv init -)"` as your last line in `~/.zshrc` should really be all that's needed **if** you've followed my advice in keeping only two Zsh related  startup files, .zshrc and .zprofile, as .zshrc is called with every shell you invoke interactively and it is sourced during login.

Just make sure you don't use .profile, .zshenv or any other shell startup files to keep it simple.
If you follow the instructions from pyenv, they instruct you to use .zshenv, but **doing so will make macOS trigger the `/usr/libexec/path_helper` every time you start an interactive or login shell, and you're back to square one...**

**Comment by gsscoder** [comment]
I tried again installing using **pyenv installer** instead of `brew` and I'm still in the same stiuation!

Just to let know.

**Comment by cseder** [comment]
Try creating a new user account on the Mac and switch to using that.
This is some sort of profile related error in some shell startup file or something.

**If you do choose to create a new user, make sure to export a list of your installed Homebrew applications / libraries etc** and uninstall Homebrew completely. Then install it again on the new user account as usual and import the list of packages to install via a pipe or something.

This is described on brew.sh.

Homebrew doesn't like a multi-user (or multi-admin to be exact) environment. You can use the installed stuff in `/usr/local/bin` but if you try to install something you'll get a screenfull of errors...
Permissions related, poorly designed IMHO.

I'll bet my socks that this will solve the pyenv problem, though it causes a bit of work to switch users in other areas. 

**But since you did an upgrade from Mojave -> Catalina, you'll be better off with a fresh profile anyway.** I NEVER upgrade OS Major versions. Always backup -> re-partition / format -> install new OS -> Restore from backup. Never have any problems this way.

**Comment by gsscoder** [comment]
Thanks again, @cseder. I'll try it.

I'm sure this issues are related to **macOS** upgrade. Anyway never imagined a macOS upgrade could be more harmful than a Windows one!

**Comment by cseder** [comment]
> Thanks again, @cseder. I'll try it.
> 
> I'm sure this issues are related to **macOS** upgrade. Anyway never imagined a macOS upgrade could be more harmful than a Windows one!

Calling it "harmful" is a bit heavy, but generally, as a rule there is always less fuzz involved when doing a backup first and re-install the new OS version on a freshly formatted partition, no matter what OS we're talking about.
In this case there are probably left-over preferences and configuration files that causes trouble, and giving the OS installer the responsibility (and permissions) to delete whatever didn't make sense would probably be way more harmful.

**Comment by gsscoder** [comment]
@cseder, you're right.
I'm trying to scheduling this activity. I want to perform it with some extra knowledge.

**Comment by gsscoder** [comment]
@cseder, your spartan perseverance won! I followed your suggestion.
- Backed-up old user
- Exported brew/cask list of apps
- Created new user
- Reinstalled apps
This not only solved the problem, but I got also a **system that seems to be faster** (without doubts is **cleaner**). Thank you! :)

I've rebuilt `.zshrc` and `.zprofile` as you suggested. In partciular I had care to handle **PATH** in the way you explained previously.
This my actual `.zshrc`:
```sh
unset path
PATH="\
$HOME/.dotnet/tools:\
/opt/bin:\
/usr/local/bin:\
/usr/local/sbin:\
/usr/bin:\
/bin:\
/usr/sbin:\
/sbin:\
/Library/Apple/usr/bin:\
/Library/Apple/bin:\
/usr/libexec"

eval "$(pyenv init -)"
```
I was unable to delete some files (even as `root`) left by previous `brew` operations (and/or by Catalina upgrade) due to **macOS** integrity system. So I've rebooted in **Recovery Mode**, disabled it and removed files. Than I've enabled it again.
Hope this can help other people too!

**Comment by cseder** [comment]
@gsscoder 
> This not only solved the problem, but I got also a system that seems to be faster (without doubts is cleaner). Thank you! :)

Hate to say I told you so! 😉
The deleting of the old user isn't strictly necessary, so I didn't mention it, but disabling SIP is required if you didn't create the account on the Catalina macOS.<br>
If you create new users now, you're able to do a `sudo rm -rf /Users/user_to_delete` when logged in with another user account without disabling SIP though... Go figure...

**Comment by gsscoder** [comment]
This is very good to know!
I'll archive it on my **evernote** and tweet this issue immediately.

Have a nice day

**Comment by etalkishere** [comment]
I had the same problem.  I had ohmyzshell installed on my Catalina.  It needs to be PYENV_ROOT/shims, not PYENV_ROOT/bin, since bin doesn't exist under .pyenv folder.

echo 'export PATH="$PYENV_ROOT/shims:$PATH"' >> ~/.zshrc

**Comment by htd-tstepien** [comment]
> I had the same problem. I had ohmyzshell installed on my Catalina. It needs to be PYENV_ROOT/shims, not PYENV_ROOT/bin, since bin doesn't exist under .pyenv folder.
> 
> echo 'export PATH="$PYENV_ROOT/shims:$PATH"' >> ~/.zshrc

Clean install on macOS - this helped!

**Comment by cseder** [comment]
> > I had the same problem. I had ohmyzshell installed on my Catalina. It needs to be PYENV_ROOT/shims, not PYENV_ROOT/bin, since bin doesn't exist under .pyenv folder.
> > echo 'export PATH="$PYENV_ROOT/shims:$PATH"' >> ~/.zshrc
> 
> Clean install on macOS with brew (OMZSH too) - this helped!
> 
> This (without that loop) works cool.
> 
> ```
> ### PyEnv
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/shims:$PATH"
> ```



> I had the same problem. I had ohmyzshell installed on my Catalina. It needs to be PYENV_ROOT/shims, not PYENV_ROOT/bin, since bin doesn't exist under .pyenv folder.
> 
> echo 'export PATH="$PYENV_ROOT/shims:$PATH"' >> ~/.zshrc

I think most of the trouble I see people reference here is already answered through my earlier answer.

Also, I think an easy way to avoid hassle when upgrading OS major versions i to create a new user, let the OS initialize everything properly, then migrate parts of your original `/Users/~` from the previous install, using a backup. 

Usually this also cleans up tons of old cruft that just wastes space.

**Comment by native-api** [comment]
Please see updated and hopefully clearer MacOS instructions in the README.

**Comment by dwiyatci** [comment]
@native-api Thank you for https://github.com/pyenv/pyenv/commit/159327ff2572d763e9553987f26b4abf0f7a19f8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5.

```shell
echo 'eval "$(pyenv init --path)"' >> ~/.zprofile
``` 
crucially adds `$HOME/.pyenv/shims` to my `$PATH`. 👍

**Comment by vallamost** [comment]
If you are using something like Oh My Zsh on Mac OSX, you'll want to do something like this:

```
echo 'eval "$(pyenv init --path)"' >> ~/.zshrc
```
