### ISSUE TITLE
Provide shims for micro/patch releases (python3.7.4)

### ISSUE THREAD

**Issue by altendky** [pyenv/pyenv#1480]
I help out in #python and at various points I want to help with a specific micro/patch Python version.  Installation is easy but to actually call (without setting up some 'local' etc setting) I have to specify the path down into `versions/` to get the version I want.  It would be handy if shims were provided and `python3.7.4` just worked.

I think this is similar to #633.  It is admittedly a convenience issue and I don't know how much hassle it is to add such support beyond the standard Linux Python executable naming conventions.

**Comment by joshfriend** [comment]
So just to make sure I get what your use case is, you would like to "activate" multiple patch versions of python at the same time (e.g. `3.7.1`. `3.7.2` and `3.7.4`), then just be able to type the exact version that the person you're trying to help is using to start a repl or run a script?

The shim creation process is currently somewhat simple in that it takes the `bin/` directory of the installed python and symlinks everything there into the shims directory. If the python itself doesn't provide a `python3.7.4` executable, pyenv wont have one either. This is why anaconda is sometimes troublesome, since they include a bunch of duplicates of common shell utils in their `bin/`.

I'm not sure why PEP-394 didn't include patch versions, perhaps they didn't think it was important since they follow semver pretty strictly.

**Comment by altendky** [comment]
They 'follow semver pretty strictly' but 3.7 micro releases broke me reasonably hard multiple times...  *shrug*

Is 'activation' of any form needed for this?  I may not be familiar with normal terminology used here. 
 I suppose I would expect to need to reference the version in a `pyenv global` call if that is required to get an entry in the shims directory.  `/home/altendky/.pyenv/shims` is in my path and I would like to be able to run `python3.7.4` or `python3.7.2` just as I can run `python3.7` today.

I agree that this is a problem down below pyenv and it's not lost on me that I am reporting it at the top of the stack.  I mean, Windows can't even have multiple micro versions installed at once...

**Comment by laike9m** [comment]
I'd love to see this happen. Different patch versions do carry some differences, and I want to have multiple patch versions in my `.python-version` (e.g. 3.7.1. 3.7.2).

I don't know why PEP-394 didn't include patch versions either, but maybe, as a version manager, pyenv can work around it?

**Comment by krautcat** [comment]
I don't exactly know but I think my issue #1606 could be related.

**Comment by native-api** [comment]
`pythonX.Y.Z` can't "just work" because there can be multiple of installations of each version, just like with `pythonX.Y`.

The way to run a command against a specific installation statelessly is `PYENV_VERSION=<version> pyenv exec <command>`, or just `PYENV_VERSION=<version> <command>` if the executable is a shim. [I've just siggested a more convenient alternative.](https://github.com/pyenv/pyenv/issues/1932)

**Comment by altendky** [comment]
In so much as `python3.9` can work I don't see why `python3.9.2` couldn't.  So, I don't understand the claim that was made.  Also, no feedback was requested.  The alternative presumably wouldn't be considered a valid alternative to `python3.9` so I fail to see how it is a sensible alternative to `python3.9.1`.

**Comment by native-api** [comment]
> In so much as `python3.9` can work I don't see why `python3.9.2` couldn't.

You didn't request that it works like `pythonX.Y`. You requested that it works right after installation, even without an appropriate version being selected. I explained above why it can't work this way.

And once you do have to select a version, the feature becomes unnecessary complication: once you've selected a version, running _any_ `python*` will invoke it.

**Comment by altendky** [comment]
Welp, I didn't mean to.

> I would expect to need to reference the version in a `pyenv global` call

I don't really follow how the third segment of the version is so utterly silly to want while the second segment is regular normal functionality for pyenv.

**Comment by native-api** [comment]
> 
> 
> Welp, I didn't mean to.
> 
> > I would expect to need to reference the version in a `pyenv global` call
> 
> I don't really follow how the third segment of the version is so utterly silly to want while the second segment is regular normal functionality for pyenv.

That's because `python`, `pythonX` and `pythonX.Y` (but not `pythonX.Y.Z`) is an existing established standard, https://www.python.org/dev/peps/pep-0394/, that Pyenv follows due to it being the standard way of providing Python in UNIX-like systems.

The reason why it doesn't provide micro release executables is because they are source- and binary-compatible, unlike minor ones, so there's no reason to have more than one available at the same time as part of an OS installation, as is there no need to write general-purpose software (=software that would expect to be installed into such an environment) that strictly expects a specific micro release.

As a consequence, users don't expect `pytonX.Y.Z` to be present on a system -- thus don't write software that expects or needs it, and Python's makefiles and OS packages don't create them.
So there's no use case for this feature that would warrant the added complexity and maintenance cost -- at least, none has been presented so far.

**Comment by altendky** [comment]
Sorry, I was trying to not rehash every last thing I know.  Yup, I am aware that standard Python doesn't do this.  Standard Python building and distribution doesn't do a lot of what pyenv does...  that's why we like pyenv.  So, a feature being a thing that standard Python doesn't do seems like it is actually a plus for it being a thing for pyenv to do.  If standard python already did it then pyenv wouldn't need to.

I'm sorry, I'm a bit frustrated by this.  Not that nobody has donated their time to develop this feature for me, certainly nobody owes me that, but that the commentary isn't really applicable to the request.

**Comment by native-api** [comment]
@pyenv/pyenv-core-maintainers Any opinion on this?

No use cases when having `pythonX.Y.Z` is important have been provided -- and I really don't think that someone's sense of harmony/completion solely is sufficient grounds to add a feature.

I guess `pyenv global 3.9.5 3.9.4` is a case where the `pythonX.Y.Z` shim could come in handy -- but again, what's the use case for that?

**Comment by native-api** [comment]
> and I really don't think that someone's sense of harmony/completion alone is sufficient grounds to add a feature.

> I guess `pyenv global 3.9.5 3.9.4` is a case where the `pythonX.Y.Z` shim could come in handy

While we're at it, why don't we add `cpython*` shims as well? And for the other flavors, too (where they don't exist already)! Because someone might write `pyenv global pypy3.7-7.3.5 3.7.10`!
All for the sake of completeness, of course! :wink:

**Comment by altendky** [comment]
I'm confused, are you mocking me now?

I admittedly don't help out in `#python` a whole lot at this point so the desire to access specific patch versions doesn't come up as much.  That said, the OP lays out the use case.  At this point my attempt to understand ends up at "`pythonX.Y` is useful because it does not pick a specific version and let's pyenv pick one".  Which does differentiate it from `pythonX.Y.Z`.  I thought somewhere here I was told that the point of pyenv was to setup and run an exact python environment, but it seems that may have been in another issue.

**Comment by native-api** [comment]
For the original use case, [you do `pyenv shell X.Y.Z; <your command>` or `PYENV_VERSION=X.Y.Z <your command> (the proposed `pyenv do` would do the latter in fewer keystrokes)](https://github.com/pyenv/pyenv/issues/1480#issuecomment-842750334). There's no need to add anything to Pyenv for that.

The last post was a joke, but it does illustrate where adding stuff without use cases may lead to.

**Comment by altendky** [comment]
You aren't the only software developer.  Rude jokes are not needed.

**Comment by anton-petrov** [comment]
I apologize for some of the team member's intemperance, but nevertheless, I agree that adding new functionality depends on its use cases. Providing shims for micro/patch releases not planned in the near future...

**Comment by eevmanu** [comment]
In case anyone is still looking for a quick **workaround** and "force" this desirable behaviour at your terminal, I was able to do this with `alias` on `.bashrc` (or your custom one):

`.bashrc` 👇
```bash
# add these lines after pyenv setup
PY_VERSIONS=$(pyenv versions --bare)
PY_VERSIONS_LIST=($PY_VERSIONS)
for v in "${PY_VERSIONS_LIST[@]}"; do
  alias python${v}="PYENV_VERSION=${v} python"
done
```

in my case I have these versions installed:

```bash
$ pyenv versions --bare
3.10.2
3.6.11
3.6.12
3.7.10
3.7.12
3.8.12
3.8.9
3.9.10
3.9.7
```

and whenever I want a specific version, I just ran:

```bash
$ python3.6.9 -V
Python 3.6.9

$ python3.6.9 
Python 3.6.9 (default, Dec 28 2020, 19:00:48) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.version
'3.6.9 (default, Dec 28 2020, 19:00:48) \n[GCC 9.3.0]'
```

Thanks @native-api for the suggestion made here 👉  https://github.com/pyenv/pyenv/issues/1480#issuecomment-842750334
