### ISSUE TITLE
libssl1.0-dev  doesn't exist on ubutu 19.10

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1481]
Hi, 

I try to compile python 3.4.9 with pyenv but failed with  a self compiled openswsl git version OpenSSL_1_0_2t :

$ LDFLAGS="-L$HOME/local-openssl/lib" CFLAGS="-I$HOME/local-openssl/include/openssl" SSH=$HOME/local-openssl/bin/openssl pyenv install -v 3.4.9

But, I meet the following errors:

```

Ignoring ensurepip failure: pip 9.0.1 requires SSL/TLS
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 19.10 using python-build 1.2.15-5-gce3476a5)

Inspect or clean up the working tree at /tmp/python-build.20191213115351.12116
Results logged to /tmp/python-build.20191213115351.12116.log
```

Then I try to use the supposed method on https://github.com/pyenv/pyenv/wiki/Common-build-problems:

```
sudo apt-get remove libssl-dev
sudo apt-get update
sudo apt-get install libssl1.0-dev
```

But, I meet the following error:

```
$ sudo apt-get install libssl1.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0-dev' has no installation candidate
```

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

How to solve this issue? 

Regards

**Comment by native-api** [comment]
>     Package libssl1.0-dev is not available, but is referred to by another package.

This means that your Apt metadata is inconsistent.
* Either the distro has dropped the old version (very possible since you're using a non-LTS release) and you haven't upgraded local packages, and/or
* You're using some 3rd-party repo that's out of sync with the official ones

See https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib for your options (as long as Pyenv is concerned).
