### ISSUE TITLE
[Linux] Missing deps, installing Python >3.6 with pyenv doesn't result in fully functional python/pip

### ISSUE THREAD

**Issue by spoelstraethan** [pyenv/pyenv#1546]
After Python 3.6 the "in-tree copy of libffi was removed" [python-bugs](https://bugs.python.org/msg329384) and if you haven't otherwise installed libffi-dev/libffi-develop when you try to `pip install` any Python packages that requires utilizing `_ctypes` it will fail hard. It looks like this should be a simple check similar to the zlib/ssl/readline [current code](https://github.com/pyenv/pyenv/blob/4e0ba2f47d97acd1284439cff57af059ce376b9d/plugins/python-build/bin/python-build#L1865). The package name required might depend on the distribution, but [this hint](https://github.com/pypa/pipenv/blob/9208ec912f551cbb4eae565120c618f04300ddc4/Dockerfile#L10) from the Pipenv Dockerfile that appears to be based on Debian gave me a hint to get it working in my case.

My simple test case was on Debian Stretch (9) on a Chromebook via Linux apps (really minimal base install of Debian).

```
curl -L https://pyenv.run | bash
pyenv install 3.8.1
eval $(pyenv init)
pip install pipenv
```

This fails on `distlib` due to `_ctypes` not being available.

**Comment by clbarnes** [comment]
Missing build dependencies are [documented here](https://github.com/pyenv/pyenv/wiki/Common-build-problems#prerequisites) - are the issues you're facing outside of those dependencies?

**Comment by spoelstraethan** [comment]
As noted in my example I installed using the pyenv-installer which I suspect pulled in any necessary dependencies necessary for pyenv while it installed it. 

This issue isn't about that though, from what I could find in the source code there are certain checks that are run post-install on Python 2.x and 3.x installations, and the link I put it to the current place in the code where this happens shows that it is already being done for other packages important to the installation of packages via pip, this seems to be one package that is missing in Python 3.7 and 3.8 (and newer) and so there should be a post-install check and warning if it isn't found as it is required for a LOT of "from source" pip installs.

**Comment by clbarnes** [comment]
> pulled in any necessary dependencies necessary for pyenv while it installed it

Yes, I believe it does - however, the dependencies for pyenv are not the same as the dependencies for building any single version of python. Fetching those are not feasible for pyenv, as pyenv supports the installation of hundreds of different python versions and distributions, with different (if overlapping) requirements, and the best way to install those dependencies will vary by the user's OS.

You're right, though, that something as fundamental as ctypes could be checked for in the same way that the libraries you linked are checked for - then at least a warning could be raised so the user would know where to go looking.

**Comment by onilton** [comment]
> Fetching those are not feasible for pyenv, as pyenv supports the installation of hundreds of different python versions and distributions, with different (if overlapping) requirements, and the best way to install those dependencies will vary by the user's OS.

@clbarnes where I can find more info on this decision? Is there an issue or documentation about that?

I always thinking that even though pyenv can not download this requirements (because of the complexity), it could be more active in checking if the requirements were present (and warn or stop install if those issues were found, it could have --force options to ignore warning).

It took me some time to realize I needed to install the requirements from https://github.com/pyenv/pyenv/wiki#suggested-build-environment . I had to install python and get some errors when running, after some search, I finally got it.

In my work, all of my coleagues had this exact same problem, (I helped some of them with this). Some of them googled the problem at first and only installed a part of the build requirements, so they still got issues later.

I wonder if at least before/after python install or even before/after install of pyenv-installer it could run some checks, detect missing build requirements and point to https://github.com/pyenv/pyenv/wiki#suggested-build-environment  it would be a nice improvement if it is feasible.

**Comment by spoelstraethan** [comment]
I think `pyenv doctor` might be a good place to put this, or it could be a part of `python-build` since that already has to know critical things about the Python version it is installing.

On some systems that have source packages available like apt on Debian/Ubuntu you can use `build-deps` to get the necessary bits, but it only works if it has the right sources.list for `deb-src`.

**Comment by clbarnes** [comment]
I think for it to go in `pyenv doctor`, we'd need to make assumptions about what the user wants out of pyenv more generally (e.g. "I want to install recent-ish versions CPython from the official source distributions"). `python-build`, as part of the build script itself, seems like the place to throw a warning (you could provide a function in a shared script for checking whether particular libraries are available; the build script would just have to list which ones it needs). Adds a little overhead to each new script written, and may require changing quite a lot of historical build scripts.

**Comment by onilton** [comment]
:(

**Comment by native-api** [comment]
> Is there an issue or documentation about that?

https://github.com/pyenv/pyenv/wiki#suggested-build-environment
