### ISSUE TITLE
shims directory is empty on Kubuntu 20.04

### ISSUE THREAD

**Issue by JackPenry** [pyenv/pyenv#1608]
### Description
- [ ] Platform information: Kubuntu 20.04
- [ ] OS architecture: amd64
- [ ] pyenv version: 1.2.18-12-g098227f2
- [ ] Python version: 3.8.2

The output of `pyenv versions` is as follows:

> Warning: no Python detected on the system

.bashrc and PATH are as they should be.

**Comment by joshfriend** [comment]
Please make sure you have followed all of the setup instructions, particularly step 3 of [this section](https://github.com/pyenv/pyenv#basic-github-checkout).

**Comment by JackPenry** [comment]
I'm sorry, if you read my report, I did do that. As I said my .bashrc file is as it should be. I've successfully used pyenv on openSUSE tumbleweed and Ubuntu Server 18.04. Did you try to recreate my issue before closing it?

**Comment by JackPenry** [comment]
![pyenv](https://user-images.githubusercontent.com/46057747/81501157-c116a500-92a4-11ea-9ae4-d8ed0f74caf8.png)

And I tried putting it in .profile and .bash_profile for shits and giggles but Kubuntu doesn't use them in a non-login shell such as Konsole soooooooo. No surprise that didn't work.

**Comment by yeduzhouzi** [comment]
> 
> 
> ![pyenv](https://user-images.githubusercontent.com/46057747/81501157-c116a500-92a4-11ea-9ae4-d8ed0f74caf8.png)
> 
> And I tried putting it in .profile and .bash_profile for shits and giggles but Kubuntu doesn't use them in a non-login shell such as Konsole soooooooo. No surprise that didn't work.

I had the same issue with you, the problem is that pyenv could not be initialized even if you run `eval "$(pyenv init -)"` manually. Did you only have the system version of python when you occur the problem? If so, this workaround might work for you:

1. install any other version of Python via pyenv
2. then manually run `eval "$(pyenv init -)"`
3. now type in `which python` and you should see the problem gone

**Comment by yeduzhouzi** [comment]
> 
> 
> Please make sure you have followed all of the setup instructions, particularly step 3 of [this section](https://github.com/pyenv/pyenv#basic-github-checkout).

I can confirm that there is this issue. On freshly installed Ubuntu 20.04 with only Python 3.8 coming with the system, Pyenv could not be successfully initialized and the `shims` folder kept empty forever, even if everything was correctly configured. But after installing another version of Python with Pyenv and then running `eval "$(pyenv init -)"` once, the problem was gone and the `shims` folder became what it should be.

**Comment by gh-andre** [comment]
I ran into the same problem on Ununtu 20.04. What confused me is that `pyenv install 3.10` reports Python build failures in a way that suggests it did something and then reported a few warnings, while it actually didn't install anything.

That is, it does say BUILD FAILED, but then reports that scripts `pip3` and `pip3.10` are installed under the home directory and follows up with this message.

> Successfully installed pip-22.3.1 setuptools-65.5.0

Running the install command with `--verbose` makes it easier to see build errors, like this:
```
pyenv install --verbose 3.10
```
Once build dependencies from this page are installed, everything worked out for me.

https://github.com/pyenv/pyenv/wiki#suggested-build-environment
