### ISSUE TITLE
Transferring ownership of pyenv repos to pyenv org

### ISSUE THREAD

**Issue by jawshooah** [pyenv/pyenv#1640]
I'd like to transfer ownership of my [pyenv-default-packages](https://github.com/jawshooah/pyenv-default-packages) and/or [homebrew-pyenv](https://github.com/jawshooah/homebrew-pyenv) repos to the pyenv org. I haven't had time to actively maintain or contribute to OSS for a few years now, so I figure it makes sense to hand these over to the pyenv team. Would you be interested?

**Comment by jidicula** [comment]
It would be great if pyenv-default-packages could be actively maintained again. I spent a lot of time over the last few days trying to find a solution that allows me to install some default packages for each Python version I install. My rationale for doing this is for installing development tooling that I use in nearly every project, like pyflakes, Rope, Jedi, etc. I initially thought it should be something handled by a dependency manager like Poetry, but after more thought, I think this is out of scope for a project-level dependency manager. If Poetry handles these as dev dependencies, the project gets commit noise for any of those tooling dependency updates that don't directly affect the project's functionality. It makes more sense to me for these tools to be installed once for each Python version (rather than for each project), and hooking into pyenv’s installation process is ideal for this. It doesn't seem like there's any tool that does this other than pyenv-default-packages, so it would be great if the pyenv organization could adopt this project.

Thanks for your work in getting this started @jawshooah!

**Comment by native-api** [comment]
No-one has replied in about a year, so I guess there are no volunteers from the core team at the moment.

The plugin's logic is quite simple, so it shouldn't require a lot of ongoing effort.
But I just don't look forward to receiveing user feedback about a piece of software that I don't care about.

@jidicula If you're using this product anyway, why don't you take up the reigns? You need to maintain it anyway since you're using it and thus will need to fix it if it breaks.

**Comment by jidicula** [comment]
I've decided against using this product now that I just rely on a Python LSP for dev tooling, so I'm not particularly invested in pyenv-default-packages anymore.
