### ISSUE TITLE
Shims directory appears multiple times in PATH

### ISSUE THREAD

**Issue by ggicci** [pyenv/pyenv#1649]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 18.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: pyenv 1.2.19-4-g366c9801
- [x] Python version: 3.8.0
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
 
Directory `${PYENV_ROOT}/shims` appears multiple times in `PATH`. We can avoid this by checking the existence of the shims path in `PATH` before appending.

**Comment by native-api** [comment]
WFM. Shims is only on the PATH once if I install Pyenv using the official instructions. Perhaps you're doing some custom stuff.

**Comment by Integralist** [comment]
I have the same problem, which is caused by reloading my `.bashrc` file (which I do multiple times during the day, whether I'm making changes or I'm loading up a new tmux instance -- which subsequently loads .bashrc).

Because I have the lines...

- `eval(pyenv init -)`
- `eval(pyenv virtualenv-init -)`

...the code internally executed by those is mutating the $PATH by just prefixing to the path without checking it first.

So I've solved this by _inlining_ all the code from those two eval's and then replacing the path modification lines with...

```bash
pathmunge /Users/integralist/.pyenv/shims
pathmunge /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims
```

The `pathmunge` reference is implemented like so:

```bash
pathmunge() {
  # pathmunge /foo/
  # pathmunge /foo/ after
  #
  if ! echo "$PATH" | grep -Eq "(^|:)$1($|:)" ; then
    if [ "$2" = "after" ] ; then
      export PATH="$PATH:$1"
    else
      export PATH="$1:$PATH"
    fi
  fi
}
```

**Comment by native-api** [comment]
> I have the same problem, which is caused by reloading my `.bashrc` file

I solved this by placing the lines into `~/.bash_profile`, then setting in Gnome-Terminal settings: `Edit -> Preferences -> Command -> check "Run command as a login shell".

This way, whenever I reload the shell with `exec $SHELL`, `~/.bashrc` gets reloaded but `~/.bash_profile` doesn't.

**Comment by native-api** [comment]
I asked about this at https://unix.stackexchange.com/questions/609522/should-bashrc-commands-support-shell-reloading and the only reaction I got so far is eyes rolling.

Whatever you do with the shell is out of Pyenv's control and none of its business. Second-guessing the user is risky business and contradicts UNIX philosophy due to that.

And I honestly can't see what could possibly break if an entry is in `PATH` multiple times. Effectively, only the first entry would have an effect.

**Comment by native-api** [comment]
In case I made myself unclear, @Integralist's solution is just fine, but I don't see that it should be the default logic so far. If you want to reload `.bashrc`, you know better than Pyenv's maintainers whether you want to prepend a `PATH` entry again or not in your particular scenario.

**Comment by ggicci** [comment]
@Integralist Prepend the shims path to `PATH` can ensure that the binaries under which having the first priority in your environment. While your implementation with the help of `pathmunge` won't guarantee that. A better implementation should remove the duplicate ones and finally prepend the shims path, IMO.

**Comment by Integralist** [comment]
@ggicci that's a good point in that I could just have the following added to the bottom of my .bashrc which does deduping...

```bash
export PATH=$(echo -n $PATH | awk -v RS=: '!($0 in a) {a[$0]; printf("%s%s", length(a) > 1 ? ":" : "", $0)}')
```

^^ copied from https://www.linuxjournal.com/content/removing-duplicate-path-entries which explains it in detail.

And to quote from that article...

> there's no compelling reason to to do this. The shell will, in essence, ignore duplicates PATH entries; only the first occurrence of any one path is important.

Followed with the secondary motivator being...

> those who are annoyed by such things as having duplicate PATH entries.

...which would be me 🙂

**Comment by native-api** [comment]
Got answers to the question. They suggest the following:

* `PATH` manipulations belong in `~/.bash_profile` rather than `~/.bashrc`. If you do that in `~/.bashrc`, you're doing it wrong. GUI login managers read `~/.profile` but not `~/.bash_profile` so the former is where `PATH` manipulations should go.
  * By this advice, Pyenv is currently in the wrong doing a `PATH` manupulation from `pyenv init` in `~/.bashrc`
* If you must use `~/.bashrc`, use `pathmunge` which turns out to be a standard, well-tested function rather than someone's personal invention (the latter would be likely to have undesirable side effects and/or bugs in corner cases so would be risky to recommend).
  * There's however a dilemma of whether to move the `PATH` entry to the front or leave it where it is.

So I see a following way to go:

* Split `pyenv init` logic into a part that does `PATH` manipulation and a part that does everything else (e.g. `--path` and `--rc`). Recommend to use the first one in `~/.profile` and the 2nd one in `~/.bashrc`.

Considered other options:
* Don't `export` `PATH` with `.shims` (this is what Virtualenv does). This is rife with side effects: launched processes will not get the entry, potentially leading to surprising and erroneous behavior.
* Make an optional logic (e.g. `--munge`) which will invoke a (private copy of) `pathmunge`. This is usable if we resolve the dilemma. My best idea is to not move the entry to the front because the idea is to avoid changing `PATH` upon shell restart -- it's presumed to have already been set up appropriately the first time the shell was started.

**Comment by pfheatwole** [comment]
For my setup the simplest solution was to add a line that simply removes the leading `$PYENV_ROOT/shims` entry (if present)  from the existing `PATH` before running `pyenv init`. My `.bash_profile` is then:

```
export PYENV_ROOT="$HOME/.local/pyenv"
PATH=${PATH#"$PYENV_ROOT/shims:"}
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PATH
```

**Comment by adigitoleo** [comment]
I just realised that pyenv was breaking my venvs inside vim terminals because it added the shims directory in front of the path again when launching `:terminal`. To prevent adding the shims directory again when launching subshells, I present an alternate approach to some of the above suggestions. In my shell config I have:
```
if command -v pyenv 1>/dev/null 2>&1; then
    if [[ -z "$PYENV_LOADED" || "$PYENV_LOADED" == 0 ]]; then
        eval "$(pyenv init -)"
        export PYENV_LOADED=1
    fi
fi
```

Maybe the README example could be updated to include some kind of subshell guard variable like this.

**Comment by native-api** [comment]
@anton-petrov have any of the proposed solutions been implemented or something? I don't see any relevant commits.

**Comment by anton-petrov** [comment]
@native-api **_pyenv_ shouldn't keep track of changes that happens in PATH. It's not peynv responsibility!**

To all users: please, do your path manipulations in ~/.bash_profile or ~/.profile, not in .bashrc or .zshrc. This is my modest recommendation ;)

In summary: I don't see any relevant commits too. And, personally, I don't face this problem, like many others. 
If there are any suggestions/improvement that can be added to the code base, let's discuss them and merge if possible...

**Comment by native-api** [comment]
> please, do your path manipulations in ~/.bash_profile or ~/.profile, not in .bashrc or .zshrc.

That's where the problem with Pyenv lies: `pyenv init` does `PATH` manipulation (prepends shims directory), and this can't be separated from other things it does (like adding a shell function) -- so it can't be moved to `~/.profile`.

**Comment by adigitoleo** [comment]
I think at least the relevant section(s) of the readme could be updated to warn people about this issue and point to this discussion or suggest on of the alternative approaches.

**Comment by anton-petrov** [comment]
Hm... you probably misunderstood me, or I formulated my thought incorrectly.
Yes, 
> pyenv works by inserting a directory of shims at the front of your PATH
but once at start.

My point is that during the process of its work, pyenv doesn't modify PATH variable. Thats all.
Again, tracking the correctness of the path is not declared in pyenv.
> I think at least the relevant section(s) of the readme could be updated 

I agree, we need to update documentation.

**Comment by native-api** [comment]
> pyenv works by inserting a directory of shims at the front of your PATH
> but once at start.

The problem is, this doesn't actually happen "once at start" as advertized -- because, as was shown earlier, `.rc` files, by design, can be sourced multiple times.

Anyway, to proceed, someone needs to make a PR that would guarantee that `PATH` addition only happens once, this way or another, provided that shell startup files are used as designed.

**Comment by justinpowers** [comment]
@anton-petrov, can we reopen this issue?

As @native-api mentioned, Pyenv quite clearly prepends to `PATH` via `export PATH="$PYENV_ROOT/shims:${PATH}"`. This is not during its primary operation, but only when initialized according to official instructions with `eval "$(pyenv init -)"`. As such, a diligent user would be inclined to place that evaluation in their `.profile`, but of course this would fail and they must place it in their `.bashrc` instead.

Forcing a user to invoke it it in `.bashrc` (and manipulate `PATH` therein) is against standards and may, at minimum, result in duplicate entries in the user's `PATH`. Most setups source `.bashrc` for all interactive shells, both login and non-login. This means that a user who opens a terminal to start their desktop and then opens a terminal emulator, will have at least two `.pyenv/shim` entries in their `PATH`. We should avoid that.

As far as I can tell, we can either: 
1. Alter the init script to check for a preexisting `shims` entry in the `PATH` using something similar to Rust's `.cargo/env` script:
    ```bash
    case ":${PATH}:" in
    *:"$PYENV_ROOT/shims":*)
       ;;
    *)
        export PATH="$PYENV_ROOT/shims:$PATH"
        ;;
    esac
    ```
    _This would still result in the invocation being placed in the `.bashrc`_, so it is definitely not ideal. But it works.

2. Instruct the user to manually add the `.pyenv/shims` directory to their `PATH` as is currently done for the `.pyenv/bin` directory. This allows the user to follow standards and manipulate their `PATH` in their `.profile` file. Then `pyenv init` can forgo any `PATH` manipulation. I'm not familiar enough with Pyenv to know this would cause any problems, but I've had no issues with the small experiments I've done.

3. Assuming the previous option is not a problem, it can be scripted. Either a separate script or utilizing an option in `pyenv init` (as suggested by @native-api).

**Comment by kamkudla** [comment]
This remains to be an issue, and further compounded when using tmux because tmux has its own nuances at startup. Add to that the nuances of macOS's quirky `path_helper` command which always autoloads from `/etc/profile/` and `/etc/zprofile/` and the problem quickly spirals. Took me an inordinate amount of time to figure out what was happening, and yes, the blind prepending of PATH is the problem here. I'm using zsh and tmux. At the bottom of my `.zshrc` I have 

```
if [[ -z $TMUX ]]; then
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
    fi
fi
```

My `.tmux.conf` 

```
set -g default-command /usr/local/bin/zsh
```

I do my PATH manipulations in `.zprofile`. 

The problem I have now is that I have to check for `$TMUX` in my `.zshrc` before calling `pyenv init`. When I launch `$TMUX`, `which pyenv` returns `/usr/local/bin/pyenv` instead of the alias that `pyenv init` sets. Not sure if this is a problem, but I had to completely ditch `pyenv-virtualenv` because it seemed to work at first, but failed when trying to do anything within tmux and so I'm worried I'll have some problems down the line.

**Comment by kamkudla** [comment]
Slightly refactoring the solution from @pfheatwole earlier in this thread, this is the simplest solution atm. 

`.zshrc` : 

```
if command -v pyenv 1>/dev/null 2>&1; then
    export PYENV_ROOT="$HOME/.pyenv"
    PATH=${PATH#"$PYENV_ROOT/shims:"}
    eval "$(pyenv init -)"
    export PATH
fi
```
