### ISSUE TITLE
New plugin for pyenv to update packages in particular or all environments. Please add it to Wiki.

### ISSUE THREAD

**Issue by zyrikby** [pyenv/pyenv#1719]
Hi, I have developed a plugin for pyenv to update packages in particular or all pyenv environments (excluding system). Please, add the link to it to the wiki page: https://github.com/zyrikby/pyenv-pip-upgrade

**Comment by native-api** [comment]
Is it any different from https://github.com/massongit/pyenv-pip-update ?

**Comment by zyrikby** [comment]
Yes, it is. I've described the differences, and why I have decided to develop a new plugin in this article: [https://zhauniarovich.com/post/2020/2020-10-why-pyenv-pip-upgrade/](https://zhauniarovich.com/post/2020/2020-10-why-pyenv-pip-upgrade/)

**Comment by native-api** [comment]
This sounds

> I've described the differences, and why I have decided to develop a new plugin in this article: https://zhauniarovich.com/post/2020/2020-10-why-pyenv-pip-upgrade/

This sounds like something that should be fixed in `pyenv-pip-update` rather than do a schism. The userbase isn't large as it is, it helps no-one to split it even further.
Anyway, this gives me the knowledge that they should be mentioned together and it'll be you who'll be dealing with the fallout.

Done.
