### ISSUE TITLE
prompt changing not working for fish 

### ISSUE THREAD

**Issue by jvrn3** [pyenv/pyenv#1723]
How can I make visible the virtualenv I am currently using on Fish Shell? 

When I run `pyenv activate venv`, the virtualenv activates but it doesn't show anything visual to me.

**Comment by bromps** [comment]
I think this issue is more suited for [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv).

I am able to reproduce the issue.  However, when I run the same commands in `zsh`, I see "pyenv-virtualenv: prompt changing will be removed from a future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior."  Setting that environment variable completely disables the messages between prompt switches, and gets rid of the "prompt changing not working" message you are seeing.

**Comment by jvrn3** [comment]
Thanks, you are right. The full message is `pyenv-virtualenv: prompt changing not working for fish.`. I'll open an issue on pyenv-virtualenv.
Actually, what I want is not only disable the message, but to show what virtualenv I'm currently on. Now I have to manually run
 ```
source ~/.pyenv/versions/myenv/bin/activate.fish
```
for it to display at my terminal. Sorry if I wasn't very clear.

**Comment by Sipty** [comment]
Have you opened a ticket in pyenv-virtualenv? This is the ticket that google shows, so would be nice to get a reference /mention to it, once made :)

**Comment by jvrn3** [comment]
https://github.com/pyenv/pyenv-virtualenv/issues/284

**Comment by xiebruce** [comment]
> Thanks, you are right. The full message is `pyenv-virtualenv: prompt changing not working for fish.`. I'll open an issue on pyenv-virtualenv. Actually, what I want is not only disable the message, but to show what virtualenv I'm currently on. Now I have to manually run
> 
> ```
> source ~/.pyenv/versions/myenv/bin/activate.fish
> ```
> 
> for it to display at my terminal. Sorry if I wasn't very clear.

This will cause another problem: after I use `pyenv deactivate` to deactivate the virtual environment, the prompt still there, how to make it disappear?
