### ISSUE TITLE
Pyenv does not append to PATH the python bin folder 

### ISSUE THREAD

**Issue by Ofeknielsen** [pyenv/pyenv#1751]
Hi
I'm using pyenv 1.2.21 on MAC 10.15.7

I noticed after installation of specific python package, its command is not revealed in the terminal but can exists in the python bin folder (/Users/ofekisrael/.pyenv/versions/3.7.8/bin)

the pyenv init - command should append it to the PATH and when the python version is changed, to change it too. 

thanks

**Comment by native-api** [comment]
Pyenv is supposed to invoke executable scripts via shims in `.pyenv/shims` rather than by adding `.pyenv/versions/xxx/bin` to `PATH`. Use `pyenv rehash` to create shims for all the scripts that are present in the selected Python installation.

Normally, Pyenv also runs `rehash` automatically after you install a package, but you need to have installed it via the `pip` shim.
