### ISSUE TITLE
Can't install python 3.4.0 on MacOS

### ISSUE THREAD

**Issue by kitanin90** [pyenv/pyenv#1837]
<img width="1738" alt="image" src="https://user-images.githubusercontent.com/32891674/109624535-23a49e80-7b60-11eb-8c68-9fc2b72659dd.png">

**Comment by yedpodtrzitko** [comment]
New Issue Template looks like this (see below), I dont see any of these filled here. Also can you maybe post text as a text instead of screenshot?

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version:
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
