### ISSUE TITLE
tag format change after v1.2.23 ->1.2.25 and duplicate tags affects automation and cause trouble

### ISSUE THREAD

**Issue by jsmithwar** [pyenv/pyenv#1867]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X ] Platform information (e.g. Ubuntu Linux 16.04): All
- [X ] OS architecture (e.g. amd64):All
- [X] pyenv version: After v1.2.23
- [X ] Python version: Not related
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  
  Problem
  tag format changed from v1.x.x to 1.x.x
  Was this intentional?
  Build issue not code
  Might be break all the consumers with automated tools or preformatted gets of pyenv using http or other
  
  Expect
  No change to pattern or use both tags for a while

**Comment by joshfriend** [comment]
I added 2 new tags with the `v` prefix and kept the other tags so nothing else continues to get broken :)

**Comment by jsmithwar** [comment]
Thanks very much

**Comment by Mogost** [comment]
@joshfriend This issue is still relevant for [1.2.27](https://github.com/pyenv/pyenv/releases/tag/1.2.27)

It seems to me necessary to agree on the format in which future versions will be released.

**Comment by native-api** [comment]
How exactly is "automation" affected? Can't you teach it to understand both flavors?

**Comment by Mogost** [comment]
For me, it doesn't affect any automation. But this inconsistency in the naming of releases makes me a little uneasy.

**Comment by native-api** [comment]
@pyenv/pyenv-core-maintainers 

[Looks like](https://github.com/pyenv/pyenv/releases) @yyuu who was doing the releases previously used the `vX.Y.Z` scheme while @anton-petrov who's doing them now and has done the ~5 latest ones prefers the `X.Y.Z` pattern.

* I can get behind the change: since tags mark _only_ releases, "`v`" is redundant.
  * Besides, in a voluntary project, the person doing the work has a moral right for a preferred opinion if there's no real difference
  * And from user's perspective, there is no real difference as long as the order is clear (see below)

* From my own experience, the multiple schemes makes it hard to browse through the tags because they are effectively unsorted:
   * I can't quickly find a tag for a specific version (to check it out to diagnose a problem for a user who uses that version)
   * I can't readily see what are the latest tags in my repo (once, I had trouble finding `1.2.27` and was wondering if my local repo is up to date)
   * **Duplicate tags are way worse than multiple schemes** -- I can't see which version line is the current one

---

I hereby suggest to:

* **Remove duplicated tags**
  * preferring the new scheme
    * since the releases with the new scheme were the original ones and the duplicates were stamped on top of them later
* **Rename old tags, or**
* **let them be** if remaking the corresponding releases poses a problem

**Comment by joshfriend** [comment]
welp, we're back to the `v` prefix it would seem 😆 https://github.com/pyenv/pyenv/releases/tag/v2.0.0-rc1
