### ISSUE TITLE
[FeatureRequest] static shim

### ISSUE THREAD

**Issue by loynoir** [pyenv/pyenv#1918]
# Scenario
There is a cli tool `foobar` at python 2.7, not support 3.7.

And likely will not.

To avoid things got breaked, installed within virtualenv.

# Background
slightly checked [source](https://github.com/pyenv/pyenv/blob/fd3c891d766a091f2dd560701953de722c2b757d/libexec/pyenv-rehash#L64) seems not implemented, so here is a feature request.

# Prepare
```txt
$ git clone \
    https://github.com/pyenv/pyenv-virtualenv.git \
    $(pyenv root)/plugins/pyenv-virtualenv
```

# Actual

Install package
```txt
$ pyenv virtualenv 2.7.10 foobar
$ env \
    PYENV_VERSION=2.7.10/envs/foobar \
    pip install foobar
```

Usage
```txt
$ env \
    PYENV_VERSION=2.7.10/envs/foobar \
    foobar --help
```
Every time call it, needs to explicitly specific with an older python version.

# Expected
Install package
```txt
$ pyenv virtualenv 2.7.10 foobar
$ env \
    PYENV_SHIM_VERSION_LOCK=y \
    PYENV_VERSION=2.7.10/envs/foobar \
    pip install foobar
```

Usage
```txt
$ foobar --help
```
Every time call it, no need to explicitly specific with an older python version.

**Comment by native-api** [comment]
Looks like **what you _actually_ want is to be able to run a tool that belongs to a Pyenv-based installation from elsewhere, as if it was installed globally.**

For this, **a working solution would be to make a separate set of manually-configured "static shims" in another directory:**

* Create another directory and place it into `PATH` _behind_ `shims`
* Add shims there _for the needed executables only_ that would run with a statically defined `PYENV_VERSION`
* Add commands to manage this set: view status, add/overwrite, delete

This way, you'll be able to run a static shim from anywhere _and_ override by installing the cli into the active version: the regular shim will fall through to the static one if the executable is not present in the active version.

This looks like a job for a plugin to me since this is a significant new feature that's only of interest to a subset of users.

**Comment by loynoir** [comment]
Thanks for your reply. Yeah, `static shim` might be more proper name. Got plugin 
(loynoir/pyenv-shim-version-lock)[https://github.com/loynoir/pyenv-shim-version-lock] to make `static shim` at last to fit my need.
