### ISSUE TITLE
Add build environment suggestions for Void Linux

### ISSUE THREAD

**Issue by kofrezo** [pyenv/pyenv#1923]
Hi,

I did not found a way to make a PR for the Wiki contents but if you have time and like to you could add the following section to the HOME.md  -> Suggested build environment.

```
* **Void Linux:**

    ```sh
    xbps-install base-devel bzip2-devel openssl openssl-devel readline readline-devel sqlite-devel xz zlib zlib-devel
    ```
```

**Comment by native-api** [comment]
Is it sufficiently mainstream compared to those included? (I've never heard or it)

The package names look RHEL-based so there's already an effectively the same entry.

**Comment by native-api** [comment]
@pyenv/pyenv-core-maintainers Do we have any principles on which distros we include info on into the wiki?

[There are ~200 currently maintained distros.](https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg) In principle, we can possibly accept info on every single one if we make a separate page -- the entries will gradually become obsolete but that's not a big problem since it's a wiki...

**Comment by yyuu** [comment]
There’s no concrete criteria which distro should be added. As long as there is some user on the distro, it’d make sense to prepare information for it. We might need to consider reorganization of documentation if information floods, but it’d be a problem of future.

**Comment by kofrezo** [comment]
> Is it sufficiently mainstream compared to those included? (I've never heard or it)

No it is pretty niche. It is not a distribution based on Debian, Redhat or something else it is completely build from "scratch". 

I am currently using it besides my regular Debian setup I thought it might be useful for somebody else to not waste time to determine the dependencies, however if you consider it too niche feel free to just close the ticket.

**Comment by native-api** [comment]
Done.
