### ISSUE TITLE
fish ships pyenv completion

### ISSUE THREAD

**Issue by MeggyCal** [pyenv/pyenv#1944]
See https://github.com/fish-shell/fish-shell/blob/master/share/completions/pyenv.fish, so the completion shipped by this package becomes redundant. Maybe it is time to drop it?

**Comment by native-api** [comment]
That's prone to breaking. It's a 3rd-party project and as such is not guaranteed to correspond to the current Pyenv codebase, not to mention another arbitrary version of the codebase that one might have.

**Comment by MeggyCal** [comment]
I see your point, but the two completions are installed at the same place, yours is more compatible with pyenv, theirs is more compatible with fish... and basically, it is not good when two packages conflict. I could probably resolve it with some update-alternatives magic, but it is unclear to me which one has the higher priority. I am just a packager who doesn't want packages to conflict, I don't have any insight to fish, so I can't play the other side in this discussion :) .

**Comment by native-api** [comment]
I don't know why they decided to fork the effort instead of contributing to this project. As far as Pyenv is concerned, that is a 3rd-party project that depends on ours, so it's their job to stay compatible.

As a packager, you probably need to choose which one to use or give your users a choice.

**Comment by native-api** [comment]
We currently provide official support for Fish out of the box, so cutting out a major part of it seems risky: if something breaks for our users, they'll have a hard time getting it fixed if this has to involve mutiple projects, especially if they are packaged (so package maintainers will have to be involved as well).

**Comment by MeggyCal** [comment]
I think it would be best to invite some fish maintainers to the party. @ridiculousfish, why did fish start to provide the pyenv completion?

**Comment by ridiculousfish** [comment]
Hello! fish-shell [got a drive-by PR](https://github.com/fish-shell/fish-shell/pull/6551) for pyenv and we merged it.

We prefer packages to ship their own completions, since they are better maintained and more likely to be up to date. Typically packages do that by placing the `pyenv.fish` file in `/usr/share/fish/vendor_completions.d`. Any such file will take precedence over the one that fish ships, and once it's widespread, we remove the fish-shipped completions ([example](https://github.com/fish-shell/fish-shell/issues/5822)). 

I see that the [arch package](https://archlinux.org/packages/community/any/pyenv/) installs completions, but it looks like [Homebrew does not](https://github.com/Homebrew/homebrew-core/blob/854b4eb2ff7f2fcbb28d0f69cf5c6d6b5d04dd21/Formula/pyenv.rb#L46), so I think fish-shipped completions may still be useful?

cc @zanchey, our resident packaging expert

**Comment by zanchey** [comment]
Yes, the completions from pyenv should be installed in `${datadir}/fish/vendor_completions.d` (this can be found use pkg-config but requires fish installed at the time, so is generally a non-starter). This will mean they take precedence. We have tried to create an infrastructure that means that packagers do not need to interfere in the installation of fish itself.

As a fish committer I am very much in favour of fish completions being maintained with the package they are for, rather than in fish.

**Comment by MeggyCal** [comment]
Thank you, installing the pyenv-provided completion into vendor_completions.d makes sense to me and it is a fine solution. I'll go for it, in openSUSE we install the completion only if both fish and pyenv are installed, anyway. Thanks again!
