### ISSUE TITLE
Path no longer set by pyenv init - in a CI setup

### ISSUE THREAD

**Issue by inakleinbottle** [pyenv/pyenv#1959]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x] Platform information (e.g. Ubuntu Linux 16.04): MacOSx 
- [x ] OS architecture (e.g. amd64):amd64 (Mac)
- [x ] pyenv version: 2.0
- [ x] Python version: 3.5, 3.6, 3.8, 3.9 etc. (For some reason the virtual machine that built 3.7 grabbed pyenv 1.2 which still worked.)
- [x ] C Compiler information (e.g. gcc 7.3): Not sure, some recent version of Clang.
- [ x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I am currently maintaining a package that uses pyenv as part of it's CI/CD pipeline for MacOS. We brew install pyenv to set the correct version of Python, which is a fairly elegant solution to the problem. However, the recent update to pyenv has removed the functionality that sets the PATH environmental variable. This is catastrophic for the integrity of the build system. Also, your readme document suggests that in fact the complete opposite should be the case. As far as I am aware, no deprecation warning was ever provided to warn people that this change was coming. I suggest making this a configuration option or an optional argument to pyenv init to restore the old functionality without having to set the path explicitly (which is not a straightforward task on a complex build system).

**Comment by native-api** [comment]
The change was made to fix a bug (#1649) that was not possible to reliably fix otherwise -- that's why no deprecation period and that's why it's not possible to provide a configuration option or such to keep the old behavior.

To indicate a breaking change, we bumped the major version number (which is the standard practice) and included the info about the breaking change into the release notes. Moreover, the warning message contains the instructions on what reconfiguration needs to be done.
In particular, "the functionality that sets the PATH environmental variable" was not removed, it was rather split off to a different initialization command that needs to be run at a different moment (or maybe even at the same moment depending on your setup).

**Comment by native-api** [comment]
If this is a CI script (i.e. no interactive shells), you need to:
* set `PYENV_ROOT`, add `pyenv` to `PATH` and run `eval "$(pyenv init --path)` somewhere early (ideally, in the initialization file for the login shell for the session);
* then run `eval "$(pyenv init -)` whenever you need `pyenv` to be a shell function (as usual for shell functions, this will have an effect to the current shell and its subshells). You only need that if you're using Pyenv subcommands that require it -- e.g. `pyenv shell` or `pyenv activate` from Pyenv-Virtualenv.

**Comment by native-api** [comment]
If this is a CI script (i.e. no interactive shells), you need to:
* set `PYENV_ROOT`, add `pyenv` to `PATH` and run `eval "$(pyenv init --path)` somewhere early (ideally, in the initialization file for the login shell for the session; or otherwise in some place that sets up the environment for everything that runs afterwards);
* then run `eval "$(pyenv init -)` whenever you need `pyenv` to be a shell function (as usual for shell functions, this will have an effect to the current shell and its subshells). You only need that if you're using Pyenv subcommands that require it -- e.g. `pyenv shell` or `pyenv activate` from Pyenv-Virtualenv.

**Comment by jangroth** [comment]
Any pointers on how to configure VSCode?

I've changed my `~/.zshrc` to 
```
    export PYENV_ROOT="$HOME/.pyenv"                                                                                                                                                              
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
```

Now I get this error message in VSCode:

```
pyenv shell shims
❯ pyenv shell shims
pyenv: shell integration not enabled. Run `pyenv init' for instructions.
```

**Comment by ChuckFoo** [comment]
@jangroth I was discussing a similar issue in pyenv/pyenv-virtualenv#391 and I imagine that if you just add the `eval "$(pyenv init -)"` to your .zshrc file that it'll probably work?  Worth a try anyways.

**Comment by jangroth** [comment]
@ChuckFoo thanks for the pointer. 

After adding
```
    export PYENV_ROOT="$HOME/.pyenv"     
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
```

I'm now seeing this error when opening in terminal in VSCode
```
pyenv shell shims
❯ pyenv shell shims
pyenv: version `shims' not installed
``` 

TBH, I can't make much sense from the command `pyenv shell shims` run by VSCode on new terminal creation. Will need to invest more time to understand this better.

**Comment by gouku** [comment]
@jangroth Any update on this? I've also got this errors after migrating to M1 mac.

**Comment by arcanosam** [comment]
Hi. I just have this problem right now

After change my last line of .bashrc from

`eval "$(pyenv virtualenv-init -)"`

to

`eval "$(pyenv init --path)" `
`eval "$(pyenv init -)"`
                                                                                 
the `pyenv shell` command back to work
