### ISSUE TITLE
Request: Update mtime of shim when installing a newer Python

### ISSUE THREAD

**Issue by cjolowicz** [pyenv/pyenv#1980]
Would it be possible for pyenv to update the mtime of a shim when a newer Python is installed?

Due to the caching logic in virtualenv >= 20, virtualenv currently uses an older pyenv-installed Python to generate environments even when a newer one is installed and activated (https://github.com/pypa/virtualenv/issues/2130). The reason for this appears to be that the mtime of the relevant shim does not change.

It seems to be a relatively straightforward change to teach `pyenv rehash` to copy the newest mtime to the shim. IIUC rehash is triggered automatically after an install. So this would make virtualenv's caching work out of the box with pyenv. I'll send a PR shortly. **Update:** See #1981

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Linux (debian:stable-slim image), Mac
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 3.9.5
- [x] Python version: 3.7.3
- [x] C Compiler information (e.g. gcc 7.3): not relevant
- [x] Please attach verbose build log as gist : not relevant
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by native-api** [comment]
Could you link to and walk us through the corresponding Virtualenv logic that you're referring to?
To make sure and support your reasoning that the mtimes are used by it as you claim they are.

That's because I suspect that your solution as it is now will have unwanted side effects.
E.g. when you switch back to `3.7.9`, it will keep using the cache from `3.7.10`.

**Comment by native-api** [comment]
In fact, the logic as you site it sounds strange. Doesn't Virtualenv check the version of the executable in addition to its mtime?

**Comment by native-api** [comment]
Finally, a shim services not just the currently-active version but all installed versinos at once. If you e.g. `pyenv local 3.7.9`, the shim won't be changed.

So **it's not possible to reliably check if the version is the same as the cache or not by just checking `python''s mtime. If Virtualenv really doesn't check the version, it will need to be fixed to do so.**

**Comment by cjolowicz** [comment]
Hi @native-api thanks for taking the time to look into this!

> Could you link to and walk us through the corresponding Virtualenv logic that you're referring to?
> To make sure and support your reasoning that the mtimes are used by it as you claim they are.

Sure :)

To begin with, let's assume a Linux system with:

- virtualenv installed in `~/.local/bin/virtualenv` using the system Python (3.7.x)
- pyenv installed in `~/.pyenv` using the recommended installer
- Python 3.9.4 installed with pyenv, and activated via `pyenv global`

(I'm changing the example slightly, to match the Dockerfile repro that I posted in the virtualenv issue, https://github.com/pypa/virtualenv/issues/2130#issue-916679622.)

Now suppose we run `virtualenv -p 3.9 venv`.

Here's the initial call stack, from the console entry point to where it gets interesting:

- `virtualenv.__main__.run`
- `virtualenv.run.cli_run`
- `virtualenv.run.session_via_cli`
- `virtualenv.run.build_parser`
- [`virtualenv.run.plugin.discovery.get_discover`](https://github.com/pypa/virtualenv/blob/4c6ca963a9ca32ab507dbed1bbd7b52953da0ee5/src/virtualenv/run/plugin/discovery.py#L10)

Unless the user has a virtualenv discovery plugin installed (unlikely), this function returns an instance of virtualenv's own discovery plugin, `virtualenv.discovery.builtin:Builtin`.

Next, the builtin discovery plugin is queried for an interpreter. Here's the call stack up to where virtualenv generates the list of potential interpreters:

- `virtualenv.discovery.builtin.Builtin.interpreter`
- `virtualenv.discovery.builtin.Builtin.run`
- `virtualenv.discovery.builtin.get_interpreter`
- [`virtualenv.discovery.builtin.propose_interpreters`](https://github.com/pypa/virtualenv/blob/4c6ca963a9ca32ab507dbed1bbd7b52953da0ee5/src/virtualenv/discovery/builtin.py#L76)

This last function performs the following steps:

1. If the interpreter spec is an absolute path and exists, try that.
2. Always try with the interpreter that virtualenv itself is using.
3. (Windows-specific)
4. Generate more candidates by searching PATH.

In step 4, we gather some information for each candidate found on PATH. This is done by running an interrogation script in the target interpreter. As this is not a cheap operation, multiple cache levels are used: an in-memory cache (not interesting here) and a filesystem cache. Here's the call stack:

- `virtualenv.discovery.builtin.PathPythonInfo.from_exe`
- `virtualenv.discovery.py_info.PythonInfo.from_exe`
- `virtualenv.discovery.cached_py_info.from_exe`
- `virtualenv.discovery.cached_py_info._get_from_cache`
- [`virtualenv.discovery.cached_py_info._get_via_file_cache`](https://github.com/pypa/virtualenv/blob/4c6ca963a9ca32ab507dbed1bbd7b52953da0ee5/src/virtualenv/discovery/cached_py_info.py#L53)

The filesystem cache uses a hash of the interpreter path as the index. Besides the information gathered from a previous run of the interrogation script, it also stores the interpreter path and mtime. If both of these did not change, the
[`PythonInfo`](https://github.com/pypa/virtualenv/blob/4c6ca963a9ca32ab507dbed1bbd7b52953da0ee5/src/virtualenv/discovery/py_info.py#L31) instance is created from the cached info. Otherwise, the interrogation script is run via `subprocess`, and the info is inserted into the cache and returned.

Back to our example. Since this is the first run, the interrogation script is run in the target interpreter, by invoking the `python3.9` shim, and information for Python 3.9.4 is stored in the cache for `~/.pyenv/shims/python3.9`.

Now let's install Python 3.9.5 with pyenv, activate it via `pyenv global`, and rerun `virtualenv -p 3.9 venv`. Since pyenv did not update the mtime, virtualenv reuses the information for 3.9.4 from the cache when considering the `python3.9` shim. Consequently, it creates the virtualenv using 3.9.4 instead of 3.9.5.

> That's because I suspect that your solution as it is now will have unwanted side effects.
> E.g. when you switch back to 3.7.9, it will keep using the cache from 3.7.10.

My solution improves the situation for a very common case, though: the case where users install newer point releases from the same `X.Y` series, and just want to use the newest one in the series. Unless I'm mistaken, switching between different Python major and minor versions works fine; only switching between point releases won't work. But it did not work before either, so my proposed solution should be a strict improvement. Am I missing something?

> In fact, the logic as you cite it sounds strange. Doesn't Virtualenv check the
> version of the executable in addition to its mtime?

See above. virtualenv queries the interpreter version and caches it for the interpreter path. The cache is invalidated if the mtime changes.

> Finally, a shim services not just the currently-active version but all
> installed versions at once. If you e.g. pyenv local 3.7.9, the shim won't be
> changed. So it's not possible to reliably check if the version is the same as
> the cache or not by just checking python's mtime.

You're right that the caching method still is not 100% reliable. But for a large number of cases, the situation would be greatly improved if pyenv updated mtimes. I think it's also conceptually not wrong. (But of course, you have my full sympathy for being reluctant to introduce an extra piece of logic and maintain it in the future.)

> If Virtualenv really doesn't check the version, it will need to be fixed to do so.

Sure, another option is that virtualenv does not perform any caching if it detects a pyenv shim (the parent directory is `${PYENV_ROOT}/shims`?). Let's see what @gaborbernat thinks.

**Comment by gaborbernat** [comment]
> In fact, the logic as you cite it sounds strange. Doesn't Virtualenv check the version of the executable in addition to its mtime?

This check is **very expensive**. So we're trying to do some reasonable caching here. Granted this is an edge case we did not account for, and I'm not sure of a better solution than updating mtime of the shim script...

**Comment by cjolowicz** [comment]
I'll just add that I modified the Dockerfile repro from https://github.com/pypa/virtualenv/issues/2130#issue-916679622 to use the change proposed in #1981, and it does indeed fix the caching issue.

<details>
<summary>Dockerfile</summary>

```Dockerfile
FROM debian:stable-slim
ARG DEBIAN_FRONTEND=noninteractive

# Install system Python (3.7.3) and latest virtualenv.
RUN set -ex; apt-get update; apt-get install -y python3 python3-pip
RUN set -ex; pip3 install --user virtualenv
ENV PATH /root/.local/bin:$PATH

# Install Python build requirements for pyenv.
RUN set -ex; apt-get update; apt-get install -y \
    build-essential \
    ca-certificates \
    curl \
    git \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2-dev \
    libxmlsec1-dev \
    llvm \
    tk-dev \
    wget \
    xz-utils \
    zlib1g-dev

# Install pyenv.
RUN git clone -b touch-shims-on-rehash https://github.com/cjolowicz/pyenv.git /root/.pyenv
ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# Ensure pyenv is loaded on each RUN.
RUN >> /root/pyenv.sh echo '#!/bin/bash'
RUN >> /root/pyenv.sh echo 'eval "$(pyenv init -)"'
RUN >> /root/pyenv.sh echo 'exec /bin/bash -c "$*"'
RUN chmod a+x /root/pyenv.sh
SHELL ["/root/pyenv.sh"]

# Install Python 3.9.4 and create a virtualenv.
RUN pyenv install 3.9.4 && pyenv global 3.9.4
RUN date --reference=/root/.pyenv/shims/python3.9 --utc --iso-8601=ns
RUN virtualenv --python=3.9 /tmp/venv-old
RUN /tmp/venv-old/bin/python -VV

# Install Python 3.9.5 and create a virtualenv.
RUN pyenv install 3.9.5 && pyenv global 3.9.5
RUN date --reference=/root/.pyenv/shims/python3.9 --utc --iso-8601=ns
RUN virtualenv --python=3.9 /tmp/venv-new
RUN /tmp/venv-new/bin/python -VV
```

</details>

**Comment by native-api** [comment]
@cjolowicz A great explanation, thank you!

> The filesystem cache uses a hash of the interpreter path as the index. Besides the information gathered from a previous run of the interrogation script, it also stores the interpreter path and mtime. If both of these did not change, the
> [`PythonInfo`](https://github.com/pypa/virtualenv/blob/4c6ca963a9ca32ab507dbed1bbd7b52953da0ee5/src/virtualenv/discovery/py_info.py#L31) instance is created from the cached info.

Okay, this confirms with evidence that Virtualenv uses exactly the raw path and mtime to match a cache entry and there are no other quirks (I thought there might be something else that we can exploit).

> This check is **very expensive**. So we're trying to do some reasonable caching here. Granted this is an edge case we did not account for, and I'm not sure of a better solution than updating mtime of the shim script... after every change to the shim.

I understand -- but what can we do if the cheap check is a wrong check? It doesn't matter how fast you do things if the result is unusable :slightly_smiling_face:, and "correctness over speed" is in Python's motto IIRC. Virtualenv assumes that path on PATH+mtime unambiguously define the installation. In this case, that assumption is wrong. It would likewise be wrong if e.g. the file is a symlink.

See below for a possible fix.

> My solution improves the situation for a very common case, though: the case where users install newer point releases from the same `X.Y` series, and just want to use the newest one in the series. Unless I'm mistaken, switching between different Python major and minor versions works fine; only switching between point releases won't work. But it did not work before either, so my proposed solution should be a strict improvement. Am I missing something?

That's true... What stops me is that
* the problem is in Virtualenv
* this "improvement" is so niche and riddled with bugs while adding cruft to the codebase. It literally fixes just the use case you've described. If the user does _anything_ else, it will still break. E.g.:
  * it links the `X.Y` cache entry not to the most recent version but to _the most recently installed_ version. It will silently switch whenever you install _any_ other version that uses the same shim:
    * e.g. the `-dev` version or a different Python flavor -- quite a normal situation in development if you e.g. need to reproduce an error in a specific version or check if the bug has been fixed in the branch head
* the resulting virtualenv is still broken:
  * if a virtualenv is linked to the shim rather than the real executable, it will be silently using different versions whenever they switch
    * There's even no need for a particular command from the user for this to happen because Pyenv chooses the version at runtime depending on CWD and envvars.
    * In particular, the virtualenv will break altogether if the user switches to a version that doesn't use that specific shim -- e.g. the system version.
* the unnecessary operations added would run every time, even if Virtualenv is not being used or not being used in this particular way
  * In particular, they are unnecessry with the Pyenv-Virtualenv plugin
  * (though I guess a single `touch` is no big deal)
* This "fix" will actually become detrimental once you fix the problem properly -- but we won't be able to remove it until the next major release (see below)

**I guess I can add it if you want it so badly.** But I already see users reporting "weird behavior", and all we can do is direct them to you -- after which you'll have to fix the problem properly anyway. **This just somewhat postpones the inevitable.**
The code will need to be prominently marked as a crutch for Virtualenv so we can remove it ASAP -- this I can do myself.

---

As for a proper fix:

* You can check when discovering the version if the found entry is a "link" and try to "resolve" it:
  * For Pyenv shims, that can be detected by checking if `sys.executable` is different than the path.
     * (Detecting if the entry is specifically a Pyenv shim then calling `pyenv which <basename>` is worse: 1)there's no stock way to check (I guess you can see if `dirname(realpath(file))` is equal to `realpath($(pyenv root)/shims))`), 2)it won't detect other such techniques (e.g. a plugin that creates its own shims), 3)the overhead is going to be similar.)
  * Likewise, if it's a symlink, you call `realpath`
* If yes, you still create a cache entry with mtime and stuff -- but mark it as a "fake executable", then switch over to the real executable.
* When using such an entry, you'll need to do similar checks (you may specify in the cache entry which resolution method to use) then use the real executable's cache entry.
* **This way, you will only incur this tax for entries like this and not in the general case.**

When you do this proper fix, the current fix will become detrimental, invalidating shim's cache entry needlessly -- but we'll have to keep it for compatibility with older Virtualenv versions! (I dunno how long, but probably until the next major release.)

**Comment by gaborbernat** [comment]
I guess from a virtualenv POV I'm tempted to mark this use case as not supported, so I can keep using path+mtime as a key, which worked fine for the last year. This is the first time somewhere complained being a problem, and it's a cheap check. I don't want virtualenv to be slow, indifferent of what people think the python mantra should be.

**Comment by native-api** [comment]
> I don't want virtualenv to be slow

Is checking `sys.executable` -- and only in this particular case to boot -- really "slow"?

Why do you want virtualenv creation to be subsecond in every case anyway? It's not like virtualenvs are created every second in real use, are they?

**Comment by native-api** [comment]
> Is checking `sys.executable` -- and only in this particular case to boot -- really "slow"?

I believe this will add next to nothing on the initial cache creation (because you run a discovery script anyway) and up to ~100-200ms on further invocations.

For the purpose of your believes, you'll still be able to say with confidence that it's "as fast as possible".
In this case, you effectively need to resolve a link -- which you have no control over -- so you can't do that faster than the external resolution mechanism!

**Comment by native-api** [comment]
> Is checking `sys.executable` -- and only in this particular case to boot -- really "slow"?

I believe this will add next to nothing on the initial cache creation (because you run a discovery script anyway) and no more than ~100-200ms on further invocations.

For the purpose of your believes, you'll still be able to say with confidence that it's "as fast as possible".
In this case, you effectively need to resolve a link -- which you have no control over -- so you can't do that faster than the external resolution mechanism!

**Comment by native-api** [comment]
> the resulting virtualenv is still broken:
> 
>     * if a virtualenv is linked to the shim rather than the real executable, it will be silently using different versions whenever they switch
>       
>       * There's even no need for a particular command from the user for this to happen because Pyenv chooses the version at runtime depending on CWD and envvars.
>       * In particular, the virtualenv will break altogether if the user switches to a version that doesn't use that specific shim -- e.g. the system version.

Okay, _this part is false,_ the virtualenv does is linked to the real `sys.executable` (I've deleted it from the previous message, too). Sorry about that.

**Comment by gaborbernat** [comment]
> > I don't want virtualenv to be slow
> 
> Is checking `sys.executable` -- and only in this particular case to boot -- really "slow"?
> 
> Why do you want virtualenv creation to be subsecond in every case anyway? It's not like virtualenvs are created every second in real use, are they?

We need to think about Windows. There calling a subprocess is expensive. Also, many tools, such as tox, create many many virtual environments, so half a second here half there adds up.

**Comment by native-api** [comment]
> We need to think about Windows.

I kinda forgot :slightly_smiling_face: since Pyenv doesn't support Windows.
In fact, since it doesn't, this is not really an issue, is it?

>  Also, many tools, such as tox, create many many virtual environments

"Many many"? Judging by https://tox.readthedocs.io/en/latest/example/basic.html, it's one per tested version -- and I've yet to see a `tox.ini` with more than 5-6 version entries.

**Comment by gaborbernat** [comment]
> I kinda forgot 🙂 since Pyenv doesn't support Windows.
> In fact, since it doesn't, this is not really an issue, is it?
> 
> > Also, many tools, such as tox, create many many

The path discovery is used by all platforms, so would impact all platforms.



> Many many"? Judging by https://tox.readthedocs.io/en/latest/example/basic.html, it's one per tested version -- and I've yet to see a `tox.ini` with more than 5-6 version entries

If you don't care about an extra second here and there that's fine. But it doesn't mean other people don't either.

**Comment by native-api** [comment]
As per the description in https://github.com/pyenv/pyenv/issues/1980#issuecomment-860045568, additional time would only be spent if there are Pyenv-style shims on `PATH` and if `-p <major.minor>` is used.

> inside most packaging tools test suite hundreds of virtual environments are used

Okay, I see.

---

Looks like the topic has been exhausted. Ping me if you still want the PR merged despite the drawbacks outlined above.

**Comment by cjolowicz** [comment]
Thanks @native-api ! I'm leaving this decision to @gaborbernat and just offering my two cents here. Ideally, we'd have a PoC implementation in virtualenv to get a realistic estimate of the performance penalties for the various platforms and constellations. If the performance impact (or complexity of implementation) means that it's not going to happen inside virtualenv, maybe a virtualenv discovery plugin would be the right way forward? Unfortunately, all of this means considerable work that somebody needs to step up to do. Personally, I can't promise this at the moment :\

**Comment by native-api** [comment]
> If the performance impact (or complexity of implementation) means that it's not going to happen inside virtualenv, maybe a virtualenv discovery plugin would be the right way forward?

From the process you descibed at https://github.com/pyenv/pyenv/issues/1980#issuecomment-858661465, that does sound like one way to go, by overriding the necessary parts of the Builtin plugin's logic.

---

Another way is to use/contribute to the [Pyenv-Virtualenv](https://github.com/pyenv/pyenv-virtualenv) Pyenv plugin -- which is a piece of software specifically created to make Pyenv and Virtualenv more convenient to use together.

In the basic use case (when only env name and optionally base Python installation are specified), it completely negates the need for discovery, instead running Virtualenv with the target Python interpterer (so it always creates environments for the running Python).

* As a consequence though, it requires Virtualenv to be installed for the target Python, and as of this writing, it does not install it itself in Venv is present and the requested operation is something that Venv can do as well. [There's a feature request](https://github.com/pyenv/pyenv-virtualenv/issues/392) to make it prefer Virtualenv (and thus install it on demand) even if Venv is present.

If `-p` is explicitly specified however, it does not interfere with Virtualenv's discovery process in any way (to my knowledge, I do not maintain that plugin).

Note though that Pyenv-Virtualenv primarily does its stuff when you use its Pyenv subcommands, NOT when you call `virtualenv` directly like in the use case you've described.
It should be possible however to add logic into that use case, too, since whenever there's a `virtualenv` executable, there should be a shim created for it, giving Pyenv a chance to kick in before of after the underlying program runs.

**Comment by native-api** [comment]
> It should be possible however to add logic into that use case, too, since whenever there's a virtualenv executable, there should be a shim created for it

This is not 100% foolproof. Virtualenv needs to be installed _for one of the alternate Python versions_ (in your use case, it's only installed for the system version) for the shim to be created. Otherwise, it's indistinguishable to Pyenv from any other of the hundreds of executables on `PATH`.

**Comment by native-api** [comment]
> If the performance impact (or complexity of implementation) means that it's not going to happen inside virtualenv, maybe a virtualenv discovery plugin would be the right way forward?

From the process you descibed at https://github.com/pyenv/pyenv/issues/1980#issuecomment-858661465, that does sound like one way to go, by overriding the necessary parts of the Builtin plugin's logic.

---

Another way is to use/contribute to the [Pyenv-Virtualenv](https://github.com/pyenv/pyenv-virtualenv) Pyenv plugin -- which is a piece of software specifically created to make Pyenv and Virtualenv more convenient to use together.

In the basic use case (when only env name and optionally base Python installation are specified), it completely negates the need for discovery, instead running Virtualenv with the target Python interpterer (so it always creates environments for the running Python).

* As a consequence though, it requires Virtualenv to be installed for the target Python, and as of this writing, it does not install it itself if Venv is present and the requested operation is something that Venv can do as well. [There's a feature request](https://github.com/pyenv/pyenv-virtualenv/issues/392) to make it prefer Virtualenv (and thus install it on demand) even if Venv is present.

If `-p` is explicitly specified however, it does not interfere with Virtualenv's discovery process in any way (to my knowledge, I do not maintain that plugin).

Note though that Pyenv-Virtualenv primarily does its stuff when you use its Pyenv subcommands, NOT when you call `virtualenv` directly like in the use case you've described.

* (It should be possible however to add logic into that use case, too, since whenever there's a `virtualenv` executable, there should be a shim created for it, giving Pyenv a chance to kick in before or after the underlying program runs.  
   This is not 100% foolproof though. Virtualenv needs to be installed _for one of the alternate Python versions_ (in your use case, it's only installed for the system version) for the shim to be created. Otherwise, it's indistinguishable to Pyenv from any other of the hundreds of executables on `PATH`.  
  So I guess this is not an option.)

**Comment by gaborbernat** [comment]
> Another way is to use/contribute to the [Pyenv-Virtualenv](https://github.com/pyenv/pyenv-virtualenv) Pyenv plugin -- which is a piece of software specifically created to make Pyenv and Virtualenv more convenient to use together.

This only works if you're manually creating virtual environments and would fail for where tools need to do this (tox/nox/pipenv/etc.).

I think it's a fair expectation to expect tools to touch Python executables whenever they relink it to a different version. Which IMHO is how this should be fixed.

**Comment by native-api** [comment]
Pyenv does not "relink". Instead, shims choose the version at runtime each time, without changing anything in the filesystem -- and even if the user doesn't have the permissions to the shims dir (that happens if Pyenv is installed globally).
This allows multiple processes to use multiple versions at the same time -- through the same shims.
So that's not possible, I'm afraid.

[We considered changing PATH instead of using shims like RVM does](https://github.com/pyenv/pyenv/issues/1112) -- but that would lose us that seamless switching capability.

Note that the same situation would happen if `pythonX.Y` is a symlink and you change the file at its destination without changing the symlink itself.
That's why I showcased symlinks -- as an analogy and to show that having to resolve links is hardly something unusual or too much to ask.

**Comment by gaborbernat** [comment]
Yeah, but symlinks are static. So whenever you update the destination the symlink points to, the process could also update the symlink. The fully dynamic shim is more esoteric and hard to reason about. 


Guess virtualenv could add some kind of ``--disable-py-info-cache`` (also know as yes I'm happy to be slow, though more correct for my use case) flag for people who use pyenv shim feature...

**Comment by native-api** [comment]
> The fully dynamic shim is more esoteric and hard to reason about.

I'd like to think of Pyenv as a sufficiently widely used software to not consider its presence an "esoteric" setup :wink: 

I guess it's possible to implement shims transparently -- with e.g. a custom FUSE filesystem (this is a huge disadvantage UX-wise though since it would massively increase Pyenv's footprint in the system). But that won't change anything performance-wise -- it will just move the link resolution step from user code into the FUSE module. If anything, it will make things _slower_ because the link would need to be resolved every time its directory entry info is queried. The custom FS can present shims as symlinks whose filesystem info doesn't change dynamically (only its target does) to avoid the latter tax -- but that wouldn't work for you because you don't resolve symlinks, either.

> So whenever you update the destination the symlink points to, the process could also update the symlink.

That's not something you can rely upon. For starters, because there's no way to find all symlinks that point to a specific file.

> For me personally, this is both a feature and an anti-feature. Offers higher flexibility but makes it much harder to reason about what's happening; and I never felt I needed this.

Didn't quite get what the 2nd sentence means. How does it "make it hard to reason about what's happening"?

**Comment by gaborbernat** [comment]
> I'd like to think of Pyenv as a sufficiently widely used software to not consider its presence an "esoteric" setup 😉

It's not totally unusual, but it is esoteric compared to Windows + brew + Linux OS alternatives. And not many people use the dynamic nature of shims (e.g. myself too only use `pyenv global 3.9.5 3.8.8 3.7.10 3.6.13 3.5.10 2.7.17`) mode that supports the existing functionality. 

> That's not something you can rely upon. For starters, because there's no way to find all symlinks that point to a specific file.

I wasn't thinking of automation here, but the user can ensure this manually. They've set up their system they know what symlinks they need to update. Alternatively, just delete the virtualenv cache to force a cache invalidation.

> Didn't quite get what the 2nd sentence means. How does it "make it hard to reason about what's happening"?

It's hard to tell what is called when you type `python3` 😊, something that your script might care about.

**Comment by brechtm** [comment]
For anyone who runs into this and would like to get around it temporarily, here's how to find out where virtualenv's cache is located so you can delete it:

    virtualenv --help | grep cache

**Comment by gaborbernat** [comment]
You can also pass in this flag https://virtualenv.pypa.io/en/latest/cli_interface.html#reset-app-data 👍 to request a fresh start.

**Comment by brechtm** [comment]
@gaborbernat Just wondering: is this caching a new feature in virtualenv? If so, I personally never noticed any slowness, so it would be a good option to be able to disable caching by means of an environment variable pyenv users can set in their RC files and forget about :-)

**Comment by gaborbernat** [comment]
This is something introduced with version 20. So a bit over a year old.

> > Guess virtualenv could add some kind of `--disable-py-info-cache` (also know as yes I'm happy to be slow, though more correct for my use case) flag for people who use pyenv shim feature...
> 
> I'd accept such PR into virtualenv, and pyenv users can set it to default true in their user virtualenv configuration file.

If someone puts a PR with that I'll accept and then people can set it, my offer stands.
