### ISSUE TITLE
[documentation] incorrect instructions for fish shell 

### ISSUE THREAD

**Issue by pawelmhm** [pyenv/pyenv#1990]
Instructions for fish in readme.md file here on github say
```
Execute this interactively:

set -Ux PYENV_ROOT $HOME/.pyenv
set -U fish_user_paths $PYENV_ROOT/bin $fish_user_paths
And add this to ~/.config/fish/config.fish:

status is-login; and pyenv init --path | source
```

then it says you should

```
pyenv init - | source
```

So here is what I get when I follow [readme.md](https://github.com/pyenv/pyenv), you can see I have pyenv root set, I have fish user paths, I have config.fish exactly as README.md says. I have virtualenv with python 3.9.1 and default Python system wide 3.8.5. I get warnings about no longer setting path, virtualenv is activated properly, but python is not correct, it should be 3.9.1.

I would be really grateful for instructions for fish users. I'm long time fish and pyenv user, and pyenv worked great for me for a long time.

![Screenshot from 2021-06-26 15-11-02](https://user-images.githubusercontent.com/2700942/123514051-e0cb8100-d690-11eb-8684-6338219789bf.png)

**Comment by native-api** [comment]
@faho, could you advise?

Also see https://github.com/pyenv/pyenv/pull/1991 -- someone else had trouble with fish instructions, too.

**Comment by faho** [comment]
The fish instructions are a reasonably direct translation of the bash/zsh ones. The only difference is that it suggests using universal variables for things that, to a first approximation, don't change. So instead of adding $PYENV_ROOT/bin to $PATH every time, you add it to $fish_user_paths once and fish then takes care that it's in $PATH.

There is a bit of weirdness in the suggestion to do things differently for login shells - in my opinion the concept of a "login shell" is basically broken, but that's also consistent between the shells.

It would be possible to change all of this to suggest changing it in config.fish, and to not require a login shell, but I don't think that's where the error lies.

I would assume the problem here is that you don't have a login fish running, so `pyenv init --path | source` isn't ever actually run?

The output of `set --show PATH` and `set --show fish_user_paths` would be useful.

**Comment by pawelmhm** [comment]
> The output of set --show PATH and set --show fish_user_paths would be useful.
![Screenshot from 2021-06-27 19-22-33](https://user-images.githubusercontent.com/2700942/123553689-0afa6d00-d77d-11eb-8309-58aad093093b.png)

> I would assume the problem here is that you don't have a login fish running (because you never did chsh)

I did chsh, I followed all instructions from fish docs. 

```
~ ❯❯❯ chsh                                                                 ✘ 130
Password: 
Changing the login shell for pawel
Enter the new value, or press ENTER for the default
	Login Shell [/usr/bin/fish]: 

```

In the end I fixed my problem by doing following

```
set -U fish_user_paths $PYENV_ROOT/shims $fish_user_paths
```

and after this it works fine. 

One thing to note is that all these problems are new, it all worked fine for me when I followed docs in my previous installation of ubuntu with pyenv < 2.

**Comment by pawelmhm** [comment]
Ohter thing I'd like to note, is that there is misleading warning from pyenv saying

```
pyenv-virtualenv: prompt changing not working for fish.
```
this is not true, at least not for all cases, I'm testing different prompts and it works fine for some of them. Warning is also new in >2, because in old versions it was always working fine in fish, prompt was always properly set to virtualenv name.

Example here, this is Nim style prompt and you can see "scrapy" virtualenvironment is there, shown fine
![Screenshot from 2021-06-27 19-49-54](https://user-images.githubusercontent.com/2700942/123554569-e2747200-d780-11eb-8797-c8a887d877bd.png)

**Comment by faho** [comment]
>In the end I fixed my problem by doing following

> set -U fish_user_paths $PYENV_ROOT/shims $fish_user_paths

That is exactly the directory that `pyenv init --path` adds, so that part did not run.

Which means you either don't have that part in config.fish like the docs say, you don't have fish as your login shell, your system doesn't run the login shell in its startup path or you've not logged in again after setting fish as your login shell.

Like I said above, I'm not sure why `pyenv init --path` is a separate step.

>Example here, this is Nim style prompt and you can see "scrapy" virtualenvironment is there, shown fine

That's because [the nim prompt handles it](https://github.com/fish-shell/fish-shell/blob/8ddbf857687c21c96855610ca2dc6cde68e3bbf6/share/tools/web_config/sample_prompts/nim.fish#L108-L112).

The default "activate.fish" script will [copy your prompt and inject virtualenv handling](https://github.com/python/cpython/blob/4861fdaf25f246eb9ee4e8161c15dad26efe895d/Lib/venv/scripts/posix/activate.fish#L43-L64), I'm not sure if that's inhibited by pyenv.

**Comment by gialmisi** [comment]
I am also having issues with the instructions in the README regarding fish. My working config.fish has the following contents:

```
status is-interactive; and pyenv init --path | source
pyenv init - | source
```

So I had to add an additional line with `pyenv init - | source`, otherwise I get

```
~> pyenv shell 3.7.8
pyenv: shell integration not enabled. Run `pyenv init' for instructions.
````

in a fish shell. Executing `pyenv init - | source` in the same shell fixes this issue.

**Comment by anton-petrov** [comment]
Hi, guys, thanks for your participating and feedback! 
Can someone take up the writing of the correct instructions for Fish?

**Comment by rakyi** [comment]
I installed fish with Homebrew on macOS. Adding this to my `config.fish` was enough:

```fish
status is-login; and pyenv init --path | source
status is-interactive; and pyenv init - | source
```

However, I don't really understand all the pieces, so I'm not sure if it is the best/complete way of setting it up.

**Comment by native-api** [comment]
I've added [@rakyi's instructions](https://github.com/pyenv/pyenv/issues/1990#issuecomment-897082171) into https://github.com/pyenv/pyenv/issues/1990. Since `pyenv init --path | source` is intended to run in a login shell and `pyenv init - | source` in an interactive shell, it does make sense to prepend both with checks.

**Comment by pawelmhm** [comment]
Just a update on this, I updated to new linux (I do it somewhat frequently because I like to test different Linux releases) and again I'm facing same problem with completely fresh Linux Mint, even with current instructions, again I had to manually run

```
set -U fish_user_paths $PYENV_ROOT/shims $fish_user_paths
```

which was supposed to be run by pyenv init --path. I noticed however that fish is not my login shell, so that explains why instructions are not run. Which brings me to a question: why do we assume fish must be a login shell for all users? If fish is not login shell shims won't get added. I have fish as my default shell, launch it via terminal but status shows me

```
╰─>$ status
This is not a login shell
Job control: Only on interactive jobs
```

Other thing: I don't understand why docs recommend setting these things in config.fish when they can be run once as post installation step? You can easily set user paths once, no need to do it on every fish startup.

 I'll prepare Pull Request with docs update and we can discuss it there.

**Comment by native-api** [comment]
@pawelmhm The documentation actually mentions this:

> If Fish is not your login shell, also follow the Bash/Zsh instructions to add to `~/.profile`.

I'm also considering going forward with https://github.com/pyenv/pyenv/issues/2085 which will eliminate the need for a separate step to add `shims` to `PATH` (except in some cases where this needs to be done at a separate moment, but they don't apply to Fish).
