### ISSUE TITLE
Pyenv rehash conda.bash change #2027 for bash4 breaks when using bash3.2 (which is osx default)

### ISSUE THREAD

**Issue by jaybocc2** [pyenv/pyenv#2034]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Mac OSX 11.5.2
- [x] OS architecture (e.g. amd64):  x86_64-apple-darwin20
- [x] pyenv version: pyenv 2.0.4-12-g3738c2a2
- [x ] Python version: 3.9.6
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

It looks like PR https://github.com/pyenv/pyenv/pull/2027 has broken pyenv rehash on bash < 4 versions (in my case my osx comes with bash 3.2)
This is awkward as i haven't updated pyenv in a few weeks and happened to do it 6 hours after this change was merged.

```
# pyenv install 3.9.6
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.9.6...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.9.6 to /Users/jay/.pyenv/versions/3.9.6

/Users/jay/.pyenv/pyenv.d/rehash/conda.bash: line 37: conditional binary operator expected
# pyenv rehash
/Users/jay/.pyenv/pyenv.d/rehash/conda.bash: line 37: conditional binary operator expected
# which bash
/bin/bash
# bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
# pyenv --version
pyenv 2.0.4-12-g3738c2a2
```

**Comment by sodul** [comment]
This breaks with zsh as well which is the default Shell for macOS from now on. These scripts should probably be required to be POSIX compliant to avoid compatibility with other shells.

**Comment by anton-petrov** [comment]
I think we need to decide whether to maintain compatibility with very old software, such as bash 3.2, or provide some requirements in the documentation. in the same time, perhaps, the PR #2027 potentially broken for old bash and zsh (zsh has a separate variable type for associative arrays). Thus, either in the near future we fix compatibility or I will roll back #2027.
Any suggestions about it?

**Comment by sodul** [comment]
@anton-petrov  my suggestion is to keep shell scripts POSIX compliant so they can work with most shells including dash, older Bash, zsh and busybox. Of course some shell will still break like tcsh since that one is not POSIX compliant.

Ubuntu has a good page on the topic and they provide a tool to check for bashism:
https://wiki.ubuntu.com/DashAsBinSh
http://manpages.ubuntu.com/manpages/trusty/en/man1/checkbashisms.1.html

**Comment by NyaMisty** [comment]
@sodul  Sorry for the inconvenience :( Does this script breaks rehash on Zsh? I'm using zsh myself on Ubuntu 20.04. And here's my log
```
 misty@DESKTOP-697LVJS  /mnt/c/Users/Misty  rm -rf /opt/pyenv/shims/*
zsh: sure you want to delete more than 100 files in /opt/pyenv/shims [yn]? y
 misty@DESKTOP-697LVJS  /mnt/c/Users/Misty  ls /opt/pyenv/shims/*
zsh: no matches found: /opt/pyenv/shims/*
 ✘ misty@DESKTOP-697LVJS  /mnt/c/Users/Misty  pyenv rehash
 misty@DESKTOP-697LVJS  /mnt/c/Users/Misty  ls /opt/pyenv/shims/*
/opt/pyenv/shims/2to3                                /opt/pyenv/shims/frida-trace               /opt/pyenv/shims/main                              /opt/pyenv/shims/qgltf
```

**Comment by jaybocc2** [comment]
Rehash has a bash #! So it shouldn't be using zsh when you run rehash. However as long as pyenv remains Bourne she'll compatible there will not be portability issues.

**Comment by NyaMisty** [comment]
Also my PR does not intend to drop the support for Bash 3 at all.
I'm using the answer from: https://stackoverflow.com/a/26931860/5367153 
However I forgot the chicken-or-egg problem, I'm checking for associative array using bash4's syntax.
Now I've fixed my PR.

**Comment by sodul** [comment]
@NyaMisty @jaybocc2 sorry if I accidentally pointed out zsh, I had not looked too deep into it. We had a team member that was installing python through pyenv and they kept on getting the python version from the OS, or brew. We eventually noticed that the shims directory was empty and that the `pyenv rehash` was throwing an error. We checked the git log and noticed the failing line had just been updated that day.

We put my copy of the conda.bash script and everything went back to normal.

Since Bash is not always available, like with Alpine Linux for example, it is probably best if the shell scripts can stay POSIX compliant. It is pretty clear that Apple will not upgrade Bash beyond 3.x due to the licensing issues. If they were open to that they would not have switched from Bash to zsh as the default. I do understand that we can install newer versions of Bash with Brew, but it brings a lot of baggage with it and its own set of issues so I don't think asking pyenv user to have Bash 4+ as a prerequisite is a good option.

**Comment by NyaMisty** [comment]
@sodul @jaybocc2 Could you please help me test it on Mac? I've test the new fix on bash 3.2 docker, but I don't really have a Mac. Much sorry for the inconvenience I brought to you and your teams! :(

**Comment by sodul** [comment]
@NyaMisty I had to uninstall Bash 5 from brew, but since I'm fully on zsh that was not a concern.
I tried your master branch with Bash 3.2 on macOS 11.5.2 on and confirmed that pyenv rehash repopulates the shims directory as expected.

**Comment by jaybocc2** [comment]
@NyaMisty i checked out your fork and it works for me.
