### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by armenzg** [pyenv/pyenv#2057]
Hi,
I want to nominate pyenv for sponsorship at my company.
We're mainly accepting GH sponsorship and open collective.

Thanks!

**Comment by native-api** [comment]
About project-wise sponsorship, only the folks that own the project's Github account can say. @pyenv/pyenv-core-maintainers , any information?

I personally am happy to receive bounties for closing specific issues that you are interested in.

**Comment by native-api** [comment]
> I personally am happy to receive bounties for closing specific issues that you are interested in.

We've received donations from Bountysource like that. That platform has proven convenient for such a format. AFAICS, you can put a set amount of money onto an account there and place bounties funded from that sum as needed.

**Comment by yyuu** [comment]
Sorry for being laggy these days 🙇‍♂️  And, thank you for having interest on the project.

As it has already mentioned, https://www.bountysource.com/ is the only option for donation. To be quite honest, I don't have very good insights on how-to receive any donation as the project team, not as individual contributor, because we are just a OSS project on GitHub and we don't have any formal organization/body.... 🤔  In case your company is willing to donate for this project, it's nice if you can create an issue on this project, and post some bounty. Some active maintainers of the project will be eligible to earn the bounty.

By the way, I have made @native-api and @anton-petrov as project owners thanks to great contributions so far. Now you guys don't have to wait for myself, but can lead the project overall. Plus, it will be very good if these contributors to be rewarded in some way like bounties. Thanks again fo all the attentions, contributions and donations! :tada:

**Comment by anton-petrov** [comment]
Thanks @yyuu !

**Comment by armenzg** [comment]
Thanks for letting us know. Unfortunately, the way we were planning to disburse funds would not work with bountysource.
If you did set up Github sponsors we would be able to send funds.
Please let me know if you do so and we can look into donating funds next year.

**Comment by native-api** [comment]
Okay, now that I have the rights, I see that it's possible to set the project up for Github Sponsorship without the need to have a legal entity, using Open Source Collective (it's one of several options) as a fiscal agent. Will that do?

**Comment by armenzg** [comment]
That would work for us. We've been using GH sponsors and/or OSC.

**Comment by anton-petrov** [comment]
@native-api contact me by mail (in my profile) to synchronize our actions since I do not know your email address.

**Comment by native-api** [comment]
Okay, the Github Sponsors setup for the project seems to be online now.

**Comment by armenzg** [comment]
Thank you!

**Comment by armenzg** [comment]
Hi,
I checked and I was expecting something like [this][brew], however, I don't see one for [pyenv][pyenv] (it redirects).

[brew]: https://github.com/sponsors/Homebrew
[pyenv]: https://github.com/sponsors/pyenv

**Comment by native-api** [comment]
@armenzg Oh, sorry. It turns out, it's still pending Github staff's approval (since Friday).
It started giving another page today when clicking the "sponsor" button -- that made me think it came live :-\

**Comment by native-api** [comment]
Okay. I had to contact Github support in the end, and now it's live for real!

**Comment by armenzg** [comment]
Thanks @native-api ! I can see it working.
