### ISSUE TITLE
Improve zsh installation instructions

### ISSUE THREAD

**Issue by shniubobo** [pyenv/pyenv#2058]
In zsh, `typeset -U PATH` can be used to avoid duplicate values in `PATH` (see [this manual page](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html)). Also, according to [its user guide](https://zsh.sourceforge.io/Guide/zshguide02.html#l24), this is the recommended way to set `PATH`.

Therefore, the following configuration, either in `.zshrc` or `.zshenv`, would work perfectly for zsh (no need to seperate any of them into `.zprofile`):

```zsh
typeset -U PATH
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

I am willing to submit a PR to update `README.md` if this configuration is acceptable.

**Comment by anton-petrov** [comment]
Please, submit a PR.

**Comment by native-api** [comment]
I've made a PR with updated setup instructions based on user feedback so far. Please review: https://github.com/pyenv/pyenv/pull/2067

Since the suggested configuration ensures there are no duplicate PATH entries -- unless the users specifically intends so -- `typeset -U` seems like unnecessary complication.

**Comment by shniubobo** [comment]
> Since the suggested configuration ensures there are no duplicate PATH entries -- unless the users specifically intends so -- `typeset -U` seems like unnecessary complication.

Yes, that makes sense.
