### ISSUE TITLE
"pyenv global" has no effect with Homebrew and Bash in Mojave

### ISSUE THREAD

**Issue by ghostforest** [pyenv/pyenv#2115]
So if you install pyenv with homebrew and you change the version in bash with: "pyenv global 3.6.7"

If you then execute "python -V"
you'll still get the system version. 

I googled a ton until I realized my ~/.bash_profile needs the following line:

export PATH="$HOME/.pyenv/shims:$PATH"

Instead people tell you to add: 
export PATH="$HOME/.pyenv/bin:$PATH" which will do nothing as there is no bin folder existing.

To check wether your path is correct on OS X: type "echo $PATH" in terminal. The first path showing up should be: /Users/YourUserName/.pyenv/shims

**Comment by native-api** [comment]
>  I used the last one for Bash that says "(OS X)" however I already had ~/.bashrc and ~/.bash_profile files existing.

That's an unusual setup then. The README directs one to the Advanced configuration section for these.

In your case, you need to add `eval "$(pyenv init --path)"` to `~/.bash_profile` and `eval "$(pyenv init -)"` to `~/.bashrc`. Or add the former line to `~/.profile` and make `~/.bash_profile` source `~/.profile`.

**Comment by native-api** [comment]
> If I add "export PATH="$HOME/.pyenv/shims:$PATH" to bash_profile, it just works.

This means your shell isn't configured to run as a login shell.

**Comment by native-api** [comment]
The README instructions have been tested to work. The advanced configuration section tells you when both commands should run (`--path` in the login shell, `-` in any interactive shell) so that in an unusual setup, you can figure out where to place them accordingly.

To say anything about what's happening at your shell's startup, I'd need to see a debug trace as per the issue template.
Place the `PS4` and `set -x` lines at the start of the shell startup file that's sourced first and you should get the trace of the entire shell startup.

**Comment by ghostforest** [comment]
+ alias 'reload=exec /bin/bash -l'
+ export PATH=/Users/User/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/User/.pyenv/shims
+ PATH=/Users/User/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/User/.pyenv/shims
++ pyenv init --path
+ eval 'export PATH="/Users/User/.pyenv/shims:${PATH}"'
++ export PATH=/Users/User/.pyenv/shims:/Users/User/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/User/.pyenv/shims
++ PATH=/Users/User/.pyenv/shims:/Users/User/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/User/.pyenv/shims

this is the output.

this is my .bash_profile:
set -x

# Alias
alias reload="exec $SHELL -l"

# Pyenv
export PATH="$HOME/.pyenv/shims:$PATH"
eval "$(pyenv init --path)"

this is .bashrc
eval "$(pyenv init -)"

**Comment by native-api** [comment]
The PATH is correct, but `bash_profile` should also source `bashrc` if the shell is interactive (https://serverfault.com/questions/146745/how-can-i-check-in-bash-if-a-shell-is-running-in-interactive-mode).

I suspect that because it doesn't, you end up not running `eval "$(pyenv init -)"` at all -- thus not running `pyenv rehash` that it runs under the hood -- so your shims are not up to date.
