### ISSUE TITLE
Python 3.x fails compilation against OpenSSL configured with SSLv3 support: "implicit declaration of function ‘SSLv3_method’"

### ISSUE THREAD

**Issue by russellvt** [pyenv/pyenv#2181]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too. (Related to #1493)
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- Platform: `CYGWIN_NT-10.0 HOSTNAME-XXXXXXX 3.3.2(0.341/5/3) 2021-11-08 16:55 x86_64 Cygwin`
- OS architecture: `Windows 10 (20H2 Build 19042.1348)`
- pyenv version: `2.2.2-1-gf2925393`
- Python: `3.9.9` (Really 3.6+)
- Compiler: `gcc 11.2.0`
- The [debug trace of the failing command as a gist](https://gist.github.com/russellvt/17757c75bf801d5f5f1ae60c1f8102ed):
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * Note: Directory has been "sanitized" to be /home/russell in the gist.

**Comment by native-api** [comment]
This is a problem in CPython. Apparently, it happens when built against OpenSSL 3.0 built with SSLv3 support (which is rare, it's disabled by default).
As per https://www.mail-archive.com/freebsd-ports@freebsd.org/msg86654.html, it was introduced in https://bugs.python.org/issue43799 ([3.8.10](https://github.com/python/cpython/commit/b71aaa0df0f3a9640b034b4774651cd8c54d2fb9) and [3.9.5](https://github.com/python/cpython/commit/7d9d5bf863bb0af26b74b0732ab89b2053d2fbec)) and fixed only in [3.10.0](https://github.com/python/cpython/commit/3309113d6131e4bbac570c4f54175ecca02d025a)  -- they initially defined stubs for `TLS*_method` but not for `SSLv3_method`.

---

A workaround is to add `-DOPENSSL_NO_SSL3` to the `CFLAGS` envvar.

**Comment by russellvt** [comment]
> A workaround is to add `-DOPENSSL_NO_SSL3` to the `CFLAGS` envvar.

Adding that CFLAG introduces some new issue, [shown in this gist](https://gist.github.com/russellvt/fc4d19f4e88b67e846f9c5227cfd4ebd).

Command Line:

> `env CFLAGS=-DOPENSSL_NO_SSL3 PYENV_DEBUG=1 pyenv install -v 3.9.9 2>&1 | tee python-3.9.9-pyenv-cflags.log`

**Comment by russellvt** [comment]
Essentially looks like we are back to this..

> `ModuleNotFoundError: No module named 'math'`

**Comment by russellvt** [comment]
Note that the distribution compilation seems to work (though there are still some configurable modules that are "missed" without additional flags), but fails with the same error on `make altinstall.`

So, I presume this is something in CPython that's breaking the math module (unless there's an obvious "miss" in the configure scripts).

Any additional help appreciated... though looking this this is not a `pyenv` problem, so much.

**Comment by native-api** [comment]
Yes, these are all CPython build's problems. We do not officially support Cygwin, but CPython probably does, which makes it all the stranger.

> checking for library containing crypt... -lcrypt
> checking for library containing crypt_r... none required
> checking for crypt_r... yes
> <...>
> /tmp/python-build.20211203161731.4406/Python-3.9.9/Modules/_cryptmodule.c:44: undefined reference to `crypt_r'
> 

`config.log` should give a clue why Configure deemed `-lcrypt` unnecessary (according to `man crypt_r`, it is necessary).

> /tmp/python-build.20211203212528.22198/Python-3.9.9/Modules/_ctypes/cfield.c:2:10: fatal error: pycore_byteswap.h: No such file or directory

This is due to `-I./Include/internal` missing from compiler flags for the extension.

> checking for --with-system-ffi... yes
> <...>
> /tmp/python-build.20211203212528.22198/Python-3.9.9/Modules/_ctypes/callbacks.c:23: undefined reference to `ffi_closure_free'

I didn't check where `--with-system-ffi` comes from but this means that you need to either install it or override that switch.

**Comment by sevens** [comment]
Just an FYI: I just ran into the `SSLv3_method` issue on Slackware Linux as well, trying to compile Python 3.9.15 with `pyenv`.  Using `CFLAGS='-DOPENSSL_NO_SSL3'` solved it (no issue with `math` lib).  This is with OpenSSL 1.1.1q however (haven't installed OpenSSL 3 at all), with `enable-ssl3`.

**Comment by asloan7** [comment]
Centos 7 as well
Python-3.9.15/Modules/_ctypes/_ctypes.c:107:17: fatal error: ffi.h: No such file or directory

**Comment by native-api** [comment]
Since this is a problem in a number of CPython versions, we will accept a patch for them if someone is interested in providing one.

**Comment by souravjamwal77** [comment]
@russellvt Is this issue resolved? Because I can't install any package with pyenv on ubuntu.

**Comment by samuel-emrys** [comment]
Confirming that I can't install 3.10.0 or newer in ubuntu 16.04 (3.9.16 works)

**Comment by souravjamwal77** [comment]
Hi @samuel-emrys if your Ubuntu has python 3.8 or 3.6 then you need to install the dev dependencies from apt for that.
