### ISSUE TITLE
Improve Installation instruction of pyenv

### ISSUE THREAD

**Issue by startakovsky** [pyenv/pyenv#2214]
What does this mean? It would be helpful if there were some clarification as I do not know what it means to be "... installed with a Git checkout"? This is in the section of the README where it explains how to install for a Mac OS.

**Comment by JaimeMitchell** [comment]
It means that they really are all over the place. For instance, You have mac and windows installations on the same page, AND for Mac, we have to jump from one page for the other for every initial requirement. Instead, you should put everything on one page for Mac, WITHOUT having to open 3-5 tabs of confusion and chaos. Windows install goes on its own page. That alone would have been a big help. Also, because I got confused with these instructions, nothing is working and here is what my paths look like and I don't know what to do about this. I've tried uninstalling and reinstalling, throwing out all the shims. Nothing works. Hours of confusion when you folks could have put everything on one page for Macs. 
/Users/jaime/.pyenv/shims/python3
/Users/jaime/.pyenv/shims/python3
/Users/jaime/.pyenv/shims/python3
/opt/homebrew/bin/python3
/usr/bin/python3

when it should just be /usr/bin/python from what this person said:
https://github.com/Homebrew/discussions/discussions/476

ls -l /opt/homebrew/bin/python*
lrwxr-xr-x  1 jaime  admin  40 Feb 23 23:40 /opt/homebrew/bin/python-build -> ../Cellar/pyenv/2.2.4-1/bin/python-build
lrwxr-xr-x  1 jaime  admin  39 Feb 23 22:23 /opt/homebrew/bin/python3 -> ../Cellar/python@3.9/3.9.10/bin/python3
lrwxr-xr-x  1 jaime  admin  46 Feb 23 22:23 /opt/homebrew/bin/python3-config -> ../Cellar/python@3.9/3.9.10/bin/python3-config
lrwxr-xr-x  1 jaime  admin  41 Feb 23 22:23 /opt/homebrew/bin/python3.9 -> ../Cellar/python@3.9/3.9.10/bin/python3.9
lrwxr-xr-x  1 jaime  admin  48 Feb 23 22:23 /opt/homebrew/bin/python3.9-config -> ../Cellar/python@3.9/3.9.10/bin/python3.9-config
jaime@Jaimes-MacBook-Pro ~ % 

and this looks like it's totally messed up. I also don't see any of the actual version I tried to install, like 3.10.2
so the instructions are pretty bad. I think just putting them in a simplified form, ALL instructions on ONE PAGE, and EACH SYSTEM: Mac, Windows, Linux, Etc. on their OWN SEPARATE PAGE. 

For the love of sanity, please do these things. Thank you.

**Comment by native-api** [comment]
The README has been clarified and restructured as part of https://github.com/pyenv/pyenv/pull/2310.

Please check [the latest README](https://github.com/pyenv/pyenv#readme) and see if anything is still unclear.

**Comment by native-api** [comment]
Note that the instructions are for the new release.

If the Homebrew formula has not been updated yet, install from the `master` branch tip with `brew install pyenv --head`.
