### ISSUE TITLE
Build 3.7.12 fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by fofoni** [pyenv/pyenv#2236]
Hi!

### Description
- [x] Platform information: Arch Linux, Linux 5.15.12-arch1-1
- [x] OS architecture: amd64
- [x] pyenv version: clean clone of tag v2.2.4-1
- [x] Python version: attempting to install 3.7.12
- [x] C Compiler information (e.g. gcc 7.3): gcc 11.1.0
- [x] Debug trace of the failing command: generated with `env PYENV_DEBUG=1 pyenv install -v 3.7.12 2>&1 | tee trace.log`: [trace.log](https://gist.github.com/fofoni/f82c2ee5061d5b76885e64b859ba35a9)

I checked 3.7.6, 3.7.9, and 3.7.11, and they build fine. Version 3.7.12 is the only one that begins by saying "patching file ..." (lots of files), but even with all that patching, it's the only one that fails.

**Comment by ajgringo619** [comment]
Interesting. I got the exact same error on my Arch KDE VM, but my EndeavourOS Cinnamon host compiled it fine; same kernel, same build tool versions, same `pyenv` versions.

**Comment by bruno-fs** [comment]
Got the same error for 3.6.15 on manjaro :thinking:

**Comment by bruno-fs** [comment]
Probably related: https://bugs.python.org/issue42351

**Comment by native-api** [comment]
@chipx86 Looks like a problem in `0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch`. It seems to me we will have to rework the patch to not touch the Linux part of the logic after all, or this will never end.

**Comment by chipx86** [comment]
I unfortunately have no availability today to test a fix, but I can aim to look at it in more detail tomorrow (or very late tonight, if I can squeeze it in).

Cursory glance though: This is from the `grep_headers_for` function in CPython, which was backported by Takumi Sueda for pyenv for Python 2.7.18, but lacked the fix here: https://github.com/python/cpython/commit/7a27c7ed4b2b45bb9ea27d3f5c4f423495d6e939

When I brought that patch to 3.6.15 and 3.7.12, it also lacked that fix. This probably just wasn't noticed on 2.7, due to Python 2.7 opening the file as a byte string and not caring about Unicode content.

This should be a pretty trivial change, since CPython already identified and fixed it.

Given that the parts that touched the Linux logic came from CPython itself (albeit newer versions), I'm not sure I'd feel comfortable diverging too much from upstream's logic, or we could both introduce other build issues without the benefit of pulling in CPython patches that correct them.

**Comment by fofoni** [comment]
Thanks @chipx86 ! Since it's trivial, I think I will take a chance at it and submit a PR.

I suppose I just have to generate a new patch file, based on the correct cpython version tag, using the fix from the CPython commit you linked, and add it to `plugins/python-build/share/python-build/patches/3.6.15/Python-3.6.15` and `plugins/python-build/share/python-build/patches/3.6.15/Python-3.7.12`? I'll do it and, if it works, I'll submit it.
