### ISSUE TITLE
Missing release 2.2.5

### ISSUE THREAD

**Issue by ulgens** [pyenv/pyenv#2281]
Version 2.2.5 is accessible as a git tag [[0](https://github.com/pyenv/pyenv/releases/tag/v2.2.5)], but in releases list [[1](https://github.com/pyenv/pyenv/releases)] 2.2.4 is the latest one. Can you please create a release for it? 🌷 

0: https://github.com/pyenv/pyenv/releases/tag/v2.2.5
1: https://github.com/pyenv/pyenv/releases

**Comment by native-api** [comment]
Done.

**Comment by ulgens** [comment]
I'd like to open this back if possible. Release summary and release notes on changelog doesn't match.

**Comment by native-api** [comment]
@joshfriend Looks like some of your changes didn't make it into the autogenerated release summary because they weren't added through a PR -- and squashed with some unrelated changes like release preparation, too.

Could you please adjust the release summary according to what exactly you added there?

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/releases/tag/v2.2.5 notes have been updated
