### ISSUE TITLE
Asking me to set pyenv global again and again

### ISSUE THREAD

**Issue by boomboomjassi** [pyenv/pyenv#2410]
Every time I open terminal and run python somefile.py I get this.

```
No global python version has been set yet. Please set the global version by typing:
pyenv global 3.7.2
```

Why does it not remember pyenv global set earlier.I guess I am missing some environment variable

**Comment by native-api** [comment]
Please provide the necessary diagnostic information as per the issue template.

**Comment by varunagrawal** [comment]
I am facing something similar though not quite the same.

My `system` python is 3.8.10, but for development I use 3.9.13. I use pyenv to install 3.9.13 and when I run `pyenv versions`, I get this (which is as expected):

```sh
$ pyenv versions
* system (set by /home/varun/.pyenv/version)
  3.9.13
```

As per the documentation, I set the global python with `pyenv global 3.9.13` and the output of `pyenv versions` looks good.
```sh
$ pyenv versions
  system
* 3.9.13 (set by /home/varun/.pyenv/version)
```

However, when I open a new terminal, the python version gets set back to `system` and this is because pyenv is somewhere setting the `PYENV_VERSION` env variable incorrectly:

```sh
$ pyenv versions
* system (set by PYENV_VERSION environment variable)
  3.9.13
```

My guess is that OP and I are having the same root issue but it is manifesting itself in different ways. Or this might be a different issue(?) in which case I'll open a new issue. This is a recent behavior change for me (global python version was working well about 1.5 weeks ago). Any idea what might be the cause @native-api?

**Comment by native-api** [comment]
> and this is because pyenv is somewhere setting the `PYENV_VERSION` env variable incorrectly

Pyenv only sets `PYENV_VERSION` temporarily -- either for commands run via shims/`pyenv exec`, or for the current shell if you run `pyenv shell`.

If you get it set in a new shell, there's most likely something in your shell startup files that either sets it explicitly or runs `pyenv shell`.
