### ISSUE TITLE
Pyenv does not allow installations with generic prefix (alias)

### ISSUE THREAD

**Issue by ssbarnea** [pyenv/pyenv#2600]
While recently pyenv was able to address the very old request about ability to install python versions without having to specify the [minor version](https://github.com/pyenv/pyenv#prefix-auto-resolution), it still did not address the second part about usability: the ability to have stable installation paths, so people can upgrade the minor version without breaking their tools (IDES, virtuale nvironments, ...)

That is a critical missing big because every python path change would fully break virtualenvs and IDE configuration, which will need to be reconfigured to recognize the paths, even if python was only updated from `X.Y.0` to `X.Y.1`.

I do have hundreds (>200) open source repos which I work with and contribute towards, so you can imagine how frustrating is to have to reconfigure python interpreters in each vscode workspace I open as vscode always saves the "resolved" python path (never uses the shims). Usually by the time I fix the python paths a new release is released.

![](https://sbarnea.com/ss/pyenv-python-paths.png)

PS. I am aware that "some" packages might need recompilation, but to be honest in 10+ years of being  a python engineers, I never needed to do that, probably because I usually work with pure-python projects, and even those that are not pure-python, do not need recompilation or reinstall when the minor version of python is updated (thanks for stable ABI).

If it would possible to find a solution for this issue, it would be really awesome as I really appreciate the help that pyenv provided for python users, maintainers in particular.

**Comment by native-api** [comment]
With Pyenv, you're not supposed to be getting "stable installation paths".
You are supposed to instead run stuff in a specific environment.
This is the same for virtualenvs, conda environments etc so Pyenv is not unique or unusually demanding here.

And that's exactly what IDEs that property support virtualenvs, conda etc do. The paths that you see in the list are just for reference so that you have an idea of what that items corresponds to. When settings them up, you instead specify inputs for the tooling, which are not necessarily "hard paths" (I reckon some IDEs might be able to extract those inputs from the path's contents, but in the end, what they store in the configuration is still the inputs).

---

Now, when you're migrating to another version, you have to make reconfigurations anyway: migrate packages to another installation, recreate virtual environments etc. What makes IDE reconfiguration special here?

Moreover, if you sneakily replace an installation underneath the IDE without any changes in its configuration, it will probably not notice that fact and not invalidate its package and indexing caches and such, not to mention change the Python version in use (which drives a considerable amount of IDE's logic).

**Comment by native-api** [comment]
In fact, a separate "Pyenv" section in the screenshot you've shown suggests that that IDE (I don't recognize it to can't verify) does properly support Pyenv.
So if it supports a recent enough Pyenv, it should accept a prefix as the Pyenv-based installation identifier.
