### ISSUE TITLE
Feature req:  Per source name Python build options, Per version/venv runtime parameters

### ISSUE THREAD

**Issue by the-moog** [pyenv/pyenv#2649]
As suggested by comments within [this gist](https://gist.github.com/the-moog/f2aa5d6ea5f77c1e07d67bd7b7f7f8e2)

I think there are good reasons for a plugin (or built in) that allows pyenv to alter it's behaviour, based
on the name of the venv or the version/upstream source of the Python pyenv build time build options

I'd like some comments on the idea proposed, to summaraise here.

- Make it possible for the user to pass arbitrary build options for a given python verson from a given upstream source.

- Have the system fallback to a install, system or user level default (e.g. provided in ./etc/ or .local/etc)

- The same mechanism could be used to alter the environment in various ways at runtime, when the user activates and env or chdirs in and out of that env.

I think this would be implemented as one or more hook scripts and a per install configuration file based on an install default, probably parsed by a simple exe or script, similar to python_config (Sadly that script can't be in Python or we'd have a chicken and egg thing going.  Would have to be sh or exe, I think?)

More info required:
- Good idea Y/N?
- How would a plugin make changes to the existing pyenv install?
- Does pyenv look for hook scripts in each plugin install folder as well as the pyenv.d tree?
- Same question for the bin and other folders, e.g. Would fusermount with overlay-fs be required?

**Comment by native-api** [comment]
Making your script from the gist into a plugin is as easy as placing it under `$PYENV_ROOT/plugins/<your_plugin_name>/pyenv.d/install`.

I doubt that a "do anything" plugin would be any easier to use than writing a custom script for each specific case -- since using it will essentially be programming, there will be wildly different custom parts each time.

I do see potential for the reusable service subroutines if customized for the general case -- e.g. the logging should probably not leave garbage behind by default.
Yet the best way to use then would probably be to incorporate them into Pyenv's logic -- if they're really so useful in Pyenv's line of work, there must be a place for them. Moreover, they could probably even be created by refactoring existing logic.
Then they will be automatically available to plugins -- since plugin code is sourced.

**Comment by native-api** [comment]
I've added [a section to the README about plugins](https://github.com/pyenv/pyenv#pyenv-plugins).

Hopefully this will make adding custom case-specific functionality easier.
