### ISSUE TITLE
Сhoosing a logo for the organization and project

### ISSUE THREAD

**Issue by deronnax** [pyenv/pyenv#2653]
I am a bit bothered by the lack of logo of PyEnv. I like the one of RbEnv a lot (see the picture).
If I was to produce a similar one for PyEnv (mights involve me paying the artist but I am OK with that) with a Python instead of the  ruby, would you adopt it?
![rbenv](https://user-images.githubusercontent.com/439279/227199189-e4b09d50-d9ef-401e-a266-ac8257e5e6e5.png)

**Comment by anton-petrov** [comment]
Hi, @deronnax! It's great idea! Please, make & offer your version and after a public discussion, if the majority likes your logo, we will approve it.

**Comment by native-api** [comment]
The general logo design LGTM.

Might be a bit dark and gloomy on the usual light background -- see e.g. the Rbenv's logo at https://www.libhunt.com/r/rbenv and compare with other entries. That could be fixed by e.g. likewise giving it a light background.

Where is it supposed to feature? That, I guess, could add some specific technical requirements.

**Comment by deronnax** [comment]
It would feature as the PyEnv Github organisation logo. The current one is the one of an avatar-less GitHub user.

**Comment by anton-petrov** [comment]
Another version from me

![pyenv_logo_v1](https://user-images.githubusercontent.com/2428315/227700588-289fbe2b-1793-4218-be96-7e5bb6cfa7d8.png)

**Comment by anton-petrov** [comment]
Just uploaded a new organization avatar just for testing to see how it will look.
