### ISSUE TITLE
`pyenv install 3.9-dev` failing in macOS ventura 13.3.1 (M1): "call to undeclared function 'openpty'"

### ISSUE THREAD

**Issue by Gunner17** [pyenv/pyenv#2679]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information : MacOS Ventura 13.3.1 (22E261
- [x] OS architecture : AArch64
- [x] pyenv version: Python-3.9-dev
- [x] Python version: python 3.9
- [x] C Compiler information (e.g. gcc 7.3): 
`$ gcc -v`
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] Please attach the debug trace of the failing command as a gist: Attaching the log from the command: `env PYENV_DEBUG=1 pyenv install -v 3.9-dev 2>&1 | tee trace.log`
[pyenv_trace_log.txt](https://github.com/pyenv/pyenv/files/11230449/pyenv_trace_log.txt)

**Actual Logs:**
[actual_pyenv_install_logs.txt](https://github.com/pyenv/pyenv/files/11230495/actual_pyenv_install_logs.txt)

**Comment by native-api** [comment]
Make sure you're using Apple's stock CLang and not the Homebrew version.

Please also attach `config.log` as per the issue template.

**Comment by Gunner17** [comment]
Attaching config.log from /Users/<username>/.pyenv/sources/3.9-dev/Python-3.9-dev 
[config.log](https://github.com/pyenv/pyenv/files/11247906/config.log)

This file was generated after running the below command:
`env PYENV_DEBUG=1 pyenv install -f -k -v 3.9-dev 2>&1 | tee trace.log`

**Comment by native-api** [comment]
The immediate cause is that the `openpty` function is not found -- despite the fact it's successfully detected by Configure.

It's supposed to be located in `util.h` within a MacOS SDK and in MacOS 13.1 SDK I have here it's defined there without any conditions.
So something must be wrong with your SDK, or there are new changes in your version of SDK that I don't have, or there may be other files elsewhere overriding the `util.h`.

Try installing XCode command-line tools: `xcode-select --install` -- since I see that you're using XCode rather than them.

If that doesn't help, check if you have `util.h` anywhere else.

If not, please attach the contents of `util.h` in your active MacOS SDK (under the path that's shown in `config.log` or the build log under a `-I` compiler option. E.g. for me, it's `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`).

**Comment by native-api** [comment]
@bensh your is a different issue, most probably https://github.com/pyenv/pyenv/wiki/Common-build-problems#on-apple-silicon-when-building-for-arm64-a-dependency-is-present-in-x64-homebrew-but-not-arm64-homebrew

**Comment by bensh** [comment]
> 

You're absolutely right!! 

Cloned my HDD from my old Mac with old version of brew. 
Followed this, pyenv and python 3.11.3 now installs fine.

https://earthly.dev/blog/homebrew-on-m1/
