### ISSUE TITLE
Rehashing is not applied after pip install in venv

### ISSUE THREAD

**Issue by hylowaker** [pyenv/pyenv#2914]
### Description
- Platform information: macOS Sonoma 14.2.1
- OS architecture: amd64
- pyenv version: 2.3.36
- Python version: 3.10.12

**Steps to Reproduce**

```
$ python -m venv venv
$ source venv/bin/activate
(venv) $ pip install ansible==5.7.1
...
(venv) $ command -v ansible
/Users/jaeheunghan/Desktop/MM2/venv/bin/ansible
(venv) $ ansible --version
ansible [core 2.14.6]    ⬅️⬅️ No, this is not what I installed.
...
(venv) $ command -v ansible
/Users/jaeheunghan/.pyenv/shims/ansible    ⬅️⬅️ What??
(venv) $ pyenv rehash
(venv) $ ansible --version 
ansible [core 2.12.10]    ⬅️⬅️ Correct one.
...
(venv) $ command -v ansible
/Users/jaeheunghan/Desktop/MM2/venv/bin/ansible
```

**Full terminal output**

[terminal.txt](https://github.com/pyenv/pyenv/files/14433495/terminal.txt)

**Note**

No problem occurs if I remove `eval "$(pyenv init -)"` line from my `.zshrc` file and manually executes Python by `~/.pyenv/shims/python`.

**Comment by native-api** [comment]
Pyenv cannot intercept command invocations if you activate a virtualenv with `source <...>/activate` (that's because it prepends its location to PATH, overriding shims).
You need to rather create it with Pyenv-Virtualenv and either activate with it as well or select like a regular Pyenv-managed version (see https://github.com/pyenv/pyenv-virtualenv?tab=readme-ov-file#usage).
