### ISSUE TITLE
Consider support for uv in `pip-rehash`

### ISSUE THREAD

**Issue by zanieb** [pyenv/pyenv#2979]
Hi! 

I'm an engineer over at Astral and we got this report that packages installed by uv did not have their commands available in environments managed with pyenv: https://github.com/astral-sh/uv/issues/1586

Someone did some sleuthing and identified that it's because there's no [`pip-rehash` script](https://github.com/pyenv/pyenv/tree/master/pyenv.d/exec/pip-rehash) for `uv` (as there is for `pip`).

Would you be willing to accept addition of one? Are there caveats here I don't understand?

**Comment by native-api** [comment]
You can add one via a plugin.
Pyenv is designed to be easily extendable: most things that you can put under `$PYENV_ROOT/<whatever>` you can also put under `$PYENV_ROOT/plugins/your_plugin_name/<whatever>`.

**Comment by native-api** [comment]
Not sure if the tool is common enough to be considered a part of a standard Python installation yet.
I mean, we even have Virtualenv support in a plugin!

**Comment by native-api** [comment]
If/when the tool becomes common enough, we can include it into the list of plugins installed by the installer.

**Comment by zanieb** [comment]
Sounds good thanks for the replies and context :)

**Comment by ddelange** [comment]
For anyone finding this later, here is the plugin that was suggested. Two files, no dependencies beyond pyenv itself.

`$(pyenv root)/plugins/pyenv-uv-rehash/etc/pyenv.d/exec/uv-rehash.bash`:

```bash
PYENV_UV_REHASH_ROOT="${BASH_SOURCE[0]%/*}/uv-rehash"
PYENV_REHASH_COMMAND="${PYENV_COMMAND##*/}"

if [ -x "${PYENV_UV_REHASH_ROOT}/${PYENV_REHASH_COMMAND}" ]; then
  PYENV_COMMAND_PATH="${PYENV_UV_REHASH_ROOT}/${PYENV_REHASH_COMMAND}"
  PYENV_BIN_PATH="${PYENV_UV_REHASH_ROOT}"
  export PYENV_REHASH_REAL_COMMAND="${PYENV_REHASH_COMMAND}"
fi
```

`$(pyenv root)/plugins/pyenv-uv-rehash/etc/pyenv.d/exec/uv-rehash/uv`, executable:

```bash
#!/usr/bin/env bash

set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Remove this directory from PATH to avoid infinite loops in `pyenv-which` (#146)
_PATH=":${PATH}:"
_HERE="$(dirname "${BASH_SOURCE[0]}")"
_PATH="${_PATH//:${_HERE}:/:}"
_PATH="${_PATH#:}"
_PATH="${_PATH%:}"
PATH="${_PATH}"

PYENV_COMMAND_PATH="$(pyenv-which "${PYENV_REHASH_REAL_COMMAND}")"
PYENV_BIN_PATH="${PYENV_COMMAND_PATH%/*}"

export PATH="${PYENV_BIN_PATH}:${PATH}"

STATUS=0
"$PYENV_COMMAND_PATH" "$@" || STATUS="$?"

# Run `pyenv-rehash` after a successful installation.
if [ "$STATUS" == "0" ]; then
  for uvarg in "$@"; do
    case ${uvarg} in
    "install" | "uninstall" ) pyenv-rehash ; break;;
    esac
  done
fi

exit "$STATUS"
```

This is `pyenv.d/exec/pip-rehash` with `pip` swapped for `uv`.
`pyenv hooks exec` should list `uv-rehash.bash` once the files are in place.

Dropping the same two files under `$(pyenv root)/pyenv.d/exec/` works too, since that path is on `PYENV_HOOK_PATH` already.

One caveat: `uv` has to resolve through a pyenv shim for the hook to fire.
A `uv` from the Astral installer at `~/.local/bin/uv` never goes through `pyenv exec`.
Installing uv into the pyenv environment is what makes it work.

Verified on pyenv 2.8.1 with pyenv-virtualenv 1.4.0.
Deleting a shim and running `uv pip install <pkg>` brings it back on its own, `uv pip uninstall` removes it again, and non-mutating commands like `uv --version` skip the rehash.

Also posted on the uv side at https://github.com/astral-sh/uv/issues/4130#issuecomment-5742196557

**Comment by native-api** [comment]
You can post this plugin to https://github.com/pyenv/pyenv/wiki/Plugins
