### ISSUE TITLE
brew doctor reports warnings after installing pyenv.

### ISSUE THREAD

**Issue by maaru** [pyenv/pyenv#42]
After installing pyenv using the Homebrew, brew doctor reports warning.

```
$ brew doctor
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

    /Users/maaru/.pyenv/shims/python-config
    /Users/maaru/.pyenv/shims/python2-config
    /Users/maaru/.pyenv/shims/python2.7-config
```

Is this a normal situation?

**Comment by robertleeblairjr** [comment]
> Because `pyenv` is using `shims` to inject commands into `$PATH`, this is not avoidable in `pyenv`.

I know this is a very old issue and had been closed. I was going to open a new one for this because 'rbenv' which uses shims and the project that 'pyenv' is based upon doesn't have a problem with brew doctor. Could it be just because of the naming convention used in the shim directory which is "python-config"? 'rbenv' doesn't use this naming for its shim configurations. I would think that moving to a simple "python" instead of "python-config" would probably solve this problem. What do you think?
