### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mcandre** [pyenv/pyenv#62]
Could we port pyenv to Windows?

I imagine `.bat` scripts could mimic the behavior of the `.sh` scripts.

---
_A note from the pyenv maintainers:_

`pyenv` does not currently support Windows outside of the Windows Subsystem for Linux (WSL). [We have no current plans to support Windows in the future.](https://github.com/pyenv/pyenv/issues/62#issuecomment-487418864)

@kirankotari has helpfully provided a port of `pyenv` for windows called [`pyenv-win`](https://github.com/pyenv-win/pyenv-win), which hopefully will meet the needs of windows users.

**Comment by ftomassetti** [comment]
I also do not use Windows but users of my open-source projects do, so it would be great to have support for pyenv on Windows. I would use it together to AppVeyor to test my software on Windows without having Windows

**Comment by chriskrycho** [comment]
As others have commented: Windows development may not be awesome, but a lot of us do use Windows for work because we have to (and some people just love it). I understand that you don't want to spend the time on it yourself, of course. Assuming someone could write Windows-friendly scripting, though, would you potentially accept PRs for it?

**Comment by autolife** [comment]
you can try pywin[https://github.com/davidmarble/pywin]

**Comment by blueyed** [comment]
Also anyenv might be an option: https://github.com/mislav/anyenv, assuming that Go on Windows works well.
Anyenv is supposed to be the successor of rbenv, pyenv etc.

**Comment by edbordin** [comment]
I'm interested in getting this working on Windows in my spare time. A couple of things I wouldn't mind feedback on though:
1. `pyenv install` works by compiling python from source. Building python on Windows isn't actually too hard (I just built Python 3.6 with no issues). But getting a comprehensive set of build tools installed [looks like a pain](https://wiki.python.org/moin/WindowsCompilers). To build all versions of python 2.x.x and 3.x.x you need VC++ 9.0, 10.0 and 14.0 and they all have their own fairly convoluted installation steps. So, perhaps an easier method would just be to download the official Windows builds. Is anyone heavily relying on adding custom build flags/patches etc. to their interpreter?

2. Given how many bash scripts have been written, the easiest approach would probably be to patch pyenv so that it works in MSYS bash on Windows. I think this would still be useful, given that once an environment has been created it is relatively self-contained. Anyone see any obvious problems with this approach?

**Comment by blueyed** [comment]
@edbordin 
Maybe it is easier to look into https://github.com/mislav/anyenv for this?  It has not been updated in a while, but was meant to replace rbenv/pyenv etc.

**Comment by edbordin** [comment]
@blueyed Yeah, I wasn't too sure about that project because (a) it seems inactive, and (b) it doesn't seem to implement the `pyenv install` command at all atm...

**Comment by slidenerd** [comment]
@yyuu  i have a mac and windows machine and I would like to know how to run this on Windows since I use both for testing so that sorta comment s gonna get a lot of dislikes even on GitHub

**Comment by raiderrobert** [comment]
Came here to see if this ticket has possibly changed or had an update to it. Of course, I'm disappointed to not see it, but the tone in this thread is totally wrong.

The griping and down-thumbing you're doing here has been enough to drive other maintainers away from other projects. This vast majority of this project has been down by 5 people. And they've likely done so to solve their own particular problem, and now we all are benefiting from them doing the extra work of sharing it--this is not a light task.

I doubt any of them get paid to do this, and even if they are, they're not getting paid by you all. Just being a user doesn't entitle you to features much less one as huge as this.

So thanks maintainers! We really appreciate all that you do on this project for the community.

**Comment by edbordin** [comment]
@raiderrobert Most of the down-thumbing was on the original response to the feature request which quite frankly had an arrogant and dismissive tone. Of course the maintainers owe nothing to anybody, but if you address people in that manner you cannot reasonably expect zero backlash. Being generous doesn't give you unlimited license to be a jerk to everybody.

To me, the majority of the responses here have just been constructive feedback on why people would find this feature useful. Whether it is feasible given how much time the devs have is a totally different story - perhaps making that point would have a been a better way to close the issue.

Having said all that, I'd also like to thank the maintainers for a really useful tool.

**Comment by flying-sausages** [comment]
If you're still trying to find out how to get pyenv running on Windows, you might want to read up a little about the Windows Subsystem for Linux

**Comment by mcandre** [comment]
> the Windows Subsystem for Linux

Nope.

**Comment by Almenon** [comment]
Unfortunately it looks like automatic switching of virtual environments offered by pyenv-virtualenv plugin is simply not possible with windows cmd :(

https://superuser.com/questions/933527/windows-run-script-on-cd

**Comment by cicorias** [comment]
work fine in WSL on Windows 10.  So, I kinda agree, nothing to do here.

**Comment by Almenon** [comment]
It didn't work on wsl for me @cicorias.  How did you install it?

**Comment by cicorias** [comment]
I’ve been using Wlinux from the App Store. What distribution are you using and what errors? There probably missing packages that wlinux adds.

**Comment by Almenon** [comment]
When installing python I get 

> configure: error: C compiler cannot create executables

```
almenon@DESKTOP-ANS3L8S:~/misc$ pyenv install 3.6.4
Downloading Python-3.6.4.tar.xz...
-> https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
Installing Python-3.6.4...
python-build: use readline from homebrew

BUILD FAILED (Ubuntu 18.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20190204202737.1377
Results logged to /tmp/python-build.20190204202737.1377.log

Last 10 log lines:
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20190204202737.1377/Python-3.6.4':
configure: error: C compiler cannot create executables
See `config.log' for more details
almenon@DESKTOP-ANS3L8S:~/misc$ which gcc
/home/linuxbrew/.linuxbrew/bin/gcc
almenon@DESKTOP-ANS3L8S:~/misc$ gcc -v
Reading specs from /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --with-isl=/home/linuxbrew/.linuxbrew/opt/isl@0.18 --with-bugurl=https://github.com/Linuxbrew/homebrew-core/issues --prefix=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/home/linuxbrew/.linuxbrew/opt/gmp --with-mpfr=/home/linuxbrew/.linuxbrew/opt/mpfr --with-mpc=/home/linuxbrew/.linuxbrew/opt/libmpc --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.5.0_4' --with-boot-ldflags='-static-libstdc++ -static-libgcc ' --disable-nls --disable-multilib
Thread model: posix
gcc version 5.5.0 (Homebrew gcc 5.5.0_4)
```

**Comment by kirankotari** [comment]
> I'm no longer using Windows. I don't like to waste my time with such thing.

On the inspiration of this thread I have ported pyenv for windows which contains basic features of pyenv. Link: [pyenv-win](https://github.com/pyenv-win/pyenv-win)

**Comment by skqr** [comment]
@yyuu why would you close the issue? Even if you don't use Windows, a lot of the users of `pyenv` do. I do. Anybody else in the GitHub community could have contributed a PR with Windows support.

Please consider your users a bit more in the future.

And thank you @kirankotari for your port!

**Comment by joshfriend** [comment]
> Even if you don't use Windows, a lot of the users of `pyenv` do.

True, but I don't own, use, or have access to Windows PCs, and I think this is likely true of the other maintainers. `rbenv` and `nodenv` also lack Windows support outside WSL and have expressed resistance to add support as well. 

> Anybody else in the GitHub community could have contributed a PR with Windows support.

Absolutely, which is why we have `pyenv-win` now. Thanks to @kirankotari for that amazing contribution to the community :smile:

> Please consider your users a bit more in the future.

The earlier comments by @raiderrobert and @edbordin are spot on. I agree that the original reply to this issue was rude, but we aren't obligated to support windows just because people ask. I know that's disappointing for all of you windows users, but we just can't support it at this time.

I'll add a section to the top comment with a link to `pyenv-win` and this comment so that the status on windows support is more clear and visible in the future.

**Comment by altendky** [comment]
Once pyenv-win is considered to be working well for many people it may be worth a mention in the readme even?  But I do wonder how much there really is to share between the two what with them both trying to use native scripting languages which makes them inherently separate code even if they were to do similar things.  I suppose maybe a lot of cli-level testing could be shared and would encourage them to retain similar interfaces?

**Comment by joshfriend** [comment]
> it may be worth a mention in the readme even?

Sure, I just added a note :+1:

The idea for a shared "interface compatibility test suite" is great, I'm always in favor of more testing, I just don't have the time for that currently.

**Comment by edbordin** [comment]
@flying-sausages the main reason I couldn't use WSL for python was the lack of CUDA support, so having a native Windows option is great! On my current project I've giving Anaconda a try since they allow you to specify the interpreter version on all platforms and they also make things like numpy+mkl easier on Windows. The conda `environment.yml` doesn't quite have as many of the features I'd like compared to Pipenv+pyenv though (particularly, no lock files), so this new pyenv-win project is still nice to have as an option 😁

**Comment by kirankotari** [comment]
thanks guys for the support. @altendky thanks for bringing the point. My initial intention is to fork the pyevn itself to support windows, I love the pyenvs' the way today they are, but the differences I have encountered were massive changes which I am listing below. Help me to support as more features from `pyenv` to `pyenv-win` for windows, including testing.

- __Installation__:- unlike linux and mac, we does not have zip/tar file for installation
- __Installation in background__:- we does not have fully background installation for windows, trying a lot but due to policy of authentication minimum UI access is required. I have seen in most of the company laptops have this policy of authentication before installing.  I am coming up with new ways to support complete background options for those doesn't have authentication policies i.e. personal laptops.
- __pip install support__:- there was a slight difference on packaging to support via pip install, that's the reason you will see slight difference in packaging of `pyenv` and `pyenv-win`

Lot more feature yet to come. I have listed the new feature at [pyenv-win/projects](https://github.com/pyenv-win/pyenv-win/projects/1) feel free to support or add more feature expectations in __pyenv-win__ we will try our best to support them.

**Comment by lvxiaoxin** [comment]
Thanks @kirankotari and others who contributed to the [pyenv-win](https://github.com/pyenv-win/pyenv-win) project. 

I just change developing work from Mac to Windows so I really need tools like this. I use it with virtualenv and this combination can handle many basic use of developing work. Thanks again!

**Comment by anurag-oss** [comment]
> 
> 
> @flying-sausages the main reason I couldn't use WSL for python was the lack of CUDA support, so having a native Windows option is great! On my current project I've giving Anaconda a try since they allow you to specify the interpreter version on all platforms and they also make things like numpy+mkl easier on Windows. The conda `environment.yml` doesn't quite have as many of the features I'd like compared to Pipenv+pyenv though (particularly, no lock files), so this new pyenv-win project is still nice to have as an option 😁

CUDA support is coming up in WSL2 as per the latest [announcement](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gpu)
