### ISSUE TITLE
[pybuild] Attempts to mkdir where I do not have permissions because of LDFLAGS

### ISSUE THREAD

**Issue by multimeric** [pyenv/pyenv#732]
I had an issue running pybuild on a system where I do not have root access. On this system, the LDFLAGS variable included a path in /usr that did not exist (e.g. `LDFLAGS=/usr/foobar`). I realise this is unusual, but normally setting an environment variable to an invalid path is just ignored.

However, in my case, the [build_package_ldflags_dirs](https://github.com/yyuu/pyenv/blob/e198792df2aff2e061ab9dd461beea681dde564f/plugins/python-build/bin/python-build#L1412) function attempted to create this directoy with `mkdir -p`, causing an invalid permission error and crashing (since I don't have write access to /usr).

Can you explain why we need to ensure all the LDFLAGS directories exist? Ideally pybuild should not need to write anywhere outside of its installation directory, surely? If someone explains the rationale I'm happy to write a PR to fix this.
##

**Comment by yyuu** [comment]
I guess it was just imported from https://github.com/rbenv/ruby-build as is. Honestly speaking I couldn't remember if removing the call of {{build_package_ldflags_dirs}} breaks CPython build or not 😵 Because python-build doesn't care so much about contents of `LDFLAGS`, I don't have strong preference about the behavor; however I don't want to just change current code without some evidence.

As a tentative workaround, both of the following could work.

1. Create your custom build definitions with modifying default build definitions bundled with `python-build`
  * just removing `build_package_ldflags_dirs` could work https://github.com/yyuu/pyenv/blob/1dee022342d5f88f4d72fa686af7878a2bdcc222/plugins/python-build/share/python-build/3.5.2#L4-L8
  * `cp $(pyenv root)/plugins/python-build/share/python-build/3.5.2 ./3.5.2 && sed -i 's/ldflags_dirs//' 3.5.2 && pyenv install -v ./3.5.2`
2. Create new hook plugin for `pyenv install` to remove `LDFLAGS` entries with non-existing directories

**Comment by chrahunt** [comment]
The commit in ruby-build that introduced this (https://github.com/rbenv/ruby-build/commit/50bf60f9c2510fbee7f111046e97fe8bf9e66472) indicates that it was an explicit action by the Ruby configure script that required it. If there's no such check in Python then we can probably remove it.

**Comment by ckreon** [comment]
This is still an issue, and ironically conflicts with both homebrew and zlib's recommendations of setting the `LDFLAGS` variable.

Following those instructions breaks the install process because it tries to create a directory in `/usr/local/opt`.

But if you don't set the LDFLAGS variable, at least in my case (running Debian on WSL1), the install fails because it then can't find zlib.

I'm not sure what changed between my previous WSL setup and this one (I did a clean install recently), because pyenv install worked fine for me previously, and it was a very similar setup with identical profile/exports/inits/etc.

**Comment by MBarrows20** [comment]
@ckreon - Still an issue for me as well on a fresh install on WSL1. My brand new device prevents me from upgrading to Windows 2004 so I'm stuck on 1909 with WSL1 for now. Running into the exact same conflict with Zlib and homebrew.

**Comment by MBarrows20** [comment]
@ckreon  - I have posted what I believe to be the appropriate install steps for Debian WSL1 to your bounty source request. Let me know if you are still experiencing issues or have trouble viewing the code steps.

**Comment by native-api** [comment]
`build_package_ldflags_dirs` is no longer used anywhere so this should be fixed.

**Comment by native-api** [comment]
Please check out the PR.
