### ISSUE TITLE
pyenv cause vim plugin error

### ISSUE THREAD

**Issue by nicozhang** [pyenv/pyenv#746]
In my directory, I use pyenv to set the local python version to 3.5.2. When I use vim to edit .py file and save the file, the plugin syntastic will raise an error:

`Traceback (most recent call last):
  File "/home/deploy/.vim/bundle/syntastic/syntax_checkers/python/compile.py", line 11, in <module>
    compile(open(argv[1]).read(), argv[1], 'exec', 0, 1)
  File "/home/deploy/.pyenv/versions/3.5.2/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1038: ordinal not in range(128)`

There are Chinese Characters in my code. 
I know this is cause by encoding and the vim  env is changed from py2 to py3, but i don't know how to solve this problem.

**Comment by chrahunt** [comment]
Hello. If this issue is still impacting you please report it to [vim-syntastic/syntastic](https://github.com/vim-syntastic/syntastic), where they can direct you on how to retrieve debug logs. From more recent threads like vim-syntastic/syntastic#1612 it seems like they should be both Python 2 and 3 compatible. You can also check out the help with `:help syntastic-checkers`.
