### ISSUE TITLE
pyenv-exec should not change PATH variable unless CPython is used.

### ISSUE THREAD

**Issue by kota65535** [pyenv/pyenv#789]
For the fix of [this issue](https://github.com/yyuu/pyenv/issues/98), `pyenv-exec` becomes to add the system python path (usually `/usr/bin`) to the head of PATH environment variable before running python. But this introduces another problem for me.

## Symptom

IntelliJ IDEA has the function to launch another terminal inside it. I realized that the PATH variable of the IDEA terminal is different from the one of the terminal that is normally launched.
It has `/usr/bin` at the head of the PATH, that means `/usr/bin` is the higher priority than `/usr/local/bin` to search executables.

The cause of this problem is as follows:

1. IntelliJ IDEA launches by python script, so it is also run through `pyenv-exec`.
2. `pyenv-exec` add `/usr/bin` to the head of PATH.
3. IntelliJ IDEA terminal inherits the PATH from IDEA itself.

## Solution

I think there are two solutions. 

1. Change the position of `/usr/bin` inserted to the tail of PATH variable.
2. Do not change PATH variable unless CPython is used.

Which is better solutions? Is there another way to resolve this?

**Comment by yyuu** [comment]
I've never used IntelliJ for Python projects.... Are you running on macOS?

Honestly speaking, it is kinda misconfiguration of shell which was invoked from IntelliJ's terminal. I suspect changing the position of `/usr/bin` in `PATH` conditionally corrupts something. At present I'm not confident enough though. Anyway will try running IntelliJ when I get a chance.

**Comment by kota65535** [comment]
Sorry, I'm not talking about Python project.  **IntelliJ IDEA uses a python script when launching itself**.  
If you install IntelliJ IDEA, you can see `/usr/local/bin/idea` is a python script that launches IntelliJ IDEA.  
So in the environment where pyenv installed, IntelliJ IDEA inevitably suffers the change of PATH by pyenv-exec...

**Comment by yyuu** [comment]
I guess you launched IntelliJ with setting pyenv version as `system`. That must be the reason why `/usr/bin` was at the top of the `PATH`.

> 1. Change the position of /usr/bin inserted to the tail of PATH variable.
> 1. Do not change PATH variable unless CPython is used.

I think both two will reintroduce the issue of #98. If so, I think it's better to keep current code since it's for `virtualenv`. Umm 😕

**Comment by yyuu** [comment]
I guess some of the following can be a workaround for the issue. Please let me know if there's some other ways.

* Modify IntelliJ's launcher script (`/usr/local/bin/idea`?) to start IntelliJ not via pyenv's shim script
  * I guess its shebang is configured as `#!/usr/bin/env python`
  * You can avoid pyenv's shim to intercept the execution by replacing the line by `#!/usr/bin/python` 
* Modify `$PATH` ordering in shell's configuration file (e.g. `.bashrc`, `.zshrc`) if it is an interactive shell running in IntelliJ
  * It seems that shell running inside IntelliJ has `DOTDIR=/Applications/IntelliJ IDEA CE.app/Contents/plugins/terminal` in environment

**Comment by davidshepherd7** [comment]
Hi, I think this issue is currently breaking emacs lisp version management on Travis. The problem is this:

* Most (or all) emacs lisp package `.travis.yml` files use `$PATH` to manage the version of emacs to test with.
* A program called `cask` is used for package version management during development (think npm but for emacs).
* `cask` is written in emacs lisp, but is started by a small python wrapper.
* On Travis python scripts seem to be run through `pyenv`.
* `pyenv` adds `/usr/bin` to the *front* of `$PATH`, which overrules anything anyone else has set up!

The result is that the system version of emacs from `/usr/bin` is always used.

I'd be very surprised that this hasn't broken anything else. Modifying the path is a fairly common way to control which version of a program is run, and prepending `/usr/bin` to `$PATH` is likely to break anything that relies on that.

I'm not particularly familiar with the Travis internals, and I'd never heard of pyenv before today, so I don't really know where this bug belongs. Do you think it's an issue that could be fixed here?

Also is there any way to disable pyenv that could be used in a `.travis.yml` file? Perhaps setting an environment variable?

[Link to the cask issue.](https://github.com/cask/cask/issues/399)

**Comment by eregon** [comment]
I also met this issue on TravisCI, which is very confusing to debug, as only the `python` process and its subprocess have the wrong `$PATH` with `/usr/bin` prepended.

Maybe `pyenv` can avoid changing `PATH` if the `python` executable is already the right one according to `which python`? Or special-case `/usr/bin`?

**Comment by blueyed** [comment]
See https://github.com/pyenv/pyenv/pull/1169.

**Comment by mbdevpl** [comment]
(If this comment should be moved to another issue, or if it's a new issue, please let me know.)

I think I might've just stumbled into this issue when using subprocess.run() from pyenv-installed Python 3.6 to launch a "Python 2 only" script `my_py2_script.py` with a shebang like this:
```
#!/usr/bin/env python
print 'hello'
```

In pyenv, I have my versions setup as follows:
```
$ pyenv global
2.7.15
3.6.8
```

Of course, launching the script directly from commandline via `./my_py2_script.py` works because default python is Python 2, but when runnning `my_py3_script.py` written like this
```
#!/usr/bin/env python3
import subprocess
subprocess.run(['./my_py2_script.py'])
```

Output after `$ ./my_py3_script.py`:
```
$ ./my_py3_script.py
  File "./my_py2_script.py", line 3
    print 'hello'
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello')?
```
Output after `/usr/bin/python3 my_py3_script.py`:
```
hello
```

It can be seen also via `shutil` module, like this:
```
$ /usr/bin/python3 -c "import shutil; print(shutil.which('python'))"
~/.pyenv/shims/python
$ python3 -c "import shutil; print(shutil.which('python'))"
~/.pyenv/versions/3.6.8/bin/python
```

This happens because pyenv is prepending paths to `PATH` envvar:
```
$ python3 -c "import os, shutil; print(os.environ['PATH'])"
~/.pyenv/versions/3.6.8/bin:~/.pyenv/libexec:~/.pyenv/plugins/python-build/bin:(expected value of $PATH)
$ echo $PATH
(expected value of $PATH)
```

BTW, messing with user's PATH this way may lead to running not only wrong version of interpreter, but also wrong versions of installed Python-based software e.g. if pylint or ipython or ipdb.

```
$ pylint --version
Using config file ~/.pylintrc
pylint 1.9.4, 
astroid 1.6.5
Python 2.7.15 (default, Mar 16 2019, 20:25:58)  # correct!
[GCC 8.2.0]
$ python3 -c "import shutil; print(shutil.which('pylint'))"
~/.pyenv/versions/3.6.8/bin/pylint  # wrong!
```

I believe python interpreter launched via pyenv should respect global version preferences and not force all subprocesses into some unexpected environment. Or are those needed for some reason? If the paths are needed, maybe they can be appended instead of being prepended so they don't mess with the environment that much?

**Comment by mbdevpl** [comment]
And I think this issue is possibly related to #1300

**Comment by eregon** [comment]
I got this again today, and found there are at least 4 issues on pyenv bug tracker about this (linked from #1169).
It's highly unexpected that `/usr/bin` can be prepended in `PATH`, because it breaks every software which has binaries both in `/usr/bin` and some other directory in PATH earlier than `/usr/bin`.

A typical example is `opt` which on TravisCI is both in /usr/bin and /usr/local/clang-7.0.0/bin/opt.

**Comment by eregon** [comment]
One workaround (at least for TravisCI) to avoid `pyenv` to prepend `/usr/bin` to `PATH` is to use a non-system version like `pyenv local 2.7.15`.
It's quite suboptimal that the system python cannot be used with pyenv without breaking other software though.

**Comment by JustAnotherArchivist** [comment]
I'm running into the same issue on Travis CI with a Ruby/Python project with `language: ruby`. Specifically, `bundle exec ruby ...` processes fail to find the installed gems when executed through Python in my case. Switching to a non-system Python – fortunately, Travis CI has [a few Python versions](https://docs.travis-ci.com/user/reference/xenial/#python-support) preinstalled through pyenv – works for me as well, but it would be great if this bug could be fixed.

One thing I'm missing in this issue so far is an explanation why this path prepending is necessary at all. Shouldn't the shims handle the paths anyway?
