### ISSUE TITLE
pyenv does not run using sudo

### ISSUE THREAD

**Issue by thedrow** [pyenv/pyenv#79]
I'm using pyenv on Ubuntu 12.04 and I have to use sudo to install python versions, however pyenv is missing when using sudo.

**Comment by achimnol** [comment]
Being coincided with https://github.com/docker/docker/issues/7198 and docker-py, I just ran into a situation that requires my pyenv environment to run as root.

**Comment by bhyde** [comment]
Root is a traditionalist.  His shell is /bin/sh.   That doesn't notice ~/.bash_profile.  ~/.bash_profile which is where pyenv's clever plumbing is typically established.  This the root cause of this issue, correct?

Often, /bin/sh is linked to /bin/bash.  When invoked that way you have a shell which is crafted to backward compatible so all the traditional scripts still work, but it is also chock full of extensions so a bash scripts usually work.

I have no idea if pyenv is intentionally (or unintentionally) crafted in an analogously compatible manner.  

But, for me, arranging to source the pyenv's setup in root's /bin/sh init files seems to work.

Thoughts?

**Comment by kuuling** [comment]
add any necessary path (e.g.,` /app/pyenv/shims`) to `secure_path`, and it will be passed to `sudo` commands.
`Defaults    secure_path = /app/pyenv/shims:/sbin:/bin:/usr/sbin:/usr/bin`
more: [define-path-environment-variable-sudo-commands](http://ask.xmodulo.com/define-path-environment-variable-sudo-commands.html)

**Comment by bsolomon1124** [comment]
For those still having trouble:

Related to setting of `secure_path` via `visudo`, there is also the option to let root (partially) inherit the environment of the calling user via `env`.

One place where I ran into this issue was that running a server on port 80 requires root.  A Django application where pyenv and the application are installed/built/owned by a non-root user will otherwise give `sudo ./manage.py runserver 0.0.0.0:80` trouble because `./manage.py` wants to find the environment Python and libraries.

To that end, you can run something like:

```bash
# All commands here except last assumed to be run by non-root user
pyenv install -v 3.7.4
pyenv global 3.7.4
python3 -m venv app-dev
source ./app-dev/bin/activate
python -m pip install -U django pip
django-admin startproject proj && cd proj
django-admin startapp app
# edit views.py, urls.py, etc
./manage.py makemigrations && ./manage.py migrate

sudo env "PATH=$PATH VIRTUAL_ENV=$VIRTUAL_ENV" ./manage.py runserver 0.0.0.0:80
```

**Comment by leopoletti** [comment]
Thank you @bsolomon1124 !

It would be nice to add your solution with `sudo env "PATH=$PATH VIRTUAL_ENV=$VIRTUAL_ENV" ` in the trouble shooting page
