### ISSUE TITLE
Micropython Support

### ISSUE THREAD

**Issue by jamesstidard** [pyenv/pyenv#790]
Hi,

I'd like to see the micropython project as a supported implementation, if that's possible. I'm not sure how you go about supporting Python implementations; if the onus would be on this project or the micropython project to register itself (like how pip works). I can open a ticket with the micropython project if that's the case.

Thanks

**Comment by joshfriend** [comment]
Running micropython on x86/x64 systems [is actually possible](https://github.com/micropython/micropython#the-unix-version).

**Comment by xsteadfastx** [comment]
This would be great. I'm only a pyenv user and no developer and i tried to read the build script. just spend some minutes with it... and couldnt get it working because i couldnt find out how to change the build dir after i cloned the git repo. there is also no `configure` script and `make` needs to be run on two directories.

**Comment by scop** [comment]
See #920
