### ISSUE TITLE
Upgrading via Homebrew in Mac does not work as expected

### ISSUE THREAD

**Issue by MathiasSM** [pyenv/pyenv#885]
All versions and shims are kept in, say, the old 1.0.8 version folder, while a new folder 1.0.9 is created (with the new pyenv being used), no pythons or shims in there. Should be upgrading by git pulling but it's not. 

Should I put this in formulae repo?

**Comment by tjsoftworks** [comment]
I have seen this as an ongoing issue a number of times. I keep my homebrew up-to-date and clean with each login.
>brew update
>brew upgrade
>brew cleanup
>brew prune
as part of the my terminal startup script. What happen is all of my prior pyenv downloads get wiped out as pyenv rolls thru it's development.

How should no maintain the pyenv environment and it's downloaded versions if the pyenv upgrade process via brew upgrade is not bring these along at the time of upgrade?

**Comment by joshfriend** [comment]
Updating Homebrew automatically with such a process is a very bad idea. Things can (and will, as seen above) break unexpectedly or in annoying ways. Unfortunately, I don't know yet how to preserve installed python versions during `brew upgrade pyenv`. I usually recommend [installing pyenv via `git clone`
](https://github.com/pyenv/pyenv#basic-github-checkout) anyways.

**Comment by MathiasSM** [comment]
If the documentation says installing pyenv via homebrew (and updating via it) is an option, it should work at  least as expected, I believe... In any case, couldn't this be solved by putting some symlinks to the python binaries and shims? (at least I did this manually and works as usual) I still can't understand why "git pulling" as upgrading mechanism is not a thing with homebrew. I just ask for the documentation to explicitly state the fact (and maybe state a solution)

**Comment by FrederickGeek8** [comment]
I know this is an old conversation, but I believe that its related to #815. I think that it wouldn't be unreasonable to perhaps integrate, by default, the solution outlined in that issue. Quoting their solution:

> I think, the problem is that pyenv stores installed versions under ./versions relative path. When brew upgrades, it completely replaces pyenv directory, which means it removes the contents of ./versions too.
> 
> I've explicitly set `PYENV_ROOT` variable to `~/.pyenv`, in order to store everything under `~/.pyenv/versions` now. I then tried reinstalling pyenv and everything seems to work properly this time. Just make sure to export `PYENV_ROOT` before calling `pyenv init`. I also manually expanded `~` to `/Users/usrname` just to be safe.
> 
> @naglalakk hope this helps!

It would be ideal that perhaps through a build parameter passed by the Homebrew installation, that pyenv by default stores Python versions in a separate directory. The current upgrade method through Homebrew is _extremely_ frustrating since I don't know what packages I had installed (some of which were manual installations), and so I'm going to have to rebuild and reinstall all Python packages I had previously for my projects.

**Comment by omdv** [comment]
I just lost my environments by running an automated brew upgrade script - second time in about a year, my fault really about running in a same issue twice. Anyhow, according to comments above it appears that installing with `homebrew` is not recommended, because it will break when one eventually runs `upgrade` and `cleanup`. I agree with @MathiasSM in that homebrew should not be recommended as a default installation mechanism or at least have a clear warning about this behavior.

**Comment by robgyiv** [comment]
After upgrading with `brew`, I had the following error running (eg)`tmuxp`:

```bash
$ tmuxp load mysession                                                                                                                                                                                                                                                          09:43:44
/Users/robgyiv/.pyenv/shims/tmuxp: line 21: /usr/local/Cellar/pyenv/1.2.16/libexec/pyenv: No such file or directory
```

To resolve this, I ran `pyenv rehash` and it started working again. Hopefully this helps someone with a similar issue.

**Comment by matej-novotny** [comment]
I am experiencing same issue as @robgyiv .
I am fixing this by find and replace in my text editor. I replace old version in path in all file in `/Users/.../.pyenv/shims/` with new version.

**Comment by RichardBronosky** [comment]
Nothing about the `rehash` command description suggests that it would help this, but I followed the advice of @robgyiv and I'm back up and running.
Someone who knows what a "shim" is should probably look into this and get better info in the install docs, FAQs, error messages, and seed Google with the information so that the top hit for https://www.google.com/search?q=pyenv+upgrade+homebrew+no+such+file+or+directory is the correct answer if this is in fact a reliable way to fix this issue.
I'm willing to do my part and create a StackOverflow question with good google-fu and give a good answer. But, I don't want to lead others astray if it is a fluke that this worked. (Did I mention that I don't even know what a shim is?) ✌🏼❤️⅋🌈

**Comment by coredumperror** [comment]
I just found this thread as the top google result for "ran brew upgrade, now pip pyenv is broken", and `pyenv rehash` fixed my issue.

**Comment by cscetbon** [comment]
I wonder why `pyenv rehash` is not added to the brew formula to avoid this issue ..
