### ISSUE TITLE
Upgrade an existing version to another, retaining packages

### ISSUE THREAD

**Issue by nyuszika7h** [pyenv/pyenv#906]
Is there any way to, say, upgrade 3.6.0 to 3.6.1, retaining any packages installed to 3.6.0 via `pip`, without manually doing `pip freeze` on 3.6.0 and then piping that to `pip install` on 3.6.1? (Actually, I realized this method while writing this issue, it's not so complicated, but it may be nice to automate this anyway.)

**Comment by saimn** [comment]
This would be especially useful with virtualenvs. It's cumbersome to have to recreate all envs just for a minor version update. Would it be possible to have a major/minor version distinction ?

**Comment by nvllsvm** [comment]
Look into using a user site-packages directory. It will organize packages by major/minor versions.
https://docs.python.org/3.7/library/site.html

**Comment by chrahunt** [comment]
There are several questions here, I'll try to get to all of them.

> Is there any way to upgrade 3.6.x to 3.6.y and retain packages without requiring re-installation?

There are two ways:

1. As mentioned by @nvllsvm, you can do `pip install --user`. This will install packages into `~/.local/lib/pythonX.Y/site-packages`, which would be used for all Python versions X.Y.z.
2. If using a virtual environment, patch version upgrades should not require re-installation of packages since they are put into `<venv dir>/lib/pythonX.Y/site-packages`

Now if you have already installed packages using a plain `pip install <pkg>`, that will end up in the main Python site packages directory at `~/.pyenv/versions/X.Y.Z/lib/pythonX.Y/site-packages`. That directory is specific to the Python installation but you can do something similar to what you proposed to get all packages installed in a new version (assuming you're using Bash):

```
~/.pyenv/versions/X.Y.z2/bin/python -m pip install -r <(~/.pyenv/versions/X.Y.z1/bin/python -m pip freeze)
```

> It's cumbersome to have to recreate all envs just for a minor version update. Would it be possible to have a major/minor version distinction?

Unfortunately not. There are a few things working against us here:

1. libraries that include compiled components will have a hard dependency on the specific Python version because it is what they were compiled against. In the best case these will just fail to import, but it may segfault or worse just behave incorrectly.
2. when installing a Python package, arbitrary code gets executed. Package maintainers must assume that a package installed under X.Y.z may run on a Python with any version for z. There is no such assumption for X.Y versions. Personally I wouldn't even consider it a bug if a package behaved in a way that did not support this.

Thankfully the burden of using multiple Python versions is becoming less every day. Tools like `Pipenv` and `poetry` manage Python-version-specific virtual environments for us and handle installation of all required dependencies, and `tox` has been able to do cross-version testing for years and years.

**Comment by native-api** [comment]
@sandman You may ant to check out https://github.com/pyenv/pyenv/wiki/Plugins and in particular, https://github.com/ashwinvis/pyenv-virtualenv-migrate .
