### ISSUE TITLE
Make python-build an independent repository.

### ISSUE THREAD

**Issue by tell-k** [pyenv/pyenv#913]
pyenv authors.

First, thanks for the awesome tool.

I know that [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) can be used standalone. But I think it is a waste to clone the entire pyenv repository.

I think that it is better for many users to make python-build an independent repository like r[uby-build](https://github.com/rbenv/ruby-build).

Do you plan to do such things? Please tell me your opinion.
Please let me cooperate if you plan to do so.

thx.

**Comment by jayvdb** [comment]
I think this would be useful, and allow better CI because the build repo can focus on verifying builds work, which can be very heavy CI (e.g. https://github.com/pyenv/pyenv/pull/617), and then then pyenv repo can focus on user functionality/usability/compatibility issues of the scripts.

https://github.com/pyenv/pyenv/issues/879 and https://github.com/pyenv/pyenv/issues/882 also relevant. ping @Samureus

**Comment by joshfriend** [comment]
Similar projects like nodenv and rbenv took this approach and I've found it to be annoying because 99% of users will want the `*-build` plugin by default. For most people `*env` is useless without the plugin to build the interpreter. Keeping `python-build` in the same repo is a super easy way of making install painless for most users.

**Comment by jayvdb** [comment]
Ya, thanks for mentioning the negative ;-)

What about using a git subtree to pull in the *-build.

https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging

For most users that should be an automatic part of a clone operation.

Maintainers would typically get a bit cranky if a PR here contained lots of *-build changes, but it would be up to maintainers to decide when a change should have been sent to the *-build repo first.

There is also a repo-CI-chaining trick so that any change to *-build in this repo would trigger a build of the same changes in the *-build repo.  I could dig it up if the use of git subtrees might be useful.
