### ISSUE TITLE
install 2.7.13 failed on Centos 4.3

### ISSUE THREAD

**Issue by baocaixiong** [pyenv/pyenv#915]
```
/home/zhangming/.pyenv/plugins/python-build/bin/python-build: line 277: printf: -v: invalid option
printf: usage: printf format [arguments]
/home/zhangming/.pyenv/plugins/python-build/bin/python-build: line 279: return: : numeric argument required
basename: too few arguments
Try `basename --help' for more information.
Downloading ...

BUILD FAILED (CentOS 4.3 using python-build 1.0.10-22-g3292200)
```

**Comment by chrahunt** [comment]
You probably have a very old version of bash. You can try upgrading, however you may be in for a long journey as other basic command-line utilities and Python dependencies require manual compilation or setup. I don't think this activity is appropriate to track here since it isn't a pyenv issue per-se, but you can always reach out on gitter or IRC and we can try to help troubleshoot.

I've also started a wiki page [here](https://github.com/pyenv/pyenv/wiki/Supported-platforms) so we start being a little more explicit about what is and isn't supported.
