### ISSUE TITLE
python update returns error when HEAD has an annotated tag

### ISSUE THREAD

**Issue by mventimi** [pyenv/pyenv#952]
With the latest (7/17/17) to pyenv, I'm seeing the following error when I run pyenv update:

```
root@localhost:/# pyenv update
Updating /opt/pyenv...
pyenv-update: /opt/pyenv is not on master branch.
...
```

The update seems to proceed ok after that, but the command returns an error code. The pyenv-update script is using `git name-rev --name-only HEAD` to get the branch name, but if an annotated tag exists on HEAD, this command returns that tag instead. `git rev-parse --abbrev-ref HEAD` may be more appropriate.

**Comment by blueyed** [comment]
`pyenv` itself has no `update` command?  At least for me (I am using the git checkout).

**Comment by mventimi** [comment]
I'm using [pyenv-installer](https://github.com/pyenv/pyenv-installer) to install pyenv on my system, as it seems to be the recommended install method. That script installs a number of pyenv-* plugins, including pyenv-update. I would have opened this issue directly against pyenv-update, but that repo does not have issues enabled.

**Comment by bkbncn** [comment]
There is a "solution" to bypass it, deleting the directory `/.git/refs/tags` under your `pyenv`.

Your solution is good for git 1.7+, but someone may still use older git.
And it does not work in a 'detached HEAD' state, if after using `git checkout`, repo will be 'detached HEAD' state.

Also I have a feeling, pyenv-update is deprecated, just as some other pyenv plugins, since in README here, the "official" way to upgrade is `git pull` or `git checkout`.

I know there are still a lot of people using pyenv-update, including me, to fix the error, I think the "stupid" `git branch` with grep or sed is safer.

There are more details about getting current branch name.
http://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git
